### PR TITLE
Trimmed whitespaces on forge variables to prevent malformed URLs

### PR DESCRIPTION
**Pull request by jdlovins**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
@jdlovins Can you explain what this actually does please?

**Comment by jdlovins** [comment]
@parkervcp if there is a whitespace after the ; in the settings file it will cause a malformed URL. This just strips white spaces, return carriages, tabs, etc so that doesn't happen.

**Comment by parkervcp** [comment]
Is there a reason you replaced `echo -e ${FORGE_VERSION}` with `FORGE_VERSION="${FORGE_VERSION// /}"` in there as well?

line 135 if you have it in a text editor.

**Comment by jdlovins** [comment]
@parkervcp Whoops, that was leftover for my first attempt at fixing it. that just strips out whitespaces but looks weird. 

Here is the better solution, adding the | tr -d at the end.

 MCVER=grep 'MCVER' settings.cfg | sed 's/;//g' | cut -d '=' -f 2- | tr -d '\040\011\012\015'
 FORGE=grep 'FORGEVER' settings.cfg | sed 's/;//g' | cut -d '=' -f 2- | tr -d '\040\011\012\015'

I removed that line from the pull request.

**Comment by parkervcp** [comment]
I'd appreciate if you put the echo back so it prints what forge version it's pulling. It really does help when diagnosing issues.

**Comment by jdlovins** [comment]
I didn't remove anything like that.  Here is the full function


```
function cfg_download_forge {
    dos2unix settings.cfg # In case the pack was distributed with Windows-style line endings in the cfg file
    MCVER=`grep 'MCVER' settings.cfg | sed 's/;//g' | cut -d '=' -f 2- | tr -d '\040\011\012\015'`
    FORGE=`grep 'FORGEVER' settings.cfg | sed 's/;//g' | cut -d '=' -f 2- | tr -d '\040\011\012\015'`

	if [ ${MCVER} == "1.7.10" ] || [ ${MCVER} == "1.8.9" ]; then
		FORGE="${FORGE}-${MCVER}"
	fi
    
    FORGE_VERSION="${MCVER}-${FORGE}"
    
    echo -e "\nDownloading Forge Version $FORGE_VERSION\n"
    echo -e "running curl -sS https://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-installer.jar -o installer.jar \n"
    curl -sS https://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-installer.jar -o installer.jar
    echo -e "running curl -sS https://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-universal.jar -O \n"
    curl -sS https://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-universal.jar -O
    java -jar installer.jar --installServer
    mv *universal.jar server.jar
    rm installer.jar
}
```

**Comment by jdlovins** [comment]
@parkervcp 

Fixed, sorry.

**Pull request merged**
