### PR TITLE
Update egg-beam-m-p-server.json

### PR DESCRIPTION
**Pull request by O1LER**
# Description

Fixed LogChat toggle, was a string before, now boolean
Changed max character limit on the server version string, was eight before, now 12

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by O1LER** [comment]
I removed the " ", it was writing `LogChat = "true"` before, now its correctly writing `LogChat = true`

**Comment by O1LER** [comment]
Ah, i see, it was \" in the configuration file window in the egg process management before, which means that it will turn into \\\" in the json file once exported, since both the \ and " have been commented out.

image
Will turn into
`\"Map =\": \"Map = \\\"{{env.MAP}}\\\"\",\r\n`
`\"LogChat =\": \"LogChat = {{env.LOGCHAT}}\"\r\n`
once exported

**Comment by O1LER** [comment]
Should i change more things? Or can we merge this?

**Comment by QuintenQVD0** [comment]
> Should i change more things? Or can we merge this?

Changes need to be tested by someone external. I did not have time yet and someone else also did not.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by O1LER** [comment]
Sorry about the impatience, i wasnt sure if you waited for me to change things. Thanks for merging 👍

**Pull request merged**
