### PR TITLE
FiveM - add arm check

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

Added s simple ARM Check, because, its possible to install FiveM on ARM and then install fails, with "file not found"

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
This will not work. The install image is amd64 only. So it will just say exec format error. And not even run the script

**Comment by gOOvER** [comment]
looks like, it wokrs. A lot of people trying to install FiveM on arm and there was never any exec error; only file not found

**Comment by QuintenQVD0** [comment]
It will say not found on start. And then we ask for the install logs that just say exec format error

**Comment by QuintenQVD0** [comment]
And if the want to host gta v on arm64 tell them to use ragemp if this: #2134 gets merged

**Comment by gOOvER** [comment]
> And if the want to host gta v on arm64 tell them to use ragemp if this: #2134 gets merged

Rage is not FiveM.

Thats the best solution to tell people, that an egg is not ARM Compatible and so lesser support and discussions about arm, as long ptero dont check this

**Comment by QuintenQVD0** [comment]
There is no point on adding this as this will not even run on install. It is already added to the readme. We can add it to the startup cmd. But not in the install script

**Comment by gOOvER** [comment]
> There is no point on adding this as this will not even run on install. It is already added to the readme. We can add it to the startup cmd. But not in the install script

noone reads the readme; Startup is the wrong place; correct place is installscripot, because it the first thing what runs after setting up a server.

**Comment by QuintenQVD0** [comment]
It will not even run. Wy do you not understand that, this docker image ghcr.io\/parkervcp\/installers:debian is only build for amd64 so it will pull that and then just exit as the image is not build for the system arch, IT will not execute anything of the install script

**Comment by QuintenQVD0** [comment]
zlos you removed the Download Link variable

**Comment by gOOvER** [comment]
i dont have time to discuss; sry. I tested iot and it works

**Comment by QuintenQVD0** [comment]
@gOOvER :
afbeelding

**Pull request closed without merging**
