### PR TITLE
V Rising BepInEx: Winetricks add mono

### PR DESCRIPTION
**Pull request by Upd4ting**
# Description

I don't really know why but I had problems with the `dotnet6` installation but the installation is working well by installing `mono` first.

It seems others people than me was having the problem so it may be a good idea to add it as a default value.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You can not edit the json file directly!!! Make the changes in the panel, save, export and fully replace the file here.

**Comment by Upd4ting** [comment]
> You can not edit the json file directly! Make the changes in the panel, save, export and fully replace the file here.

Sorry, it should be good now i've exported the file from the panel

**Comment by QuintenQVD0** [comment]
Something went real wrong as those spaces and tabs are messed up

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you

**Comment by Upd4ting** [comment]
@QuintenQVD0 Is there any reason that you have updated wine to latest? For me the VRising server does not load when running on wine latest but does load with wine staging

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Is there any reason that you have updated wine to latest? For me the VRising server does not load when running on wine latest but does load with wine staging

Wine staging has some console bugs. But it should work. If not then sorry. It is just a habbit as wine staging was broken for a long time. Feel free to pr the changes back to staging. I merge it asap.

**Pull request merged**
