### PR TITLE
V Rising BepInEx: Wine staging version

### PR DESCRIPTION
**Pull request by Upd4ting**
# Description

It seems the server doesn't want to load using `wine` latest version. By using the staging version the server load correctly.

## Checklist for all submissions
* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by gOOvER** [comment]
staging have no consoleoutout, thats why stable is used.

**Comment by QuintenQVD0** [comment]
> staging have no consoleoutout, thats why stable is used.

It was staging. I pushed it to latest but he claims now it does not work anymore.

**Comment by Upd4ting** [comment]
> > staging have no consoleoutout, thats why stable is used.
> 
> It was staging. I pushed it to latest but he claims now it does not work anymore.

Yeah for me loading a server with wine latest was stuck at the startup command where it starts the `VRisingServer.exe`. It was stuck at this step, with no crash and no usual logs that the server output when it starts

**Comment by QuintenQVD0** [comment]
> > > staging have no consoleoutout, thats why stable is used.
> > 
> > 
> > It was staging. I pushed it to latest but he claims now it does not work anymore.
> 
> Yeah for me loading a server with wine latest was stuck at the startup command where it starts the `VRisingServer.exe`. It was stuck at this step, with no crash and no usual logs that the server output when it starts

When switching wine vetsion you must remove the .wine folder.

**Comment by Upd4ting** [comment]
> > > > staging have no consoleoutout, thats why stable is used.
> > > 
> > > 
> > > It was staging. I pushed it to latest but he claims now it does not work anymore.
> > 
> > 
> > Yeah for me loading a server with wine latest was stuck at the startup command where it starts the `VRisingServer.exe`. It was stuck at this step, with no crash and no usual logs that the server output when it starts
> 
> When switching wine versions you must remove the .wine folder.

I tested with a fresh server so the problem was not coming from that

**Comment by gOOvER** [comment]
ill test it right now

**Comment by gOOvER** [comment]
Funny Thing; he's right. Wine stable have no console output and stanging have one :D I do more tests :D

**Review by gOOvER — APPROVED** [review]
this egg really needs staging. :D Test it with stable; stuck on start (no consoleoutput). Running with staging, server is online and i can connect.

VRising_jHxkLoxfD7

**Comment by gOOvER** [comment]
<But pls export the egg from panel; idk what you are doing, but you change the whole egg

**Comment by Upd4ting** [comment]
@gOOvER done
I'm exporting the egg from panel each time, don't know why it is changing the whole egg each time sorry

**Comment by gOOvER** [comment]
[egg-v-rising-bep-in-ex.json](https://github.com/parkervcp/eggs/files/13321989/egg-v-rising-bep-in-ex.json)

pls try to upload this file. idk, what going wrong with your installation

**Comment by QuintenQVD0** [comment]
@Upd4ting indeed your instalation is messed up with those spaces. Please update to use the egg he send.

**Comment by gOOvER** [comment]
> @gOOvER done I'm exporting the egg from panel each time, don't know why it is changing the whole egg each time sorry

what do you use to upload to github?

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
LGTM! thank you

**Pull request merged**
