### PR TITLE
Rising-World - split to legacy (java) and unity Version

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

Rising World switch to Unity in near Future. So the Java Version is no longer maintained. Savegames are not compatible with the new Unity Version.

More Infos: [https://forum.rising-world.net/thread/12060-important-notice-for-server-hoster/](https://forum.rising-world.net/thread/12060-important-notice-for-server-hoster/
)

Changelog legacy version:

- switch to PTDL_v2
- update all images to yolk
- add legacy branch to prevent that the server will overwritten with new Unity Version

Changelog Unity Version:

- added new Unity Version. As long its not in mainbranche, you must use the betabranch `unity`
- update all readmes

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

### CODE REVIEW

**Comment by gOOvER** [comment]
Converted to draft, so i can add the Unity Server too

**Comment by gOOvER** [comment]
added Unity Version too

**Comment by QuintenQVD0** [comment]
Please add them also like this in the main README: 
afbeelding

Then it is fine for me if you can join both.

**Comment by gOOvER** [comment]
> Please add them also like this in the main README: afbeelding
> 
> Then it is fine for me if you can join both.

done

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
