### PR TITLE
Bump default version to 1.16.5

### PR DESCRIPTION
**Pull request by GeekCornerGH**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
 

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### Description
So, Minecraft 1.16.5 is released, and Mohist bumped their latest builds to 1.16.5. **1.16.5 and 1.16.4 still crossplayable**, but 1.16.5 resolve some crashs, and is recommanded.

### CODE REVIEW

**Comment by parkervcp** [comment]
I swear i had this set to accept "latest" as a version instead of needing to bump versions like this...

**Comment by GeekCornerGH** [comment]
Really?

**Comment by GeekCornerGH** [comment]
Ok lemme do it

**Comment by GeekCornerGH** [comment]
- [x] Done 🙂

**Comment by Software-Noob** [comment]
`latest` as of now is an invalid Minecraft version since the mohist API doesn't support it for MC_VERSION nor does the install script regex for it at this moment.

**Comment by parkervcp** [comment]
> 
> 
> `latest` as of now is an invalid Minecraft version since the mohist API doesn't support it for MC_VERSION nor does the install script regex for it at this moment.

Yeah I realized the other night. I have been meaning to look into supporting a `latest` version.

**Comment by parkervcp** [comment]
@GeekCornerGH please revert the version change to 1.16.5 until I can look at adding a "latest" flag.

**Comment by GeekCornerGH** [comment]
Here you are @parkervcp

**Pull request merged**
