### PR TITLE
[rust-staging] fix: Install script ignoring Branch env variable

### PR DESCRIPTION
**Pull request by Winter**
# Description

Fixes startup script not respecting the branch startup option for the rust-staging egg

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
> # Description
> Fixes startup script not respecting the branch startup option for the rust-staging egg
> 
> ## Checklist for all submissions
> * [x]  Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
> * [x]  Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
> * [x]  Have you tested and reviewed your changes with confidence that everything works?
> * [x]  Did you branch your changes and PR from that branch and not from your master branch?
>   
>   * If not, why?:
> 
> * [x]  You verify that the start command applied does not use a shell script
>   
>   * [x]  If some script is needed then it is part of a current yolk or a PR to add one
> * [x]  The egg was exported from the panel

Re-read the last asked question in the readme

**Comment by Winter** [comment]
> > # Description
> > Fixes startup script not respecting the branch startup option for the rust-staging egg
> > ## Checklist for all submissions
> > 
> > * [x]   Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
> > * [x]   Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
> > * [x]   Have you tested and reviewed your changes with confidence that everything works?
> > * [x]   Did you branch your changes and PR from that branch and not from your master branch?
> >   
> >   * If not, why?:
> > * [x]   You verify that the start command applied does not use a shell script
> >   
> >   * [x]   If some script is needed then it is part of a current yolk or a PR to add one
> > * [x]   The egg was exported from the panel
> 
> Re-read the last asked question in the template

I apologize for misunderstanding the context. I took it to mean something to the effect of ensuring that the egg still exports from the panel.

**Comment by QuintenQVD0** [comment]
> > > # Description
> > > Fixes startup script not respecting the branch startup option for the rust-staging egg
> > > ## Checklist for all submissions
> > > 
> > > * [x]    Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
> > > * [x]    Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
> > > * [x]    Have you tested and reviewed your changes with confidence that everything works?
> > > * [x]    Did you branch your changes and PR from that branch and not from your master branch?
> > >   
> > >   * If not, why?:
> > > * [x]    You verify that the start command applied does not use a shell script
> > >   
> > >   * [x]    If some script is needed then it is part of a current yolk or a PR to add one
> > > * [x]    The egg was exported from the panel
> > 
> > 
> > Re-read the last asked question in the template
> 
> I apologize for misunderstanding the context. I took it to mean something to the effect of ensuring that the egg still exports from the panel.

It stats that all changes to an egg must be made on the panel and exported. Then replace the whole egg here. Not just 1 line. You can not edit directly the json as we may need the exported_at value in the future

**Comment by Winter** [comment]
Not sure why the PR closed when I reset the branch.. but I exported the egg from the panel. Again, apologies for any inconvenience.

**Review by QuintenQVD0 — APPROVED** [review]
Lgtm! Thanks

**Pull request merged**
