### PR TITLE
update forge egg for latest update

### PR DESCRIPTION
**Pull request by parkervcp**
Forge is bringing standard jars back and this will skip unix args if there is a jar.

# Description

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
is there a reason this got removed?
```bash

echo "-----------------------------------------"
echo "Installation completed..."
echo "-----------------------------------------"
```

**Comment by parkervcp** [comment]
> is there a reason this got removed

I copy and pasted the install script from an old egg. I have re-added it.

**Review by QuintenQVD0 — APPROVED** [review]
Looks fine to me

**Review by PaintNinja — APPROVED** [review]
The code comments are outdated (still says executable jar only below 1.17), but functionally this looks good, thanks :)

**Pull request merged**
