### PR TITLE
Rathole

### PR DESCRIPTION
**Pull request by TunayAdaKaracan**
# Description

It is server side rathole egg for rathole software. 

I don't have much experience in creating an egg and overall linux. So i copied a lot from rust generic egg.
Note: It didn't work with debian yolk so i just instead used rust one which works fine.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by parkervcp** [comment]
I don't see why this would be needed for pterodactyl

**Comment by TunayAdaKaracan** [comment]
I did for my self usage mainly as i have a raspberry pi. But wanted to share it. Rather it would be more useful if you are self hosting pterodactyl and not a daily user

**Comment by QuintenQVD0** [comment]
This is a reverse proxy application, as web hosting is not supported and for other application will not work that well in docker containers, I am closing this

**Comment by parkervcp** [comment]
They explained themselves and this can proxy more than just web services.

**Comment by QuintenQVD0** [comment]
if you see it from that point then I guess this can stay open indeed

**Comment by TunayAdaKaracan** [comment]
I would like to say, rathole is more of a tunneling software that can be alternative to ngrok and playit.gg. Even tho they start as free it is cheaper to afford a small ptero server if you are planning to tunnel more than one port. (Resource usage is really low with rathole). This could be useful for those who have single board computers or for those who don't have a static ip to port forward. It really depends on what you need to view this as useful or not. In my case, since i have a rasp pi i find it useful for tunnelling my socket applications, ssh and othee things.

**Comment by TunayAdaKaracan** [comment]
One side note, unlike ngrok and playit. Your ip doesn't change with rathole. Imagine your wifi goes offline for sometime and you will have to login from home network to see what is your connection ip now. Doesn't sound fun, right?

**Comment by QuintenQVD0** [comment]
> One side note, unlike ngrok and playit. Your ip doesn't change with rathole. Imagine your wifi goes offline for sometime and you will have to login from home network to see what is your connection ip now. Doesn't sound fun, right?

I have a pi myself, I just setup my pi to have a static reserved local ip and that is forwarded to the public ip what is also static

**Comment by parkervcp** [comment]
> > One side note, unlike ngrok and playit. Your ip doesn't change with rathole. Imagine your wifi goes offline for sometime and you will have to login from home network to see what is your connection ip now. Doesn't sound fun, right?
> 
> I have a pi myself, I just setup my pi to have a static reserved local ip and that is forwarded to the public ip what is also static

This is calling out the external ip not being static, not the internal ip for the pi

**Comment by TunayAdaKaracan** [comment]
Also, if you don't have a static ip, most likely you are in a CGNAT where you can't port forward

**Comment by parkervcp** [comment]
> Also, if you don't have a static ip, most likely you are in a CGNAT where you can't port forward

This is not always true. I know Verizon in the US doesn't use CGNAT and you can use ddns to point at the address.

**Review by parkervcp — APPROVED** [review]

**Pull request closed without merging**
