### PR TITLE
Added minecraft forge build number support

### PR DESCRIPTION
**Pull request by NgLoader**
### All Submissions:

* [Yes] Have you followed the guidelines in our Contributing document?
* [Yes] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to an existing Egg:

1. [Yes] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [Yes] Have you tested your Egg changes?

### Changes
Added forge build number support.
Example:
``1.12.2``
or
``1.12.2-14.23.5.2811`` (with build number)

### CODE REVIEW

**Comment by NgLoader** [comment]
Thanks @ZeProf2Code

**Comment by ZeProf2Code** [comment]
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.9.0-17-g8b92b92a30 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.0-16-gfe0ab7c606 [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9750 distinct packages available
(1/4) Installing nghttp2-libs (1.35.1-r0)
7  0%                                             8[0K(2/4) Installing libssh2 (1.8.0-r4)
7 14% ██████                                      8[0K(3/4) Installing libcurl (7.63.0-r0)
7 31% ██████████████                              8[0K(4/4) Installing curl (7.63.0-r0)
7 77% ██████████████████████████████████          8[0K7100% ████████████████████████████████████████████8[0KExecuting busybox-1.29.3-r10.trigger
OK: 104 MiB in 58 packages
/mnt/install/install.sh: line 28: syntax error: unexpected end of file (expecting "fi")
`

When I'm trying to install a server

**Comment by NgLoader** [comment]
Oh, forge has made some changes
I make a fix for that

**Comment by ZeProf2Code** [comment]
Did you manage to fix it?

**Comment by NgLoader** [comment]
Its now working for me.
Have fun 😃

**Comment by ZeProf2Code** [comment]
Thanks :D

**Comment by ZeProf2Code** [comment]
Do a pull request on the official pterodactyl's forge egg :D

**Comment by NgLoader** [comment]
Okay

**Comment by parkervcp** [comment]
Use this grep for a replacement on your script - `grep -o -e '[1].[0-9]*.[0-9]* - [0-9]*.[0-9]*.[0-9]*.[0-9]*'`

**Comment by NgLoader** [comment]
Okay thanks

**Comment by ZeProf2Code** [comment]
@parkervcp did you see my mail that I send to you?

**Comment by parkervcp** [comment]
@ZeProf2Code This is not the place.

**Pull request merged**
