### PR TITLE
Added PhantomBot

### PR DESCRIPTION
**Pull request by NgLoader**
### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

Read the README pls to setup!
You need 3 ports for this bot!

### CODE REVIEW

**Comment by NgLoader** [comment]
Note: to enable all features you need to add the youtube api and discord api!

**Comment by gOOvER** [comment]
Wow, great. Installed it and works like charm.

MB You can add youtube and Discord API key field too

**Comment by gOOvER** [comment]
Would be nice, when you can also add "nightly" as realease

see: https://github.com/PhantomBot/nightly-build

**Comment by NgLoader** [comment]
OkayVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Torsten Widmann <notifications@github.com> Datum: 28.02.20  07:17  (GMT+01:00) An: parkervcp/eggs <eggs@noreply.github.com> Cc: NgLoader <nilsgereke1@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [parkervcp/eggs] Added PhantomBot (#441) Would be nice, when you can also add "nightly" as realease
see: https://github.com/PhantomBot/nightly-build

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/parkervcp/eggs/pull/441?email_source=notifications\u0026email_token=ADI534CUKJCFWKC74CEXPJDRFCT6JA5CNFSM4K5AMZ52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENHEOQA#issuecomment-592332608",
"url": "https://github.com/parkervcp/eggs/pull/441?email_source=notifications\u0026email_token=ADI534CUKJCFWKC74CEXPJDRFCT6JA5CNFSM4K5AMZ52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENHEOQA#issuecomment-592332608",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by NgLoader** [comment]
Okay, thats easy to add 😄

**Comment by NgLoader** [comment]
When you use the nightly version you need to change the docker image to ``quay.io/parkervcp/pterodactyl-images:debian_openjdk-11``

**Comment by gOOvER** [comment]
Workesd for me.

Maybe remove requiered|string from the fields, so you can host the bot for others without giving out Oauth Datas

**Comment by gOOvER** [comment]
For Nightly. You must use Java 11. With Java 13 i can't start the bot

**Comment by NgLoader** [comment]
Okay, i commit some changes soon

**Comment by NgLoader** [comment]
But why i shoud remove requiered|string?
You can host it without giving the other person permissions :thinking:

**Comment by gOOvER** [comment]
If requierd is set, YOU cant create a Server without adding something in the fields. Why it must requiered?

**Comment by NgLoader** [comment]
I can remove it but the bot require this values to start

**Comment by gOOvER** [comment]
I removed it. Only thing is, that Server will not start without Value's set.

For example. I want to host PB for a friend. When i try to install server, i need all his keys when i Setup the Server. If requiered is not set, heute can add if for his own.

**Comment by NgLoader** [comment]
Remove it from the configuration files in eggs -> phantombot -> configuration

**Comment by TheSoulrester** [comment]
awesome - thank you for the egg <3

but is that ok to use jdk13 for nightly instead of jdk11 like the dev of phantombot assumes?

**Comment by gOOvER** [comment]
Latest commits for for me. mb Parker can add it to Official Repro

**Comment by NgLoader** [comment]
You mean ``Latest commit works for me``? or?

**Comment by gOOvER** [comment]
> @gOOvER You mean `Latest commit works for me`? or?

Yeah :D Sry, autocomplete on mobile :D

**Pull request merged**
