### PR TITLE
Rewrite Egg Space Engineers Dedicated Server + added workshop support

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

egg was complete rewritten, because Author installed WINE4 in installscript and deleted all depencies from WINE 7. This cant work.

## Changelog:
- update to PTDL_v2
- update Image to Wine Staging
- updated steam installscript to latest
- changed installimage
- cleanup installscript and remove useless wine installtion
- updated startup
- move winetricks_install to variable
- updated server config to latest
- update premade World to latest
- egg supports now Workshop mods

## This PR closes following issues:
closes: #1578
closes: #1602 
closes: #1691

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by gOOvER** [comment]
Login:

```
2022-11-05 07:48:28.992: Peer2Peer_SessionRequest [007...250]
2022-11-05 07:48:34.053: OnConnectedClient gOOvER|OldNoobTV attempt
2022-11-05 07:48:34.294: Server ValidateAuthTicketResponse (OK), Steam ID:[007..
.250] Owner ID:[007...250]
2022-11-05 07:48:34.450: World request received: gOOvER|OldNoobTV
2022-11-05 07:49:23.510: Loaded 497 Steam Inventory item definitions
2022-11-05 07:50:45.105: User left gOOvER|OldNoobTV
2022-11-05 07:50:45.118: Disconnected: [007...250]
STEAMPS3 - AsyncTCPSocket created
```

**Comment by gOOvER** [comment]
Server List:
SpaceEngineers_SgAnxuCUzf

**Comment by gOOvER** [comment]
fixes:

- https://github.com/parkervcp/eggs/issues/1578
- https://github.com/parkervcp/eggs/issues/1691
- https://github.com/parkervcp/eggs/issues/1752
- https://github.com/parkervcp/eggs/issues/1602

**Review by Fuggschen — COMMENTED** [review]
Helped testing those changes and they are fully working on my setup.
Server installs all dependencies and starts without errors anymore. Mods are also working fine.

**Review by Braastos — APPROVED** [review]
Can confirm that this server works. Have one server running since over a week, no Problems

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
