### PR TITLE
Update Palworld

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- Add and download a self written parser application for their (bad) config file
- Add a working console over RCON
- allow toggling bEnableInvaderEnemy what is known for memory leaking
 
 If anyone want to see the source of the parser application: https://github.com/QuintenQVD0/Palword-server-config-parser and yes it does also work on Windows even tho that is not pterodactyl related.
 
 **For Those updating an exiting egg / server**
 1. Update your egg
 2. Update the startup of all already made servers to the one that now comes with the egg
 3. Then hit reinstall because the parser application has to be downloaded 

**For those testing this egg**
This will not work as long as this is not merged
If you want to test this egg, on line 64 replace the link:
-> `https://raw.githubusercontent.com/parkervcp/eggs/master/game_eggs/steamcmd_servers/palworld/PalworldServerConfigParser-linux-amd64` 
to:
-> `https://github.com/QuintenQVD0/Palword-server-config-parser/releases/latest/download/PalworldServerConfigParser-linux-amd64`
## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by GameAreaCZ** [comment]
Works fine! Thank you for your work.

**Comment by lilkingjr1** [comment]
How is the parser application used? It is a welcomed addition, but the install script only downloads it and it doesn't seem to be used again.

**Comment by QuintenQVD0** [comment]
> How is the parser application used? It is a welcomed addition, but the install script only downloads it and it doesn't seem to be used again.

Its in the startup. Its the first things that runs.

**Comment by Toetje585** [comment]
Works awesome, thanks for the effort!

**Comment by lilkingjr1** [comment]
@QuintenQVD0 Oh my goodness, my bad, totally missed that.

**Comment by lilkingjr1** [comment]
@QuintenQVD0 If I set a setting (like `DeathPenalty=None`) in the config that is not currently handled by your script, will it get overwritten?

**Review by parkervcp — APPROVED** [review]
This is working so far as I am concerned.

**Comment by j-barot** [comment]
I don't know how to use RCON ... Anyone can explain me ? ^^

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 If I set a setting (like `DeathPenalty=None`) in the config that is not currently handled by your script, will it get overwritten?

No. The application will not touch variables I have not set to be parsed. So as in your example if you manual edit the DeadPenalty to something else then that will just stay as you set it. Until you hit reinstall because then a fresh config is made.

**Pull request merged**
