### PR TITLE
Add: Automanaged Mods, MOD_ID Field

### PR DESCRIPTION
**Pull request by Cryotize**
# Description

I haven't seen any recent posts about automanaged mods being a problem on Linux. This is why i want to add modding support to the official Egg. I use automanaged mods since about 2 years with LinuxGSM without any problems.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by gOOvER** [comment]
idk, if this is all. As i know, you must also add the mods to the config

**Comment by Cryotize** [comment]
I can test it again later today, but if I'm not mistaken, this should be good. According to the official wiki, it should work: https://ark.fandom.com/wiki/Server_configuration

**Comment by Cryotize** [comment]
Alright, I've been able to test it again, with success. Server loads Mods, same goes for my client when joining the server, mods are available in game.

Also, notice how the descriptions on the wiki are identical for mod loading by using the command line option and GameUserSettings.ini.

This matches the official 190.0 Patchnotes: https://ark.fandom.com/wiki/190.0

**Comment by alex4401** [comment]
> I can test it again later today, but if I'm not mistaken, this should be good. According to the official wiki, it should work: https://ark.fandom.com/wiki/Server_configuration

[That is actually not the official wiki since April this year.](https://survivetheark.com/index.php?/articles.html/community-crunch-312-desmodus-reveal-official-ark-wiki-and-more-r1922/)

**Comment by QuintenQVD0** [comment]
LGTM! 

> Alright, I've been able to test it again, with success. Server loads Mods, same goes for my client when joining the server, mods are available in game.
> 
> Also, notice how the descriptions on the wiki are identical for mod loading by using the command line option and GameUserSettings.ini.
> 
> This matches the official 190.0 Patchnotes: https://ark.fandom.com/wiki/190.0

DId you had to add anything to a config file for this to work?

**Comment by Cryotize** [comment]
> LGTM!
> 
> DId you had to add anything to a config file for this to work?

Nope, only added the command-line options.

**Comment by QuintenQVD0** [comment]
> > LGTM!
> > DId you had to add anything to a config file for this to work?
> 
> Nope, only added the command-line options.

So you confirm that with adding that 1 variable and change the startup cmd it loads mods now?

**Comment by Cryotize** [comment]
> > > LGTM!
> > > DId you had to add anything to a config file for this to work?
> > 
> > 
> > Nope, only added the command-line options.
> 
> So you confirm that with adding that 1 variable and change the startup cmd it loads mods now?

Yes, exactly.

**Comment by QuintenQVD0** [comment]
SO LGTM!

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
