### PR TITLE
Added OpenTTD

### PR DESCRIPTION
**Pull request by ProJaCore**

### CODE REVIEW

**Comment by ProJaCore** [comment]
If I move to a stock image, it will break the ability to load last saved games.

**Comment by ProJaCore** [comment]
Well people have to manually load the game after they did stop the server or the server did crash. Its not an big issue tho

**Comment by ProJaCore** [comment]
The game will save the current game into multiplie files; so you have to load one autosave file depending on what the latest save file is.

**Comment by parkervcp** [comment]
I am closing this for now as the save system for the game is terrible to work with.

**Pull request closed without merging**
