### PR TITLE
Update Server.cfg - Add Mission Selection

### PR DESCRIPTION
**Pull request by QuickCentralHosting**
This adds the ability for players to select the mission their server boots up to and adds the ability to cycle missions.

### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the nesessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
how are these supposed to selected in the egg?

**Comment by QuickCentralHosting** [comment]
These additions are supported by Arma 3 itself. So any standard server.cfg file will have these. This gives people the ability to choose the missions they play vs loading just the server and then for an admin to log in and select the mission. 

This is a needed thing for most of the Arma 3 gaming community.

**Comment by parkervcp** [comment]
I am just asking if they needed to be a variable or anything.

**Comment by QuickCentralHosting** [comment]
Sorry parker, it doesn't need to be a variable. It would be nice if it could be

**Pull request merged**
