### PR TITLE
Add Rust generic egg (discord.rs)

### LINKED ISSUE #1250: [Egg Request]: Serenity / Rust
### Service

discord bot / serenity

### Does this expand an already existing service

No

### Link to game

https://github.com/serenity-rs/serenity

### Links for server downloads

https://github.com/serenity-rs/serenity

### Links for the install docs

https://github.com/serenity-rs/serenity#installation

### PR DESCRIPTION
**Pull request by CDE90**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Did you PR the necessary changes to make it work? (https://github.com/parkervcp/yolks/pull/52)
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

Closes #1250

### CODE REVIEW

**Comment by yesBad** [comment]
why did you name it serenity if its just rust (the language)0

**Comment by CDE90** [comment]
I named it that way to match the serenity crate. Should I change it to just rust or discord.rust to match the other generic eggs?

**Comment by parkervcp** [comment]
@CDE90 Can you make sure the images work before I accept this PR?

https://github.com/users/parkervcp/packages/container/package/yolks

**Comment by CDE90** [comment]
> @CDE90 Can you make sure the images work before I accept this PR?
> 
> https://github.com/users/parkervcp/packages/container/package/yolks

I've tested all the images again, and they are all working correctly

**Comment by parkervcp** [comment]
> > @CDE90 Can you make sure the images work before I accept this PR?
> > https://github.com/users/parkervcp/packages/container/package/yolks
> 
> I've tested all the images again, and they are all working correctly

Just wanted to be sure as they hadn't been merged into my repo yet.

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
