### PR TITLE
Changed max members and token field

### PR DESCRIPTION
**Pull request by PilaScat**
# Description
Updated to 12 max members and 60 for token length

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] You verify that the start command applied does not use a shell script
* [x] Did you branch your changes and PR from that branch and not from your master branch?
* [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]
You did not read the checklist! this is not exported from a panel

**Comment by PilaScat** [comment]
It's the same, I don't know how to make it otherwise

**Comment by PilaScat** [comment]
In theory it shouldn't be because of my changes since the server hasn't started yet and the original docker I'm already using has always worked with these settings

**Comment by PilaScat** [comment]
Here the compiler error: (I'm on x86_64)
image

**Comment by Z3r0byte** [comment]
Must admit that I didn't look too closely at which values should be allowed there since I don't use them, so thanks for the PR. It seems indeed that the yuzu team has made some changes to their source code in the meantime, making that warning pop up. However, compilation still succeeds as its only a warning (just ran a reinstall and that worked).

Maybe there is some way to suppress that warning, although they can of course also be useful for debugging if something goes wrong, so I am not sure if that is something we want to do.

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
LGTM!

**Pull request merged**
