### PR TITLE
add wine generic egg

### PR DESCRIPTION
**Pull request by parkervcp**
This is mostly for testing. It's not guaranteed to work.

default will install beamng-mp. May or may not work.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by docimin** [comment]
Seems to work.

**Comment by parkervcp** [comment]
@Software-Noob can you approve this?

**Review by AevumDecessus — APPROVED** [review]

**Comment by Software-Noob** [comment]
> @Software-Noob can you approve this?

This should've been updated to use game_eggs/ path as the folder structure was changed

**Comment by parkervcp** [comment]
🤷🏻 We have several from people that will probably never update it.

**Pull request merged**
