### PR TITLE
Add Minetest

### PR DESCRIPTION
**Pull request by niansa**
Everything works except sending console commands to server (they will just get ignored). That happens because of an bug (?) in the Minetest engine, so I can't fix that.

This egg will not configure the minetest.conf!
Edit: The Server will automatically set the correct port.

### CODE REVIEW

**Comment by niansa** [comment]
This script does not allow the user to select an Minetest version to avoid bugs.

**Comment by niansa** [comment]
ooh... Okay I will try it...

**Comment by niansa** [comment]
Done.

**Comment by parkervcp** [comment]
This looks better. Can you please add a README to the minetest forder and update the main README as well.

**Comment by niansa** [comment]
Done.

**Comment by parkervcp** [comment]
I will be closing this in favor of getting a new PR that uses the new PR template I have added to the repo.

If you still want to add this please resubmit a PR for this.

**Pull request closed without merging**
