### PR TITLE
fix(pocketmine): New PHP binary download URL

### LINKED ISSUE #2082: [Install Bug]: Pocketmine
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

pocketmine installation

### Modified

No, I did not modify the egg

### Expected Behavior

Hello, what happens is that I'm trying to install a pocketmine server and it doesn't download some data, I see the error that it releases and it's the following

image

### Console

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:1aa05ed709a704e2308096330b1b1568a2c44eba16efe293e23b3a89b5abc75b 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi
/entrypoint.sh: line 13: ./bin/php7/bin/php: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

### Steps To Reproduce

none

### Install logs

https://pteropaste.com/9hizt2/

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- change the PHP download link as there preparing for pm5 so the switched the naming for there php builds

closes #2082

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by Software-Noob — APPROVED** [review]
LGTM. Thanks for contributing :+1:

**Comment by dktapps** [comment]
You might want to do it this way, so that it automatically selects the right binary for the major version used: https://github.com/pmmp/get.pmmp.io/commit/13aea9cd28d8a757c0e8defd79f07af475d6a558. https://update.pmmp.io/api will also recommend a PHP version to use (currently 8.0, but will change in the future).

**Comment by QuintenQVD0** [comment]
> You might want to do it this way, so that it automatically selects the right binary for the major version used: [pmmp/get.pmmp.io@13aea9c](https://github.com/pmmp/get.pmmp.io/commit/13aea9cd28d8a757c0e8defd79f07af475d6a558). https://update.pmmp.io/api will also recommend a PHP version to use (currently 8.0, but will change in the future).

It will when pm5 releases. We will drop support for pm3 and only have pm4 and pm5

**Comment by dktapps** [comment]
PM3 hasn't been updated in 10 months. You could probably drop it already.

**Comment by QuintenQVD0** [comment]
> PM3 hasn't been updated in 10 months. You could probably drop it already.

It will. But no need to do it rn. It can be 1 pr for adding pm5 and removing 4.

**Comment by LtAkmal** [comment]
Hello, can you update the PHP again?

i think the link for download PHP are broken

**Comment by QuintenQVD0** [comment]
> Hello, can you update the PHP again?
> 
> i think the link for download PHP are broken

No there not. There download page is ofline. You downloaded ad everyone else the 400 page

**Pull request merged**
