### PR TITLE
Fix Eco start done config

### PR DESCRIPTION
**Pull request by Magi1053**
The server is outputting `[Server Initialization]...` when it first starts and not when it finishes starting. Fix server startup done config by adding `Finished in`.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by gOOvER** [comment]
There are more languages than Englisch. When an other language is used, this will break the Server started

**Comment by acl1704** [comment]
There are already plenty of eggs that rely on English output. If this makes the status change work as expected, then I think that's fine. Right now the functionality isn't correct.

**Comment by gOOvER** [comment]
Sry, but the Egg wirk as it should. This change is not needed and break a lot

**Comment by gOOvER** [comment]
What you can use:

Webserver now listening

**Comment by gOOvER** [comment]
> There are already plenty of eggs that rely on English output. If this makes the status change work as expected, then I think that's fine. Right now the functionality isn't correct.

It is and only one will have this; so he can change it to the line he want and no need to break it for others.

And pls show me the other eggs ;)

ECO Server is other than other Server. THe whole output is translated, when u change the Language

**Review by gOOvER — CHANGES_REQUESTED** [review]
This break the Startup fopr other languages than english

You can use: `Webserver now listening` insteed

**Comment by Magi1053** [comment]
It's too bad that it doesn't support regex

**Comment by Software-Noob** [comment]
> It's too bad that it doesn't support regex

It will match the string, doesn't have to be a full exact string. Arrays can also be used to configure multiple different strings.

**Pull request merged**
