### PR TITLE
Add Lavalink

### PR DESCRIPTION
**Pull request by Kashalls**
Downloads Latest Stable Build 7107

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [X] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?

This build requireds the `quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre` docker image.

3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

I understand as this might be a useless addition but it allows some of the bots that self host but require a Lavalink server to be hosted here as well.

### CODE REVIEW

**Comment by Kashalls** [comment]
Please hold off on this PR. I forgot to implement grabbing the latest file as I was unsure how to do it effectively.

**Comment by ZandercraftGames** [comment]
+1 on this. I would find it extremely useful. Is development continuing on it or not?

**Comment by Kashalls** [comment]
> +1 on this. I would find it extremely useful. Is development continuing on it or not?

Many thanks, I currently am working on the script still, team city doesnt make their api very helpful and I am having a hard time allowing it to choose what branch to download from because in the stable edition, youtube sourcing is broken. But in some dev versions, this is fixed. Let me know in Discord if you have any recommendations.

**Comment by parkervcp** [comment]
Doesn't the dev do releases on github? If they do I have a github release grabber now.

**Comment by ZandercraftGames** [comment]
@Kashalls Maybe ask for someone's help if you cant figure it out on your own. I'm sure someone would be happy to help you out. 😁

**Comment by Kashalls** [comment]
> Doesn't the dev do releases on github? If they do I have a github release grabber now.

As to my knowledge, they do releases for stable versions here: https://github.com/Frederikam/Lavalink/releases

TeamCity says that dev is pushed to github as well but I dont see where it is.

**Comment by parkervcp** [comment]
You generally want to stick to full releases anyways. Unless you are building java packages in your installer.

**Comment by Kashalls** [comment]
> You generally want to stick to full releases anyways. Unless you are building java packages in your installer.

Well, the reason for it currently is that stable releases are broken when it comes to Youtube. Youtube changed the way they do some things, and there is a dev jar that fixes this issue but it isnt ready for stable.

**Comment by Kashalls** [comment]
@parkervcp It will probably be better for the github releases. I'll make two copies that downloads the stable lavalink and an egg for dev lavalink. 

Persons using Lavalink usually know what to do if they want to use it as a server anyways.

**Comment by Kashalls** [comment]
Unless we want to figure out how to use their provided docker images: https://hub.docker.com/r/fredboat/lavalink/

**Comment by ZandercraftGames** [comment]
Still working on this Kash?

**Comment by Kashalls** [comment]
Not at this time. It's still not stable right now. The config works with the jar correctly but my local install script breaks every time they update the jar.

**Comment by parkervcp** [comment]
@Kashalls Are you still working on this? Can you please rebase on the latest master as well?

**Comment by Kashalls** [comment]
Haven't had the time lately to work on anything to be honest. Working
during corona takes your time out of other stuff in retail. I'll be able to
do it once work dies down but right now I don't have the time.

**Pull request closed without merging**
