### PR TITLE
Update Curse Readme to match egg referenced modpack

### PR DESCRIPTION
**Pull request by tmunsch**
[x] Have you followed the guidelines in our Contributing document?
[x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Update readme to match egg description for curseforge pack.

### CODE REVIEW

**Comment by parkervcp** [comment]
@tmunsch please fill out the template.

**Comment by tmunsch** [comment]
It's so weird, I swear it did it, but I did it from my phone. So who knows.

**Comment by tmunsch** [comment]
@parkervcp Fixed, although it's not liking my x's for some reason.

**Comment by tmunsch** [comment]
Redoing this, can't get it to format anymore

**Pull request closed without merging**
