### PR TITLE
Add Fabric Egg

### LINKED ISSUE #706: Game Request: Minecraft Fabric
Service: Minecraft Fabric

Does this expand an already existing service: Y

Link to game: [https://fabricmc.net/](https://fabricmc.net/)

Links for server downloads: 
https://fabricmc.net/use/?page=server
https://www.curseforge.com/minecraft/mc-mods/fabric-api (optional but needed for most mods)

Links for install steps/docs: 
https://fabricmc.net/use/?page=server
https://fabricmc.net/wiki/doku.php

### PR DESCRIPTION
**Pull request by tmunsch**
resolves #706 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  If not, why?: I'm don't know what i'm doing

New Server Submission:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Have you added the server to the main README.md?
3. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by tmunsch** [comment]
Anything I need to add or change Parker?

**Comment by TekExplorer** [comment]
minor thing, but something I just realized, is that those boxes are actually task lists. you can put an x in them like: `[x]` to mark it as checked or just leave them as `[]` and check them by clicking on it

- [ ] unchecked list
- [x] checked list

minor learning moment :D

**Comment by parkervcp** [comment]
@tmunsch Is there a better way to get versions? being able to set the version to "latest" is the best option.

**Comment by parkervcp** [comment]
Looking at the maven site this is a dirty workaround 

`curl https://maven.fabricmc.net/net/fabricmc/fabric-installer/ | grep -Po '(?<=href=")[^"]*/' | sort -h | tail -1`

**Comment by tmunsch** [comment]
I just started working on that last night Thanks Parker

**Comment by tmunsch** [comment]
I think it's good now, please test and let me know

**Pull request merged**
