### PR TITLE
Adding ?MaxPlayers variable to config and startup command

### PR DESCRIPTION
**Pull request by Ballaual**
This PR is updating the ARK: Survival Evolved egg by adding ?MaxPlayers variable to config and startup command.

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You are not allowed to change the author mail

**Comment by Ballaual** [comment]
> You are not allowed to change the author mail

Reverted author changes with https://github.com/parkervcp/eggs/pull/2360/commits/72783f3d2fb305d906841a0b27e15a90a68ff65e

**Comment by parkervcp** [comment]
I am not a fan of adding max player variables unless they are strictly necessary.

**Comment by Ballaual** [comment]
> I am not a fan of adding max player variables unless they are strictly necessary.

afaik there is currently no other viable option to set the player limit outside the start command.

**Comment by Ballaual** [comment]
I am already using this version in my installation for own use and it works fine. If not wished here, pr can be closed.

**Comment by gOOvER** [comment]
the problem is, thats its hard to set max players on an ARK Server, so it would be nice, when this could be merged

**Comment by QuintenQVD0** [comment]
Please set a defaulr ammount in the variable that is defaulr by the game. Then it is fine as indeed this is not directly posible in the config files.

**Comment by parkervcp** [comment]
The variable should be set to the default and also not be nullable.

**Comment by Ballaual** [comment]
changes done

**Comment by QuintenQVD0** [comment]
you can not make directly changes in the .json file , do it in a panel and then export and fully replace the file here.

**Comment by QuintenQVD0** [comment]
now the diff is bad, wy did you not just replace the contents of the file instad of deleting it and re-uploading it?

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by 90baoet** [comment]
> This PR is updating the ARK: Survival Evolved egg by adding ?MaxPlayers variable to config and startup command.

**Pull request merged**
