### PR TITLE
feat: add steam_disk_space egg feature to SteamCMD eggs

### PR DESCRIPTION
**Pull request by Software-Noob**
A new egg feature modal was introduced in Panel v1.7.0 triggering when a server has run out of disk space to provide more user-friendly instructions to both admins and normal users. This is unique to SteamCMD specific errors.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by lilkingjr1** [comment]
Neat! Any chance the PR or commit with these panel changes could be linked so I can view how it behaves under the hood to ensure it does not conflict with anything? (ie. the Arma 3 egg/image update I'm working on)

**Comment by Software-Noob** [comment]
> Neat! Any chance the PR or commit with these panel changes could be linked so I can view how it behaves under the hood to ensure it does not conflict with anything? (ie. the Arma 3 egg/image update I'm working on)

Egg features look for specific strings in the console while the server is in starting state and trigger the modal once they're detected.

https://github.com/pterodactyl/panel/commit/0ff2f28cede94b2084c849dec82be6b826f9c187

**Comment by gOOvER** [comment]
In my eye's this is useless. When you import such an egg and export it again, these features are removed. As long as Ptero don't support this features on egg export, it should not be merged

**Review by parkervcp — APPROVED** [review]
LGTM

**Pull request merged**
