### PR TITLE
Enshrouded/updated readme and add workaround for Serverlist

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

* added my Kofilink
* added workaround for server not showing in Serverlist

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@gOOvER you may want to add the table with the port requirements. And that query must be game+1

**Comment by Northwave** [comment]
whx must the query port +1 to game port ? I run this without them being neighbors

**Comment by QuintenQVD0** [comment]
> why must the query port +1 to game port ? I run this without them being neighbors

I saw that mentioned in there discord. I can be wrong. You at least need 2 ports

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
