### PR TITLE
Update egg-unturned.json

### PR DESCRIPTION
**Pull request by MatrixSystemPVP**
# Description

Moved "force_install_dir" before login, because of the Warning by SteamCMD.
Warning message by SteamCMD: "Please use force_install_dir before logon!"

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Your changes must be done in the panel and then fully replaced here. Also just update to our steamcmd install script.

**Comment by MatrixSystemPVP** [comment]
Alright, I've exported it from the panel.
Where do I find the steamcmd install Script, you're referring to?

**Comment by MatrixSystemPVP** [comment]
Found the Script.
"force_install_dir" is already before logon in there.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
