### PR TITLE
Fix Impostor Server URLs

### PR DESCRIPTION
**Pull request by JohnB17**
### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: 
It seemed easier.

### Changes to an existing Egg:

1. [X] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [X] Have you tested your Egg changes?

The download URLs changed, this pull request fixes them.

### CODE REVIEW

**Comment by Software-Noob** [comment]
The install container runs as root making the chmod for tar files which are removed at the end unnecessary. Is there a particular reason to change the whole install script when it only requires updating the download link to `Impostor-Server_${VERSION}_linux-x64.tar.gz`?

**Comment by gOOvER** [comment]
Impostor change the Links with every commit. It's hard to maintain Imposter. Talk with the dev, to host all on github and not 1.000.000 different plsces

**Comment by Software-Noob** [comment]
> Impostor change the Links with every commit. It's hard to maintain Imposter. Talk with the dev, to host all on github and not 1.000.000 different places

It has been the same format since October 2020 release. Only the two original releases had a different format. All this would require is to use `Impostor-Server_${VERSION}_linux-x64.tar.gz` for the version

**Comment by Software-Noob** [comment]
Thank you for your contribution. This was superseded by #1262

**Pull request closed without merging**
