### PR TITLE
Update the egg to run dynamica-v2

### LINKED ISSUE #2430: [Bug]: Discord Dynamica
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

bots/discord/dynamica

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Removed the limit of 18 characters for the bot client ID, as discord now has above 18 characters for client IDs.

`|size:18` is what was removed

### Actual Behavior

Server doesn't start up. Heres the error

```
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:42339ed43474d121a107bfb856db9fb466dfffff681aca4b53e02fe2f12b6700 
Status: Image is up to date for ghcr.io/parkervcp/yolks:nodejs_16 
[Pterodactyl Daemon]: Finished pulling Docker container image
v16.20.2
:/home/container$ yarn deploy && yarn prisma migrate deploy && yarn start
yarn run v1.22.19
$ echo "This script is no longer used. All you need to do is run yarn start and deployment happens automatically."
This script is no longer used. All you need to do is run yarn start and deployment happens automatically.
Done in 0.13s.
yarn run v1.22.19
$ /home/container/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:/home/container/dynamica/db.sqlite"
14 migrations found in prisma/migrations
No pending migrations to apply.
Done in 5.34s.
yarn run v1.22.19
$ node --enable-source-maps .
node:internal/modules/cjs/loader:435
      throw err;
      ^
Error: Cannot find module '/home/container/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:427:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:640:18)
    at resolveMainPath (node:internal/modules/run_main:19:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:75:24)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/container/package.json',
  requestPath: '/home/container'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Steps To Reproduce

Change the variable for CLIENT_ID under rules to only have the following:

Old: `"rules": "required|string|size:18"`
New: `"rules": "required|string"`

Create a new server
Enter a bot token and client id into the variables
Leave everything else default
Start server installation process
Boot server up
Error

### Install logs

https://pteropaste.com/eqvwzswsjdjc

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
# Description
Updated the egg to run a newer version of the bot because original repository was archived. 

closes #2430 
## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@diedyesterdaywashere Have you tryed it as it does not work for me

**Comment by diedyesterdaywashere** [comment]
> @diedyesterdaywashere Have you tryed it as it does not work for me

Yeah I did, and it worked fine

**Comment by QuintenQVD0** [comment]
> > @diedyesterdaywashere Have you tryed it as it does not work for me
> 
> Yeah I did, and it worked fine

it did not start for me. and there docker file is nodejs 18 required so I am supprised if it would even start

**Comment by gOOvER** [comment]
When invent the wheel twice, when they have allready an egg for the bot?

**Comment by QuintenQVD0** [comment]
> When invent the wheel twice, when they have allready an egg for the bot?

there bot files are in the docker image...

**Comment by gOOvER** [comment]
> > When invent the wheel twice, when they have allready an egg for the bot?
> 
> there bot files are in the docker image...

ahh ok; didnt checked that

**Comment by QuintenQVD0** [comment]
Yea I forgot the a in the commit name.

Now we use the proper script and the needed files are now generated to actually make this bot work for v2. I have it running with this egg.

afbeelding

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
