### PR TITLE
Update/sogeBot - Cleanup Installscript and added missing link to readme

### PR DESCRIPTION
**Pull request by gOOvER**
- cleanup installscript
- added missing Link to readme

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
I just want to call out the script for grabbing software from git, downloading files, unpacking packaged files

https://github.com/parkervcp/eggs/blob/master/scripts/github_release_grabber.sh

https://github.com/parkervcp/eggs/blob/master/scripts/download_link_validator.sh

https://github.com/parkervcp/eggs/blob/master/scripts/file_unpacker.sh

**Comment by gOOvER** [comment]
Ok, i used your script, but i have i problem. I think this caused by the Version of the file:

`https://github.com/sogehige/sogeBot/releases/download/11.12.3/sogeBot-11.12.3.zip
unknown filetype. Exeting`

Maybe you can give me a tip to handle this

**Comment by parkervcp** [comment]
You need to install `file` as well. Add it after the `wget` you have in the `apt install` line

**Comment by gOOvER** [comment]
File will be installed.

apt install -y curl unzip sqlite jq wget file

i think, it's the filename sogeBot-11.12.3.zip

**Comment by gOOvER** [comment]
The submitted Egg works. MB you can merge it

**Pull request merged**
