### PR TITLE
ARK egg for vanilla or moded server

### PR DESCRIPTION
**Pull request by SheppeR**

### CODE REVIEW

**Comment by parkervcp** [comment]
@SheppeR Can you manually update the email as the pterodactyl team did not build this modified version of the egg.

**Comment by SheppeR** [comment]
Sure, what email do you want ? mine ?

**Comment by toddferg** [comment]
Out of curiousity how would you use mods in this?

**Comment by Budman17r** [comment]
So how would one use mods on this egg?
Modify the game.ini?

**Comment by SheppeR** [comment]
You can install mods by editing 2 files ( Game.ini and GameUserSettings.ini)

Adding id to Game.ini is for install mods from workshop and GameUserSettings is for active mods on server.

_Game.ini_
[ModInstaller]
ModIDS=123456789
ModIDS=987654321

_GameUserSettings.ini_
[ServerSettings]
ActiveMods=123456789,987654321

**Pull request merged**
