### PR TITLE
Update multitheftauto

### PR DESCRIPTION
**Pull request by QuintenQVD0**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- The current egg was not working with the `tar -xzvf` what I changed to `tar -xvf`
- I updated the server image to a newer image
2. [x] Have you tested your Egg changes?
yes

### CODE REVIEW

**Comment by parkervcp** [comment]
@QuintenQVD0 Does MTA even support ARM themselves?

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Does MTA even support ARM themselves?

It is in a dev state but there working on it
https://linux.mtasa.com/
afbeelding

but do net yet merge this I will remove for now the arm64 function until it is out of experimental. Let me do 1 commit to remove the arm64 function but then this PR will just be to fix the server installing

**Comment by QuintenQVD0** [comment]
@parkervcp It should be ready now.

**Review by Software-Noob — APPROVED** [review]
LGTM. Thank you for contributing :+1:

Weird for them to change the format after so many years. We might want to look into adding a check to detect the archive type.

**Pull request merged**
