### PR TITLE
Add Lavalink Egg and Voice Servers Category

### PR DESCRIPTION
**Pull request by DanPlayz0**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: 

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

It installs the necessary configuration files and dependencies to run the lava link server.

### CODE REVIEW

**Comment by gOOvER** [comment]
You missed add it to Main Readme

**Comment by DanPlayz0** [comment]
Just added it to the Main Readme

**Comment by parkervcp** [comment]
While you at adding a voice_servers section to the main README add teespeak in there too.

**Comment by parkervcp** [comment]
Also if all you are doing is running a curl command you could just use debian:buster-slim instead of the nodejs image for install

**Comment by DanPlayz0** [comment]
Added teaspeak to the main README and changed the install script's container

**Comment by parkervcp** [comment]
@DanPlayz0 You don't need git or openjdk in the install script if you aren't using them.

**Comment by DanPlayz0** [comment]
Well, I removed the JDK, JRE, and Git from the install script. I also added application.yml to the configuration files area of the egg.

**Pull request merged**
