### PR TITLE
Add a option to uninstall node modules with the discord.js egg

### PR DESCRIPTION
**Pull request by ducksquaddd**
This pr adds a feature that allows users to uninstall node modules rather than doing it manually.

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
You could of course just delete the folder for that package.

**Comment by ducksquaddd** [comment]
> 
> 
> You could of course just delete the folder for that package.

When installing packages doesn't also add other packages, so wouldnt this be easier rather than cleaning all the node modules yourself

**Review by docimin — CHANGES_REQUESTED** [review]
Hey, you cannot have both uninstall and install node packages with the env_variable "NODE_PACKAGES", please change env_variable to UNNODE_PACKAGES instead, as you put that variable in the startup command.

**Comment by parkervcp** [comment]
#1253 added this at my request.

**Comment by ducksquaddd** [comment]
> 
> 
> Hey, you cannot have both uninstall and install node packages with the env_variable "NODE_PACKAGES", please change env_variable to UNNODE_PACKAGES instead, as you put that variable in the startup command.

Thanks for pointing that out lol, I changing some stuff around because i the current egg i use is changed up alot and didnt want to give that one here.

**Pull request closed without merging**
