### PR TITLE
Update egg vanila-valheim

### PR DESCRIPTION
**Pull request by masterworgen**
# Description
Update egg valheim vanila, the current egg is not working

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by masterworgen** [comment]
Proof that the current state is not working
image

**Comment by danny6167** [comment]
The current egg imports just fine. What version of the panel are you running?

**Comment by danny6167** [comment]
I can see from the egg you have exported that it was exported from an outdated version of the panel.

**Comment by danny6167** [comment]
> > The current egg imports just fine. What version of the panel are you running?
> 
> 1.7.0

That is MANY months out of date. Please upgrade.
Your report/PR is invalid.

**Comment by masterworgen** [comment]
Ok

**Pull request closed without merging**
