### PR TITLE
Satisfactory: Added ASC

### PR DESCRIPTION
**Pull request by LegacyAngel2K9**
Added Additional Startup Commands variable to allow for custom startup commands such as -DisableSeasonalEvents

### All Submissions:

* [Yes] Have you followed the guidelines in our Contributing document?
* [Yes] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [Yes] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [Yes] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [Yes] Have you tested your Egg changes?

### CODE REVIEW

**Comment by LegacyAngel2K9** [comment]
I used this flag all season and it worked like a charm for me

> `-DisableSeasonalEvents` is not a valid startup flag [according to their Wiki](https://satisfactory.fandom.com/wiki/Dedicated_servers#Command_line_options), nor can I find it referenced anywhere else. `FG.DisableSeasonalEvents x` on the other hand, is a valid console command you can type into the client console via the Server Manager as an admin (which unfortunately is hard to test right now because the seasonal event is over).
> 
> 
> 
> The egg already covers all currently known startup flags for the server, and this PR adds an unnecessary wildcard variable at the end of the startup command that could potentially allow a bad end-user to perform additional shell scripting if the server were to crash.
> 
> 
> 
> Lastly, in terms of cosmetics, it also seems to reorganize the order of Pterodactyl startup variables by putting experimental and advanced settings at the top of the list, which is not ideal in my opinion.

**Comment by lilkingjr1** [comment]
> I used this flag all season and it worked like a charm for me

Interesting... Well that's good news, because I personally had an issue using the command line command myself, but just assumed I did it wrong because I did it in a hurry. Maybe we can find a way to have a boolean variable that dynamically adds the specific flag or not based on it's value. I'll submit a PR to your fork if you want.

**Comment by LegacyAngel2K9** [comment]
Yeah, sure thing ☺️

**Comment by lilkingjr1** [comment]
> Yeah, sure thing ☺️

Submitted a PR to your fork. Discuss there if you have any feedback.

**Comment by lilkingjr1** [comment]
Due to apparent abandonment, I recommend this PR be closed if #1622 gets merged.

**Pull request closed without merging**
