### PR TITLE
Fixes BeamMP server not shutting down

### PR DESCRIPTION
**Pull request by skittles-fivem**
# Description

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]
You cleary did not read the questions you where asked when you made this pr. All changes must be made in a panel and then exported. Do not ever edit the .json file directly

**Comment by skittles-fivem** [comment]
> 

that one was on me i edited the egg from the org then imported to test it then grabbed the wrong one to upload will fix in a sec

**Comment by QuintenQVD0** [comment]
Wy did you rename it to servers and not server as it was? As it only hosts 1 server of beanmp per server

**Comment by skittles-fivem** [comment]
> Wy did you rename it to servers and not server as it was? As it only hosts 1 server of beanmp per server

To put it back to the original name from the master branch

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you

**Pull request merged**
