### PR TITLE
[Satisfactory] Removed -multihome flag, no longer required as of patch 0.5.0.7.

### PR DESCRIPTION
**Pull request by Maelstromeous**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
  * 
### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by Software-Noob** [comment]
It doesn't hurt to keep this ensuring no such breaking occurs again. Similar to how we specify 0.0.0.0 IP in games or applications that support it

**Comment by Maelstromeous** [comment]
@Software-Noob it was always intended as a temporary fix to put  the flag in. Also in its current form IPV6 connectivity does not work.

**Comment by gOOvER** [comment]
> @Software-Noob it was always intended as a temporary fix to put the flag in. Also in its current form IPV6 connectivity does not work.

No, it was not only for Quickfix. This is an official flag for the server and should stay where it is

**Comment by Maelstromeous** [comment]
> > @Software-Noob it was always intended as a temporary fix to put the flag in. Also in its current form IPV6 connectivity does not work.
> 
> No, it was not only for Quickfix. This is an official flag for the server and should stay where it is. You can add also an IPv6 Ip to -multihome

What's the full param? `-multihome=::`?

**Comment by Software-Noob** [comment]
> > > @Software-Noob it was always intended as a temporary fix to put the flag in. Also in its current form IPV6 connectivity does not work.
> > 
> > 
> > No, it was not only for Quickfix. This is an official flag for the server and should stay where it is. You can add also an IPv6 Ip to -multihome
> 
> What's the full param? `-multihome=::`?

That would enable IPV6. From what I've read, leaving this in the startup args doesn't affect anything negatively, and I would rather keep this, for now, similar to how other eggs force 0.0.0.0 to prevent this kind of server breaking. Feel free to open a new PR or issue should the Satisfactory server make new breaking changes.

**Pull request closed without merging**
