### PR TITLE
Add Longvinter

### LINKED ISSUE #1579: [Egg Request]: Long-vinter
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1635450/Longvinter/

### Links for the download

https://github.com/Uuvana-Studios/longvinter-linux-server

### Links for the install docs

https://docs-server.longvinter.com/

### PR DESCRIPTION
**Pull request by TuEye**
* Added Longvinter egg
* Readme modified accordingly
* Closes #1579 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by parkervcp** [comment]
@TuEye Please resolve the readme conflicts

**Comment by TuEye** [comment]
> @TuEye Please resolve the readme conflicts

Done

**Comment by MADDMAXKZ** [comment]
is this working when i try to connect to my server it just crashes and puts me back in main menu or goes into a inf loading

**Comment by tomlahaye** [comment]
Hi, a date for this egg ?

**Comment by TuEye** [comment]
> is this working when i try to connect to my server it just crashes and puts me back in main menu or goes into a inf loading

@MADDMAXKZ I just tested the egg on two different hosts and could not reproduce this problem. The only way I could get the same results as you described, is when I block the network ports of the game server. So I would guess you had Network issues when trying this egg. Could you check this?

**Comment by fmolliet** [comment]
@TuEye I will testing here.
If this problem happens, I'll let you know.

**Comment by fmolliet** [comment]
I got this error while running the server after install but works fine.
image
Evidence: 
image

Observations: 
The start configuration is not work properly, so the status is keeping in starting...
image

**Comment by fmolliet** [comment]
If this can help, the startup log.
[startupLogs.txt](https://github.com/parkervcp/eggs/files/9059731/startupLogs.txt)

**Comment by fmolliet** [comment]
image
I think is an kind of bug in longvinter server.
I will lookup at the REPO
https://github.com/Uuvana-Studios/longvinter-linux-server

**Comment by fmolliet** [comment]
I created an Issue:
https://github.com/Uuvana-Studios/longvinter-linux-server/issues/48

**Comment by parkervcp** [comment]
@TuEye 

If you use the debian installer image you don't need to add git, curl.

As for sed you don't need it as wings will manage config files. I still recommend copying over the config during install.

On line 45 you run a `git clone` on the longvinter server repo
You want to use `git clone "https://github.com/Uuvana-Studios/longvinter-linux-server.git" .` so it pulls the files into the folder directly and not into a sub-folder. This also gets rid of the `cd` line 48

**Comment by QuintenQVD0** [comment]
To be honnest, if someone can confirm that it is still working then this can be merged.

**Comment by ImKringle** [comment]
> To be honnest, if someone can confirm that it is still working then this can be merged.

Tested and confirmed working 👍🏼 
image

**Comment by gOOvER** [comment]
> > To be honnest, if someone can confirm that it is still working then this can be merged.
> 
> Tested and confirmed working 👍🏼 image

With default ports or with other ports too? Last time i tested this, it didnt work with other than defaultports

**Comment by ImKringle** [comment]
> > > To be honnest, if someone can confirm that it is still working then this can be merged.
> > 
> > 
> > Tested and confirmed working 👍🏼 image
> 
> With default ports or with other ports too? Last time i tested this, it didnt work with other than defaultports

I used port 25570; so definitely not default lol

**Comment by gOOvER** [comment]
> > > > To be honnest, if someone can confirm that it is still working then this can be merged.
> > > 
> > > 
> > > Tested and confirmed working 👍🏼 
> > 
> > With default ports or with other ports too? Last time i tested this, it didnt work with other than defaultports
> 
> I used port 25570; so definitely not default lol

Noone see this on your screenshot, which is saying nothing ;) A consoleoutput would be better

**Comment by ImKringle** [comment]
> > > > > To be honnest, if someone can confirm that it is still working then this can be merged.
> > > > 
> > > > 
> > > > Tested and confirmed working 👍🏼
> > > 
> > > 
> > > With default ports or with other ports too? Last time i tested this, it didnt work with other than defaultports
> > 
> > 
> > I used port 25570; so definitely not default lol
> 
> Noone see your port at your screenshot, which is saying nothing ;) A consoleoutput would be better

You mean the console output *you know* doesnt show the port you assign to it? xD 

But yeah, sure here you go:
Logs showing a random ass 7000 port while assigned 25570:
https://pastebin.com/d5RTEBvJ

A literal clip of me using 25570 to connect to it:
https://github.com/parkervcp/eggs/assets/135805091/4d9784fd-ab52-413a-96b7-b661718fad2f

Query port was left at default 27015, port to connect can be literally whatever you want 🤷🏼 Try it yaself

**Comment by gOOvER** [comment]
> > > > > > To be honnest, if someone can confirm that it is still working then this can be merged.
> > > > > 
> > > > > 
> > > > > Tested and confirmed working 👍🏼
> > > > 
> > > > 
> > > > With default ports or with other ports too? Last time i tested this, it didnt work with other than defaultports
> > > 
> > > 
> > > I used port 25570; so definitely not default lol
> > 
> > 
> > Noone see your port at your screenshot, which is saying nothing ;) A consoleoutput would be better
> 
> You mean the console output _you know_ doesnt show the port you assign to it? xD
> 
> But yeah, sure here you go: Logs showing a random ass 7000 port while assigned 25570: https://pastebin.com/d5RTEBvJ `[2023.12.28-07.41.13:652][ 34]LogNet: Created socket for bind address: 0.0.0.0 on port 7787`
> 
> A literal clip of me using 25570 to connect to it: https://github.com/parkervcp/eggs/assets/135805091/4d9784fd-ab52-413a-96b7-b661718fad2f
> 
> Query port was left at default 27015, port to connect can be literally whatever you want 🤷🏼 Try it yaself

please try an other QueryPort too. That was my problem

**Comment by gOOvER** [comment]
> The server indeed seems to have some port issues
> 
> port allocate is 25568-25569 with 25568 primary
> 
> all from the same log file: `[2023.12.28-07.59.25:856][ 0]LogNet: Created socket for bind address: 0.0.0.0 on port 25568` `[2023.12.28-07.59.31:103][ 31]LogEOS: Verbose: [LogEOSP2P] Using Port Range 7777-7876 for P2P traffic` `[2023.12.28-07.59.31:778][ 51]LogNet: Created socket for bind address: 0.0.0.0 on port 7787` `[2023.12.28-07.59.31:778][ 51]LogNet: EOSNetDriver_2147288141 EOSNetDriver_2147288141 IpNetDriver listening on port 7787`

that was the error i also get. QueryPort dont work correct

**Comment by ImKringle** [comment]
Main Port: 25570
Query Port: 25571
image

Logs: https://mclo.gs/L4VbdfM (Pastebin got unhappy with whatevers in this); again it works xD

Allocated ports:
25570-25574

Its really just the game not showing it allocating right, it works fine regardless of the error lol Connected, tested and confirmed 🤷🏼

**Comment by ImKringle** [comment]
> > The server indeed seems to have some port issues
> > port allocate is 25568-25569 with 25568 primary
> > all from the same log file: `[2023.12.28-07.59.25:856][ 0]LogNet: Created socket for bind address: 0.0.0.0 on port 25568` `[2023.12.28-07.59.31:103][ 31]LogEOS: Verbose: [LogEOSP2P] Using Port Range 7777-7876 for P2P traffic` `[2023.12.28-07.59.31:778][ 51]LogNet: Created socket for bind address: 0.0.0.0 on port 7787` `[2023.12.28-07.59.31:778][ 51]LogNet: EOSNetDriver_2147288141 EOSNetDriver_2147288141 IpNetDriver listening on port 7787`
> 
> that was the error i also get. QueryPort dont work correct

Also unless im misunderstanding, why are you trying to connect with the Query Port? For this you connect with the main allocation, not the query port lol

**Comment by parkervcp** [comment]
@ImKringle This is working for you?

**Comment by ImKringle** [comment]
> @ImKringle This is working for you?

Yeup, tried base ports and not-default ports. Both worked just fine

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
