### PR TITLE
feat(postgres): v16 egg

### LINKED ISSUE #2562: [Egg Request]: PostgreSQL 16
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.postgresql.org/

### Links for the download

https://www.postgresql.org/download/

### Links for the install docs

https://www.postgresql.org/docs/current/tutorial-install.html

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**
# Description

Adds a new egg for Postgres 16. It was added as a separate egg due to one egg not working with multiple versions since the install script uses a specific version of Postgres.

It uses the new Postgres 16 yolk added in parkervcp/yolks#210.
Closes #2562.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your egg use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [x] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Password defaultq must be empty!, could this not just be added to the existing postgres egg?

**Comment by WilliamDavidHarrison** [comment]
> Password defaultq must be empty!

On the v14 egg it is the same, I can change it however.

> could this not just be added to the existing postgres egg?

I tried to do this however since the install script (on the v14 egg) uses `postgres:14-alpine` when trying to use the v16 Docker image, it will cause the following error: `The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 16.1.` Therefore, the v16 version needs to be seperate and use the `postgres:16-alpine` install script image for it to install correctly.

**Comment by QuintenQVD0** [comment]
> > Password defaultq must be empty!
> 
> On the v14 egg it is the same, I can change it however.
> 
> > could this not just be added to the existing postgres egg?
> 
> I tried to do this however since the install script (on the v14 egg) uses `postgres:14-alpine` when trying to use the v16 Docker image, it will cause the following error: `The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 16.1.` Therefore, the v16 version needs to be seperate and use the `postgres:16-alpine` install script image for it to install correctly.

Normaly it is not allowed but for postgres it is needed so fine.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thanks

**Pull request merged**
