### PR TITLE
Steam Swords 'n Magic and Stuff 

### LINKED ISSUE #2222: [Egg Request]: Swords 'n Magic and Stuff
### Does this expand an already existing service

No

### Link to a game or software

https://www.playswordsandmagic.com/

### Links for the download

https://steamdb.info/app/2058450/

### Links for the install docs

https://discord.com/channels/398282199788552193/1022758416923504680

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

add Swords 'n Magic and Stuff  with a wrapper to have some console logs until there next update is merged

I did not test to connect as I do not own the game.

closes #2222 
## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by mikeseese** [comment]
I'm a little confused on how I can test this. I have installed Pterodactyl using https://github.com/pterodactyl/panel/blob/develop/docker-compose.example.yml, created a user, created the nest, egg (via import of the JSON), location, allocation, node, and finally the server (I love the fact there's options for so much control, but it sure felt like a convoluted setup process), but I'm not sure how/where this stuff is installing and where (the server is just showing "Installing" with nothing happening)? The docker-compose file doesn't seem to have anything related to enabling the container to create new containers.

Is there a more straight forward way for getting a development environment?

**Comment by mikeseese** [comment]
Also, I see you're still using a custom c wrapper for the logs, but per https://github.com/parkervcp/eggs/issues/2222#issuecomment-1520899582, I was able to get stdout working. Can you make the changes necessary to use stdout instead? That might make the testing easier

**Comment by QuintenQVD0** [comment]
> Also, I see you're still using a custom c wrapper for the logs, but per [#2222 (comment)](https://github.com/parkervcp/eggs/issues/2222#issuecomment-1520899582), I was able to get stdout working. Can you make the changes necessary to use stdout instead? That might make the testing easier

The stdout wont work until they update there game

**Comment by mikeseese** [comment]
I'm the developer trying to test the egg with a development build that has those changes.

**Comment by QuintenQVD0** [comment]
`wine /home/container/SNM2020\/Binaries/Win64/SNMASServer-Win64-Shipping.exe -log -port={{SERVER_PORT}} -QueryPort={{QUERY_PORT}}`

Also check if the startup marker is running. So it looks for a specific string in the console to see if the server is started. It will print the message marked as starting. If it does not do then post a screen of an example starup in the console so I can change it to your needs. Then this egg can be merged if the update is out.

**Comment by QuintenQVD0** [comment]
@mikeseese Did it work?

**Comment by mikeseese** [comment]
I'm traveling so haven't had a chance to try it. I'll let you know when I get a chance.

**Comment by QuintenQVD0** [comment]
@mikeseese Did you had time to test?

**Comment by mikeseese** [comment]
Not yet, I got back from travel yesterday. I'll look at it this week.

**Comment by mikeseese** [comment]
@QuintenQVD0 I'm having issues just getting basic things set up. I just see an infinite loading spinner saying it's installing:
image

I don't have time to figure out what specific configuration pterodactyl needs, so can you test it instead? I've created a Steam branch that you can use (via `SRCDS_BETAID` and `SRCDS_BETAPASS` variables if you add them to your egg temporarily) to test logging without a wrapper on your end.

Branch name: `pterodactyl`
Branch password: `RAuvPUkEkvjzBVvRvaCt`

The goal here is to get that working and delay merging this PR (without the specific branch) until the next release.

**Comment by mikeseese** [comment]
Can you try adding `-log` argument to the command line?

**Comment by QuintenQVD0** [comment]
> Can you try adding `-log` argument to the command line?

now I get this:
```
vcrun2019 already installed, skipping
:/home/container$ wine /home/container/SNM2020/Binaries/Win64/SNMASServer-Win64-Shipping.exe -port=${SERVER_PORT} -QueryPort=${QUERY_PORT} -log
LogPakFile: Display: Found Pak file ../../../SNM2020/Content/Paks/SNM2020-Window
sServer.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../SNM2020/Content/Paks/SNM2020-Win
dowsServer.pak.
LogModuleManager: Warning: ModuleManager: Module 'D3D11RHI' not found - its Stat
icallyLinkedModuleInitializers function is null.
[2023.06.02-20.06.11:406][  0]LogMemory: Platform Memory Stats for WindowsServer
[2023.06.02-20.06.11:407][  0]LogMemory: Process Physical Memory: 156.53 MB used, 156.53 MB peak
[2023.06.02-20.06.11:407][  0]LogMemory: Process Virtual Memory: 132.38 MB used, 132.38 MB peak
[2023.06.02-20.06.11:408][  0]LogMemory: Physical Memory: 941.94 MB used,  3964.21 MB free, 4906.15 MB total
[2023.06.02-20.06.11:408][  0]LogMemory: Virtual Memory: 134212784.00 MB used,  4940.21 MB free, 134217728.00 MB total
[2023.06.02-20.06.12:133][  0]LogSnMDedicatedServer: Dedicated server started; initializing.
[2023.06.02-20.06.12:133][  0]LogSnMDedicatedServer: Version: 1.5.14.6
```

is this it or am I supposed to see more logs like in the log file?

**Comment by mikeseese** [comment]
Nice! I'd personally make the changes to this PR to support this future release and hold off on merging until then rather than use the intermediary effort of the wrapper. Ultimately it's up to yall how you want to proceed as this is just a third party integration, but I personally believe having one less thing to fail will ultimately reduce the amount of issues. I'm still not sure when the next release will be, but I'll be sure to update you when it does go out either way you choose to move forward

**Comment by vp-en** [comment]
Hey :)

So I wanted to try out this egg, since I recently bought the game. But it won't let me connect to the server.

Here's what I did:

**Using the wrapper based branch**
1) I went to [the branch](https://github.com/parkervcp/eggs/tree/steam_2058450/game_eggs/steamcmd_servers/swords_'n_Magic_and_Stuff) where the egg is available, and downloaded the `egg-swords-n-magic-and-stuff.json` file

2) I imported the egg

3) I changed the install script a bit, to let it download the wrapper thing properly from the right branch and fixed the `chmod +x` to point to the exact location of wrapper, since it otherwise gives a permission error
```bash
if [ ! -f /mnt/server/wrapper ]
then
    echo "The wrapper does not yet exists, download a new one"
    curl -sSL -o /mnt/server/wrapper "https://raw.githubusercontent.com/parkervcp/eggs/steam_2058450/game_eggs/steamcmd_servers/swords_'n_Magic_and_Stuff/wrapper"
    chmod +x /mnt/server/wrapper
else
    echo "wrapper found. skipping"
fi
```

4) Install the server, as you would normally through the Pterodactyl Panel and assign two ports. In my case it'll use the ports `35585` for the server and `35586` for the Steam Query port.

5) Let the server install. Full logs:
`https://paste.ec/paste/nV2C1+sV#YAND5+pbKuAEqN87WsXgKPmkpnlhLWPhDVniAw3rWI2`

6) It'll output, that it did it successfully:
```
:/home/container$ ./wrapper /usr/bin/wine /home/container/SNM2020/Binaries/Win64/SNMASServer-Win64-Shipping.exe -port=${SERVER_PORT} -QueryPort=${QUERY_PORT}
[2023-06-10T15:02:06.937Z] - Dedicated server started; initializing.
[2023-06-10T15:02:06.937Z] - Version: 1.5.13
[2023-06-10T15:02:11.205Z] - Setting reset timer for 32,269 seconds
[2023-06-10T15:02:11.205Z] - Next reset warning in 28669.0 seconds.
[2023-06-10T15:02:11.205Z] - World loaded; updating Steam.
[2023-06-10T15:02:11.206Z] - WARNING: Failed to get Steam session settings. Can be ignored if the server just started. If the server just underwent a reset, this should be considered an ERROR.
[2023-06-10T15:02:11.548Z] - No server name specified; choosing a random one.
[2023-06-10T15:02:11.548Z] - Creating Steam session with configuration:
  Name:  "Kitten Lava"
  Password: ""
  Steam Owner ID: "76561198050600779"
  Max players: 16
  Days until reset: 1
  Reset warnings in minutes: 60
[2023-06-10T15:02:11.551Z] - Succeeded to create Steam session with ID: 6B4EAA154EA7CEF934240399D7DBD765
container@pterodactyl~ Server marked as running...
```

But when trying to connect to the IP ingame `213.XXX.194.XX:35585`, will result in instantly seeing the loading screen very very shortly, and then this error appears:
`You were disconnected. There was an issue with the connection to the server`

Using the Steam Query port instead results in it loading for a long time and then the same error message appears.

I'm using Pterodactyl for eight other game servers and have no issues with them, so I'm figuring there must be something up with this particular egg, but I can't find any logs to show me any useful information other than the error message mentioned above.

**Using the -log based steam beta branch**
So I also tried the beta branch, mentioned in [this earlier comment](https://github.com/parkervcp/eggs/pull/2249#issuecomment-1573254371). 
That results in an error message, along the lines of "You can't connect to this server, since it's running on a different version". The logging does work though, when using the `-log` thing as mentioned.

I know this egg is still not merged, but I just wanted to mention it here.

**Comment by mikeseese** [comment]
@vp-en the `-log` based beta branch isn't meant for general consumption as it requires a compatible client build to use (which you have found out, doesn't exist yet); it was just meant as a way to get @QuintenQVD0 to test it. I'm disabling the `pterodactyl` Steam branch now.

**Comment by mikeseese** [comment]
As far as the wrapper based version, the variables that Pterodactyl are injected as Environment variables which take precedence over the config file. If the environment variable exists then the corresponding config file variable is ignored, which is why you're not seeing any difference if the Game.ini has the correct values. Since you are using environment variables, I would recommend not using the Game.ini at all to prevent confusion on what your config actually is.

As far as the error `You were disconnected. There was an issue with the connection to the server`, I'm not really sure what the issue could be. Make sure port 35585 is forwarded on your router.

**Comment by QuintenQVD0** [comment]
> As far as the wrapper based version, the variables that Pterodactyl are injected as Environment variables which take precedence over the config file. If the environment variable exists then the corresponding config file variable is ignored, which is why you're not seeing any difference if the Game.ini has the correct values. Since you are using environment variables, I would recommend not using the Game.ini at all to prevent confusion on what your config actually is.
> 
> As far as the error `You were disconnected. There was an issue with the connection to the server`, I'm not really sure what the issue could be. Make sure port 35585 is forwarded on your router and allowed on your Linux firewall, as it seems like the server never saw the incoming player (there is typically a message saying a player is trying to join). You probably have to forward the QueryPort too if you want to see your game listed in the session browser.

to be certain look in the log file becuase if the  wrapper fails for some reason then those lines will not be printed to the console

**Comment by QuintenQVD0** [comment]
for the ports, this is the startup

` /usr/bin/wine /home/container/SNM2020/Binaries/Win64/SNMASServer-Win64-Shipping.exe -port={{SERVER_PORT}} -QueryPort={{QUERY_PORT}}` and the {{SERVER_PORT}} is auto pulled from the primary allocation and {{QUERY_PORT}} is pulled from the variable under start startup tab what also should be a aditional allocation

**Comment by vp-en** [comment]
Thanks to the both of you, for your quick replies.

The server I'm using is a dedicated server rented on Hetzner. I have no firewall setup. It's basically just setup with UPnP. So every port allocated through Pterodactyl is automatically opened. I have a ton of other web based services running on the server, all accessible with no need for any forwarding or firewall setup.

I also got a bunch of [other game servers](https://i.imgur.com/Nav9Owh.png), which I can connect to through the allocated ports. It's just this egg that doesn't work for me :|

I've tried reinstalling the Swords 'n Magic egg several times. I also tried changing server names, tried with or without a password, but it still won't connect. There must be somet

**Comment by QuintenQVD0** [comment]
> Thanks to the both of you, for your quick replies.
> 
> The server I'm using is a dedicated server rented on Hetzner. I have no firewall setup. It's basically just setup with UPnP. So every port allocated through Pterodactyl is automatically opened. I have a ton of other web based services running on the server, all accessible with no need for any forwarding or firewall setup.
> 
> I also got a bunch of [other game servers](https://i.imgur.com/Nav9Owh.png), which I can connect to through the allocated ports. It's just this egg that doesn't work for me :|
> 
> I've tried reinstalling the Swords 'n Magic egg several times. I also tried changing server names, tried with or without a password, but it still won't connect.
> 
> There must be something happening, since it instantly loads when using the allocated primary port `35585` and then gives an error. When using a different port, like the Steam query port `35586` the loading just times out after 20 seconds or so.
> 
> If I can get your Steam ID or something @QuintenQVD0, I can gift you the game and you can test it out on your end? :). You can also just add me, [this is my steam info](https://steamid.io/lookup/76561198050600779).

I never gave a penny to steam so I can not recieve gifts exept steam gift codes. but I don't need the game and don't have time rn. I have exames so I will be free at the end of the month. 

You can always try to remove the -port and query port from the start, manual change it in the config and see if it works that way

**Comment by mikeseese** [comment]
Just wanted to clarify the reason I just disabled the Steam branch for the -log was merely because it won't work with a client until we actually release the next update. We're still planning to support this in the next build; I just didn't want others to think it's a functional server build.

**Comment by vp-en** [comment]
> You can always try to remove the -port and query port from the start, manual change it in the config and see if it works that way.
Sadly, same result :(

> Did you see anything in the log file?
Nope, nothing other than:
```
[2023-06-10T16:14:19.536Z] - Dedicated server started; initializing.
[2023-06-10T16:14:19.536Z] - Version: 1.5.13
[2023-06-10T16:14:23.384Z] - Setting reset timer for 44,137 seconds
[2023-06-10T16:14:23.384Z] - Next reset warning in 40537.0 seconds.
[2023-06-10T16:14:23.385Z] - World loaded; updating Steam.
[2023-06-10T16:14:23.385Z] - WARNING: Failed to get Steam session settings. Can be ignored if the server just started. If the server just underwent a reset, this should be considered an ERROR.
[2023-06-10T16:14:23.756Z] - Creating Steam session with configuration:
  Name:  "Night Scythe Cult Server"
  Password: "xxxxxx"
  Steam Owner ID: "765XXXXXXXXX00779"
  Max players: 16
  Days until reset: 1
  Reset warnings in minutes: 60
[2023-06-10T16:14:23.758Z] - Succeeded to create Steam session with ID: 9D4DC9134A354E191C1D6AA6B81AC5E6
```

**Comment by QuintenQVD0** [comment]
@mikeseese is there a way to change the bind ip as it may binded to 127.0.0.1

**Comment by mikeseese** [comment]
I can't find any documentation on how to specify the interface to bind to; it appears it binds to 0.0.0.0 by default. You should be able to verify this using netstat

**Comment by QuintenQVD0** [comment]
> I can't find any documentation on how to specify the interface to bind to; it appears it binds to 0.0.0.0 by default. You should be able to verify this using netstat

in or outside the container?

**Comment by mikeseese** [comment]
Both. You can start with the container and if that is bound properly, then you should be able to check the host too as I'm guessing you're instantiating these containers using the host network option.

**Comment by vp-en** [comment]
Tried to run a `netstat -peanut | grep ":35585"` and for port `35586`
```
hetzner@hostname01:~$ sudo netstat -peanut | grep ":35585"
tcp        0      0 213.XXX.194.XX:35585    0.0.0.0:*               LISTEN      0          44827      10158/docker-proxy
udp        0      0 213.XXX.194.XX:35585    0.0.0.0:*                           0          44864      10170/docker-proxy

hetzner@hostname01:~$ sudo netstat -peanut | grep ":35586"
tcp        0      0 213.XXX.194.XX:35586    0.0.0.0:*               LISTEN      0          44802      10133/docker-proxy
udp        0      0 213.XXX.194.XX:35586    0.0.0.0:*                           0          44812      10145/docker-proxy
```

Not sure if that's useful.

**Comment by mikeseese** [comment]
I might be able to take a look at it when I'm back in town Monday

**Comment by QuintenQVD0** [comment]
I found some time friday evening but my setup is not that real world as my vm is localy hosted so it does not go over the internet

**Comment by mikeseese** [comment]
I've probably spent 4 hours total trying to get Pterodactyl to run in a Docker environment and still no dice, and I don't want to pollute my home server with executables installed bare-metal. As someone with years of experience building SaaS platforms with Docker/Kubernetes, this setup process is beyond complicated. Unfortunately, I'm just a volunteer and I simply can't dedicate more time supporting this effort. It'll be up to the community to get this integration working. If you have any specific feature requests, you can make them in the Swords 'n Magic Discord server under the #dedicated-servers forum channel and I'll do my best to implement reasonable requests.

I wanted to set this up myself so I can use client and server builds that have more logging in them and also to reduce the communication lag of going back and forth with someone doing testing. We don't do much special when it comes to the networking stack. We run Unreal with default networking stack, listening on the default port 7777. We then use Steamworks to register servers and use the default query port there too. The error that @vp-en is receiving is a catch all; my guess is the error you'd see is "connection was closed" because there was no open socket at that IP and that the server is simply not receiving the request.

If all of your port forwarding is configured properly, you'd see your server listed in the server browser in the game client. It's possible for a Steam session to be created but the query port is not accessible; if the query port is not accessible, then clients won't display the server.

Best of luck.

**Comment by vp-en** [comment]
> I've probably spent 4 hours total trying to get Pterodactyl to run in a Docker environment and still no dice, and I don't want to pollute my home server with executables installed bare-metal. As someone with years of experience building SaaS platforms with Docker/Kubernetes, this setup process is beyond complicated. Perhaps I'm being dumb 🤷 

First of all, thank you for your help so far 👍 ❤️ . I had a terrible time as well getting Pterodactyl to work. I got it to work by abiding by their folder-setup. So on the wings/node, I mapped it exactly 1:1, like `"/etc/pterodactyl/:/etc/pterodactyl/"` it says and not try and map the `/etc/pterodactyl` (or any of the other volumes) to anything else. Otherwise it wouldn't let me install anything/setup a server.

> Unfortunately, I'm just a volunteer and I simply can't dedicate more time supporting this effort. It'll be up to the community to get this integration working. If you have any specific feature requests, you can make them in the Swords 'n Magic Discord server under the #dedicated-servers forum channel and I'll do my best to implement reasonable requests.

❤️❤️ 
 
> I wanted to set this up myself so I can use client and server builds that have more logging in them and also to reduce the communication lag of going back and forth with someone doing testing. We don't do much special when it comes to the networking stack. We run Unreal with default networking stack, listening on the default port 7777. We then use Steamworks to register servers and use the default query port there too. The error that @vp-en is receiving is a catch all; my guess is the error you'd see is "connection was closed" because there was no open socket at that IP and that the server is simply not receiving the request.

It's all kind of weird to me honestly. I have **no** firewall setup on Hetzner, other than "allow all", and no `ufw` active on my Ubuntu setup:
https://i.imgur.com/5snOUOR.png


> If all of your port forwarding is configured properly, you'd see your server listed in the server browser in the game client. It's possible for a Steam session to be created but the query port is not accessible; if the query port is not accessible, then clients won't display the server.

I also tried to allocate 7777 and 27015 in Pterodactyl and set up the server using the original ports, but that still didn't work for me :(. It gives the same error. And it still doesn't show up in the server browser thingy.

My `iptables -L` only shows docker related stuff as well:
https://paste.ec/paste/Bz3WWgql#xmK+4FB4ijcs71uDcGiZVr9-ZYoJ3x2zXIrql4Z9Fdk


> Best of luck.

Thanks. Hopefully this'll work out :)

**Comment by QuintenQVD0** [comment]
I do not own the game but that is not realy the issue as i home host so yea it could be using nat

**Comment by vp-en** [comment]
If I can help with anything else, just give me a heads up 🙂

**Comment by mikeseese** [comment]
As of June 20, the game finally got the release. I was out of town on a couple long trips, so this totally slipped my mind. You should be able to use the `-log` parameter and remove the wrapper application in this PR. At a minimum, @QuintenQVD0 should be able to run a server and either @vp-en or myself can run the client and see if we can connect to it (since neither of us had success getting the server to run via Pterodactyl). If that all works, this PR could finally be put to rest.

**Comment by QuintenQVD0** [comment]
@mikeseese @vp-en Egg updated for the new version and working fine now.

@parkervcp This can be reviewed now. (and likely squash merged)

**Review by parkervcp — APPROVED** [review]

**Comment by vp-en** [comment]
@QuintenQVD0 Still getting the same issue using the new egg, unfortunately.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Still getting the same issue using the new egg, unfortunately.

This still sounds like a firewall issue to me as if you have allocated the 2 needed ports. And set the query one in the variable. Then it will start and bind to them fine. Are they both tcp and upd open?

**Comment by EvilGenius13** [comment]
> @QuintenQVD0 Still getting the same issue using the new egg, unfortunately.

If you are talking about the port issue, I'm having the same trouble. I tried running a server that uses the same game port (7777) and they worked for me but I just can't get a connection with this one.

**Comment by mikeseese** [comment]
@EvilGenius13 @vp-en can either of you DM me on Discord for us to try to debug what's going on? I'm `mikeseese` on Discord. If the server logs look like it does in https://github.com/parkervcp/eggs/pull/2249#issuecomment-1585658839, then we can use some process of elimination to determine the issue.

**Comment by mikeseese** [comment]
Heads up @vp-en, looks like I have the help I need to debug this further; I'll update this if there are any updates. I don't think a networking configuration is the issue.

**Comment by mikeseese** [comment]
I was able to figure out what was going on. This egg should work after the next version of the game is released that will package some extra DLLs for wine to load

**Comment by vp-en** [comment]
Thanks @mikeseese for all the work you've put into this. I'll test again once the next patch goes out

**Comment by mikeseese** [comment]
1.7.0 is being released tomorrow, which includes the fixes for this egg. No updates to this egg are necessary.

**Comment by vp-en** [comment]
It works now 👍

**Pull request merged**
