### PR TITLE
Update of SCP:SL egg for stability.

### PR DESCRIPTION
**Pull request by wistlyr**
## Purpose:
The current SCP: Secret Laboratory egg is prone to an issue where it does not accept input through the console. To remedy this, I've rebuilt the egg to use MultiAdmin with a config option instead of LocalAdmin, as a friendly frontend for Pterodactyl to interface with. This egg has not crashed in my tests, but further testing would be appreciated. A before and after is as follows:

**BEFORE:**
Old SCP:SL egg not working.

**AFTER:**
New SCP:SL egg working.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by gOOvER** [comment]
This is not Vanilla. U use Multiadmin which is a 3rd Party Plugin.

Egg from.my Site work, as it should.

I would recomment to create a NEW Egg called MultiAdmin or something

**Comment by wistlyr** [comment]
multiadmin is a wrapper for localadmin, which allows servers to have multiple configurations per instance. in this case, it is used to fix the console input issue.

**Comment by gOOvER** [comment]
> multiadmin is a wrapper for localadmin, which allows servers to have multiple configurations per instance. in this case, it is used to fix the console input issue.

But IT's 3rd Party Plugin.

i can't confirm errors with Localadmin

**Comment by wistlyr** [comment]
multiadmin is endorsed by the scp:sl devs in their own discord server. localadmin does not work with text input, and is faulty as a result. multiadmin is the next best option for server stability, and i will not vouch for server instability brought about by the previous egg.

**Comment by gOOvER** [comment]
@wistlyr but not official from SCPSL Team

**Comment by parkervcp** [comment]
I don't need you to arguing all over the place.

Can someone that's not one of these two test this out please?

**Comment by srkhost** [comment]
Yep, it's working for me.

**Comment by parkervcp** [comment]
@wistlyr I think this would be better moving it to a separate egg and letting the two duke it out.

**Comment by wistlyr** [comment]
@parkervcp I hope I did it right lmao I rarely use github

**Comment by parkervcp** [comment]
Looks good to me.

**Pull request merged**
