### PR TITLE
Add waterdog pe

### PR DESCRIPTION
**Pull request by Ree-jp**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### CODE REVIEW

**Review by Software-Noob — CHANGES_REQUESTED** [review]
Please don't create a duplicate category. Put this below the existing WaterDog egg inside the same cross_platform folder.

**Comment by Ree-jp** [comment]
Unlike existing waterdogs, this waterdog PE is only compatible with the bedrock version, so cross-platform is not suitable

**Review by Software-Noob — CHANGES_REQUESTED** [review]
In that case, please correct the readme

**Comment by Software-Noob** [comment]
The start configuration of the waterdog doesn't work with PE. It never outputs `Listening on `

```
15:06:12 [INFO ] Starting WaterDogPE proxy software!
15:06:12 [INFO ] Software Version: 1.1.2
15:06:12 [INFO ] Build Version: 11
15:06:12 [INFO ] Development Build: false
15:06:12 [INFO ] Software Authors: WaterdogTEAM
15:06:12 [INFO ] Discovered branch release commitId b1823c9
>
15:06:20 [INFO ] Loading resource packs!
>
15:06:20 [INFO ] Loaded 0 packs!
>
15:06:20 [INFO ] Binding to /0.0.0.0:19132
>
15:06:20 [INFO ] Started query on address /0.0.0.0:19132
```
Changing it to `Started query on` would be more appropriate to determine when the server is running correctly.

```{
    "done": "Started query on"
}
```

To get rid of the new lines > after each message, change startup to `java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}`

After that, everything looks good to me and works as it should.

**Review by Software-Noob — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
