### PR TITLE
add RageCOOP 

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

add RageCOOP 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

closed: #1832 

note: can not use parcker debian install image as it supports arm64

### CODE REVIEW

**Comment by parkervcp** [comment]
@QuintenQVD0 Is their website being down going to cause issues here?

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Is their website being down going to cause issues here?

Normaly not as the server files are pulled from here: https://github.com/RAGECOOP/RAGECOOP-V and the config is generated with a egg so it still should work.

**Comment by QuintenQVD0** [comment]
It works for me , Last PR just remove support arm as it is a 32 bit bin.
https://github.com/parkervcp/eggs/issues/1832#issuecomment-1256467597

**Comment by QuintenQVD0** [comment]
@parkervcp There website is back online and the files are pulled thru github and this is working for me

**Review by parkervcp — APPROVED** [review]
LGTM

**Pull request merged**
