### PR TITLE
Space Engineers Vanilla: Add ExperimentalMode and InGameScript options.

### PR DESCRIPTION
**Pull request by risingfish**
# Description
The change adds 2 new parameters to the vanilla space engineers egg. There are no open issues for this, but I though these would be nice to have for folks who like to run modded games.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
.. you have to make all changes in a panel, then export and fully replace the .json file. Not just some part.

**Comment by risingfish** [comment]
> .. you have to make all changes in a panel, then export and fully replace the .json file. Not just some part.

Yeah, I read the contributing guidelines and realized that after the PR was created. :) I could find where the variable substitution happens in the panel though.

**Comment by risingfish** [comment]
Tested creating a new server and as well as modifying an existing server.

**Comment by QuintenQVD0** [comment]
@gOOvER I think you are the best to confirm this

**Comment by gOOvER** [comment]
i'll test IT tomorrow:)

**Comment by QuintenQVD0** [comment]
> i'll test IT tomorrow:)

did you test it?

**Comment by gOOvER** [comment]
> > i'll test IT tomorrow:)
> 
> did you test it?

i'll added some of my fixes to his egg, so no need to pr them later. His changes works for me

@risingfish  pls use this egg

[egg-space-engineers.zip](https://github.com/parkervcp/eggs/files/12136225/egg-space-engineers.zip)

It contains some more fixes for SE fropm my site, so no need to PR them after your PR is merged

**Comment by gOOvER** [comment]
@risingfish 

I'll created a PR in your repo

https://github.com/risingfish/eggs/compare/space-engineers/more-config-options...gOOvER:parkervcp-eggs:patch-14

**Comment by QuintenQVD0** [comment]
> @risingfish
> 
> I'll created a PR in your repo
> 
> https://github.com/risingfish/eggs/pull/1/files

I can push them on this pr if you want. Why go to wine latest and move from staging?

**Comment by gOOvER** [comment]
> > @risingfish
> > I'll created a PR in your repo
> > https://github.com/risingfish/eggs/pull/1/files
> 
> I can push them on this pr if you want. Why go to wine latest and move from staging?

Would be great :)

because staging have a bug, which prevent servers posting console output. Its the same error like for conan.

mb you also can rerun wine stable to update to 8.0.2

**Comment by QuintenQVD0** [comment]
> > > @risingfish
> > > I'll created a PR in your repo
> > > https://github.com/risingfish/eggs/pull/1/files
> > 
> > 
> > I can push them on this pr if you want. Why go to wine latest and move from staging?
> 
> Would be great :)
> 
> because staging have a bug, which prevent servers posting console output. Its the same error like for conan.
> 
> mb you also can rerun wine stable to update to 8.0.2

Changes added,

wine is rebuilding, so staging is at 8.12 and latest at 8.0.2

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! Thank you both!

**Comment by gOOvER** [comment]
> wine is rebuilding, so staging is at 8.12 and latest at 8.0.2

ty :)

**Comment by risingfish** [comment]
Boy, step away for a couple days and all the magic happens. :) Looking for to see if the wine updates make the game run a little, or at least shutdown a little faster.

**Comment by RogueRaiden** [comment]
could the same be done for the torch version as well?

**Pull request merged**
