### PR TITLE
discord.js remove --production and unused code

### PR DESCRIPTION
**Pull request by docimin**
This pr removes some useless code and removes the --production on npm install, as discord often uses -dev packages and removes confusion.
Makes it generally more simple for people to run bots without having to figure out to remove the --production (not needed for bots)

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Review by parkervcp — CHANGES_REQUESTED** [review]
the usr bin layout guarantees it uses the installed version of npm and not a path set version...

**Comment by parkervcp** [comment]
might as well integrate #1252 as well

**Comment by docimin** [comment]
Alrighty!

**Comment by docimin** [comment]
Should be it!

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
