### PR TITLE
Remove invalid utf8 character

### PR DESCRIPTION
**Pull request by Kurounin**
Remove the character \u201c90 from installation script which caused an error

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the nesessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by SeaLife** [comment]
Why did you closed the first one? 
#234

**Comment by Kurounin** [comment]
@SeaLife To rename the branch

**Comment by parkervcp** [comment]
@Kurounin Please see my review.

**Comment by Kurounin** [comment]
@parkervcp what review are you referring to?

**Comment by parkervcp** [comment]
I made a request for you to leave the "90" in the command you removed it along with the unicode.

**Comment by Kurounin** [comment]
Can't see the request, but I added the 90 back. Missed it on initial commit.

**Comment by parkervcp** [comment]
@Kurounin Why are you adding max players to this?

I try not to force max players as a variable and let the server hosts/owners set them up themselves. If I do add it I try to set it at the maximum.

**Comment by Kurounin** [comment]
Sorry didn't think it would be an unwanted change. I'll revert the change for MAX_PLAYERS.

**Pull request merged**
