### PR TITLE
Add Valheim

### LINKED ISSUE #959: Egg Request: Valheim
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Valheim dedicated server

Does this expand an already existing service: Y, it's SteamCMD, linux compatible

Link to game: https://store.steampowered.com/app/892970/Valheim/

Links for server downloads:  https://steamdb.info/app/896660/

Links for install steps/docs: https://steamcommunity.com/sharedfiles/filedetails/?id=2382282960 (usual SteamCMD setup really)

### PR DESCRIPTION
**Pull request by Magi1053**
I started off with the egg from #965 but it was semi non functional, so I rewrote the startup script and made some other changes such as actually outputting the server log and using the native server shutdown trigger

Closes #959

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by Software-Noob** [comment]
Remove file_denylist or otherwise the egg importing will not work for the latest panel versions until the next release when that issue is resolved.

**Comment by Software-Noob** [comment]
You have validate flag in your install, all eggs by default do not perform any destructive actions on reinstall. Your startup exports of the LD path could just be a variable. I do not see any reason why are you exporting auto_update or APP_ID?

**Comment by Magi1053** [comment]
@Software-Noob What is the reason for putting the startup exports into a variable instead of leaving them them as is?

**Comment by Software-Noob** [comment]
> @Software-Noob What is the reason for putting the startup exports into a variable instead of leaving them them as is?

It's pointless clutter in the startup for no reason, your three export lines for LD LIB PATH could just be one hidden variable.

**Comment by Magi1053** [comment]
I'm getting syntax errors putting the multiple exports into 1 variable, could you provide me with an example?

**Comment by Magi1053** [comment]
So the server spits out a ton of useless debug info that I was piping to sed to filter out, but I can't seem to get that to work when it's inside of the variable

**Comment by Magi1053** [comment]
@Software-Noob Take a look at that and lmk what you think

**Comment by Magi1053** [comment]
The shutdown trigger is not functional, working on a fix.

**Comment by Software-Noob** [comment]
Your INIT variable for LD LIB PATH could just be set to ./linux64 and renamed to LD_LIBRARY_PATH as done in other eggs such as [here](https://github.com/parkervcp/eggs/blob/77ea6c770a428f130cc4c7637801084be511c8b4/steamcmd_servers/avorion/egg-avorion.json#L135) and [here](https://github.com/parkervcp/eggs/blob/77ea6c770a428f130cc4c7637801084be511c8b4/steamcmd_servers/7_days_to_die/egg-7-days-to-die.json#L63 ). You also don't have to include it in the startup for exporting.

Other than that LGTM except for that double quote in the server password description. The server starts, can be joined, and stops as it should.

**Comment by gOOvER** [comment]
I see no need to use any external Image. As i see you can also use Debain:source

**Comment by gOOvER** [comment]
Some Errors:

`./steam/steamcmd.sh: line 37: /home/container/steam/linux32/steamcmd: No such file or directory
:/home/container$ ./start_headless_server.sh -nographics -batchmode -name TestServer -port 2456 -public 1 echo Server started
/entrypoint.sh: line 13: ./start_headless_server.sh: No such file or directory`

Headless dont existst after download

**Comment by gOOvER** [comment]
Next thing is; You know, that you need Mono? Your Egg will never work. You Image is a normal Ubuntu 20.04 Source Image.

**Review by gOOvER — CHANGES_REQUESTED** [review]
Some Errors:

./steam/steamcmd.sh: line 37: /home/container/steam/linux32/steamcmd: No such file or directory :/home/container$ ./start_headless_server.sh -nographics -batchmode -name TestServer -port 2456 -public 1 echo Server started /entrypoint.sh: line 13: ./start_headless_server.sh: No such file or directory

There is no start_headless_server.sh after download

Only a start_server.sh. Pls Update, because i don't found such an Linus Server in any Guides

In this state, your egg is complete broken

**Review by gOOvER — CHANGES_REQUESTED** [review]
Next thing is; You know, that you need Mono? Your Egg will never work. You Image is a normal Ubuntu 20.04 Source Image.

**Comment by Magi1053** [comment]
> There is no start_headless_server.sh after download Only a start_server.sh.

start_server.sh is part of the server download and it the egg does not use it at all. 

>./start_headless_server.sh: No such file or directory

I have no idea why you are starting your server with that file, it is not part of the server download and my egg does not create it or use it at all. `start_headless_server.bat` is a file that is in the windows version of the server, but this egg uses the linux version. 

The egg launches with the native linux binary `./valheim_server.x86_64  -nographics -batchmode...`. I'm not sure if mono is required in the image or not, but the server definitely does start and is joinable and @Software-Noob [confirms it](https://github.com/parkervcp/eggs/pull/968#issuecomment-774762575).

**Comment by arriej** [comment]
Container is running fine for me, unfortunately not joinable, port stays closed.

**Comment by xardoniak** [comment]
Container _appears_ to be running, but is not joinable.
Hopefully these screenshots are useful!
image
image
image
image

**Comment by xardoniak** [comment]
Same as above - server appears to be working, but is not joinable. Screenshots,
image
image
image

**Comment by Magi1053** [comment]
@arriej @xardoniak When using the steam server browser you need to use the query port 2457 not the game server port.

**Comment by xardoniak** [comment]
@Magi1053 Beautiful! Good old user error!
image
Working in game now, too. Not sure what the difference was before and now as it wasn't showing up earlier today. Maybe the server takes some time to auth against the master list??
image

**Comment by Magi1053** [comment]
Yeah their in game server list is kinda poo imo

**Comment by Magi1053** [comment]
Should I maybe swap around the game server and query ports so that people don't get confused?

**Comment by xardoniak** [comment]
Might be a good idea!

I know this isn't the best place for this but unsure how to DM you! What's your thoughts on hosting 2 instances of the server on the same IP? I'm wanting to set up a public server AND a private sever. Is it as simple as just spinning up another instance, then changing the 3 IPs to something else? eg 2458, 2459, 2460?

**Comment by Magi1053** [comment]
I thought about swapping the game server and server query ports, but looking at other example eggs such as Ark the primary port is the game server port and the server query port is a variable. So based on that I think it would be good to keep it the way it is.

**Comment by arriej** [comment]
I try to ping the port directly on the machine, after it not responding in the server browser. And when I check 2456, 2457 or 2458 they are staying closed. This is the only egg that has this issue.

**Comment by Software-Noob** [comment]
> I try to ping the port directly on the machine, after it not responding in the server browser. And when I check 2456, 2457 or 2458 they are staying closed. This is the only egg that has this issue.

The egg does not have any control over ports, if you allocated the ports then Pterodactyl should open them unless you have a firewall blocking it.

**Comment by arriej** [comment]
Then I'm not sure where the issue is then. I've tried to test this other egg "https://github.com/RestoreMonarchy/pterodactyl-Valheim" and that one opens the ports fine but the server doesn't work for me.

**Comment by grimesy88** [comment]
I have the egg running without issue. I had an issue with ports but what I had to do was ensure I give the server two allocations. That way the egg will use the first port and second port for game and query. When connecting to the server via Steam > View > Servers you need to use the second port to connect. So from an egg point of view it all seems good. Now as for the game itself and its severe desync problems, that's another story!

**Comment by AvonGenesis** [comment]
How many ports does this egg officially need? I ran a netstat in the container and only saw it listening on one port (game server port +1)

Spent about an hour troubleshooting to find that the game was accepting connections on a different port from what was configured in the Pterodactyl interface.

**Comment by Software-Noob** [comment]
> How many ports does this egg officially need? I ran a netstat in the container and only saw it listening on one port (game server port +1)
> 
> Spent about an hour troubleshooting to find that the game was accepting connections on a different port from what was configured in the Pterodactyl interface.

Two ports as listed in readme: Game port and query port which is game port +1 with query port being the port used for connections.

**Comment by Butain** [comment]
@Magi1053  This is working great for me so far, thanks for working on it!

**Comment by xardoniak** [comment]
@Magi1053 I've been using this successfully for a little under a week now.
Some issues I've come across,

1. Server commands don't seem work: https://www.yekbot.com/valheim-admin-commands/
The console doesn't output anything for info or help, for example
2. We seem to lose some world data (maybe 30 mins?) on reboot (eg building progress, chest contents etc)

**Comment by Magi1053** [comment]
@xardoniak thank you for your concerns. First off, the dedicated server admin console does not respond to any input from the user. All admin commands in the example you listed are used in game only, that guide even tells you how to do it. Second regarding the server stopping gracefully, we are using the SIGINT signal to gracefully shutdown the server. Please make sure your egg and variables are up to date, the shutdown command is functional with the latest server version.

**Comment by xardoniak** [comment]
> @xardoniak thank you for your concerns. First off, the dedicated server admin console does not respond to any input from the user. All admin commands in the example you listed are used in game only, that guide even tells you how to do it. Second regarding the server stopping gracefully, we are using the SIGINT signal to gracefully shutdown the server. Please make sure your egg and variables are up to date, the shutdown command is functional with the latest server version.

Yeah I've come across a few servers that are like this recently, which seems a little silly. I guess I've been spoiled by the Minecraft server software.

I thought I had the latest version of the egg, but it turns out I didn't! I haven't had the opportunity to test shutting down a server and seeing if data stays but I assume its fine.

**Pull request merged**
