### PR TITLE
Added Left 4 Dead 2

### PR DESCRIPTION
**Pull request by NgLoader**

### CODE REVIEW

**Comment by parkervcp** [comment]
@NgLoader Can this not be handled by the default `Custom Source Engine` ?

**Comment by NgLoader** [comment]
@parkervcp For me it's not working

**Comment by parkervcp** [comment]
Can you tell me why it's not working.? @NgLoader

**Comment by NgLoader** [comment]
Oh, sry I tried it again and it's work now.

**Pull request closed without merging**
