### PR TITLE
add Minio S3 egg

### PR DESCRIPTION
**Pull request by tmunsch**
[x] Have you followed the guidelines in our Contributing document?
[x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Have you added the server to the main README.md?
3. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by tmunsch** [comment]
Once this is merged we will need to update the egg to pull from the correct location

**Comment by Software-Noob** [comment]
> Once this is merged we will need to update the egg to pull from the correct location

That's just a waste of time, you can already define the future location of the files when they will be merged

**Comment by ClemKristian** [comment]
Not sure if this is the correct place to ask, but is there anyway to configure this as your S3 Backup instead of using AWS? Going off the [Additional Configuration](https://pterodactyl.io/panel/1.0/additional_configuration.html) page. Would I just replace every occurrence of AWS with MINIO or configure the options to point to a Minio server instead?

**Comment by ClemKristian** [comment]
Not sure if this is the correct place to ask, but is there anyway to configure this as your S3 Backup instead of using AWS? Going off the [Additional Configuration](https://pterodactyl.io/panel/1.0/additional_configuration.html) page. Would I just replace every occurrence of AWS with MINIO or configure the options to point to a Minio server instead? Or would the process be more involved?

**Pull request merged**
