### PR TITLE
Add Open Fortress

### PR DESCRIPTION
**Pull request by elitetheespeon**
Add egg for Open Fortress

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by mixerrules** [comment]
I was attempting to setup a server using this egg, setup seem to work fine but when I attempted to start the server it gives me the following then attempts to restart:

container@pterodactyl~ ./srcds_run -game open_fortress -console -port 27047 +map dm_2fort +ip 0.0.0.0 -strictportbind -norestart -debug +maxplayers 24
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
Using Breakpad minidump system. Version: 7370160 AppID: 232250
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Loaded 2710 VPK file hashes from /home/container/tf2/tf/tf2_misc.vpk for pure server operation.
Loaded 1343 VPK file hashes from /home/container/tf2/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 478 VPK file hashes from /home/container/tf2/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 10454 VPK file hashes from /home/container/tf2/tf/tf2_textures.vpk for pure server operation.
Loaded 1217 VPK file hashes from /home/container/tf2/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /home/container/tf2/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /home/container/tf2/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 446 VPK file hashes from /home/container/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/container/platform/platform_misc.vpk for pure server operation.
Segmentation fault (core dumped)
cat: hlds.1.pid: No such file or directory

**Comment by Dr3nz4r** [comment]
Just me being goofy but is it wise to have the egg require your own webserver to deliver the gameinfo.txt? shouldn't it download it from this repo instead?

**Comment by Software-Noob** [comment]
> Just me being goofy but is it wise to have the egg require your own webserver to deliver the gameinfo.txt? shouldn't it download it from this repo instead?

It's a requirement to have it on the github repository or an official link and a personal web server is neither. I have not completed the review to comment on everything yet.

**Comment by elitetheespeon** [comment]
> Just me being goofy but is it wise to have the egg require your own webserver to deliver the gameinfo.txt? shouldn't it download it from this repo instead?

The intent was to manually write the file with cat, but for the sake of time I did it that way. I will be making some commits later and one of them will do this the intended way, the other will include a fix for [murse](https://github.com/w3bb/murse), as it seems to hit the mirror rate limiting currently due to something changed on OpenFortress end.

**Comment by elitetheespeon** [comment]
I have fixed the issues downloading OpenFortress game files with help from the developer of Murse and the manager of the OpenFortress download mirror. Additionally I have changed the gamedata to be created in-line on the install script and not downloaded from anywhere. Commit e59dc07 fixes these issues and now I consider this egg ready.

**Comment by w3bb** [comment]
Hey, creator of murse here.

It's a very bad idea to use that link to download murse. I have versioned tarballs on sourcehut you should use instead. I'm going to make a small release shortly that fixes a small error in the tarballs we make, and from then on should be a matter of bumping the version.

**Comment by w3bb** [comment]
I've made the release, you can find the versions and their tarballs here: https://git.sr.ht/~welt/murse/refs

**Comment by w3bb** [comment]
(For future readers v0.2.1 and later is good.)

**Comment by elitetheespeon** [comment]
> Hey, creator of murse here.
> 
> It's a very bad idea to use that link to download murse. I have versioned tarballs on sourcehut you should use instead. I make zero promises about keeping that link as it is; it's subject to change. I'm going to make a small release shortly that fixes a small error in the tarballs we make, and from then on should be a matter of bumping the version.

This has been fixed in the latest commit, I am using the tgz of the direct version that works on the site you linked.

**Comment by gOOvER** [comment]
> > Just me being goofy but is it wise to have the egg require your own webserver to deliver the gameinfo.txt? shouldn't it download it from this repo instead?
> 
> It's a requirement to have it on the github repository or an official link and a personal web server is neither. I have not completed the review to comment on everything yet.

Here is the point; you never have time. Invest 1h a day or pls step back as maintainer

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
