### PR TITLE
 Update egg-among-us--impostor-server.json

### PR DESCRIPTION
**Pull request by protoxz**
### All Submissions:

* [v ] Have you followed the guidelines in our Contributing document?
* [v ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ v] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [v ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [v ] Have you tested your Egg changes?

Add {{server.build.default.ip}} variable in the config, to automatically set the right IP Address

### CODE REVIEW

**Comment by gOOvER** [comment]
As i know is the public IP everytime 127.0.0.1. So your PR is incorrect

**Review by gOOvER — COMMENTED** [review]
As i know is the public IP everytime 127.0.0.1. So your PR is incorrect

**Comment by protoxz** [comment]
If i let 127.0.0.1, only me can join the server, when i changed it to my modification, others players were able to join

**Comment by protoxz** [comment]
> As i know is the public IP everytime 127.0.0.1. So your PR is incorrect

If i let 127.0.0.1, only me can join the server, when i changed it to my modification, others players were able to join

**Comment by gOOvER** [comment]
the public ip is not for jouning

**Comment by protoxz** [comment]
Maybe, but i swear adding publicIp resolved my joining issue

**Comment by gOOvER** [comment]
ListenIP is for joining, not PublicIP. Read the Serverdocs.

So i'm against merging this

**Review by gOOvER — CHANGES_REQUESTED** [review]
This PR is wrong

**Comment by protoxz** [comment]
Yeah, in the docs it's what they say ;


PublicIp | 127.0.0.1 | This needs to the public IPv4 address of the server which you give to others to connect. You can find your IPv4 address on this website. Unless you are only planning to use Impostor privately, on your local network, you should change this to your public ip. It is also possible to use hostnames instead of IPv4 addresses, which will be resolved to IPv4 addresses.

It's the public IP you have to change, unless you only play local.

(i'm french, maybe i missunterstood something ?)

**Comment by gOOvER** [comment]
You are the first, which have problems with that.

PublicIP only Shows your IP to others, but have nothing to Do with Connecting.

btw. 127.0.0. is the ip of your rootserver and not the Container, where Impostor Runs. ;)

I will test it, when i'm at home, but they dont change anything, so you should be able to connect.

Pls Post a log of a Login Try

**Comment by gOOvER** [comment]
How did you connecr? You know, that you need to use your Server IP in the Client?

**Comment by protoxz** [comment]
> How did you connecr? You know, that you need to use your Server IP in the Client?

In the client, i specified the server ip:port, and ingame, i can join,
But when i let the default value, i other players cant join, only create game

**Comment by gOOvER** [comment]
The Version 1.1.0 don't support latest AmongUs

chrome_CwxnwFCwEA

**Comment by gOOvER** [comment]
btw: This line was removed in:

https://github.com/parkervcp/eggs/commit/3619a3dab9f9391b7ebc8232def80ad299471a8e#diff-b51f1fabee9449fe4db48b83e031d1301769094f7e68b5464c07df24719e7c6e

**Pull request closed without merging**
