### PR TITLE
Add Umod Servers folder - Add Valheim to Umod Servers

### PR DESCRIPTION
**Pull request by J-Pster**
### All Submissions:

*  [x]  Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

**To Parketvcp:**
I started working on an EGG for Valheim when I bought the game, a week ago, I exposed my work on GitHub on the 19/02 a few days later I divulged my project on Pterodactyl's discord and uMod's discord, I was working on the project and perfecting it to only later make a PR, but I see that this was my mistake, another user whose name you know what it is, created on the 26/02 a PR with the same idea as my project, this user talked to me in the Pterodactyl discord, being arrogant and saying that he had a project that worked, in the GitHub of this user, there was (but he deleted) a Fork of my project a few days ago, I believe that this user, got my repository, modified (and congratulations for his work) and made an AutoUpdate, however, removed any credit that I had from the project.

The evidence of what I said here, is saved in messages, such as the message I sent to you, Parkervcp, on Feb 21st, and in the comment: https://github.com/parkervcp/eggs/pull/1010#issuecomment-786911853, there are also more arguments about this in the commentary: https://github.com/parkervcp/eggs/pull/1010#issuecomment-787095372 .

**Anyway, if gOOvER is in fact not the same person as Software-noob, then Software-noob is stealing my project.**

My intention then is to take my now-completed project, merge parts of the Software-Noob's project, credit both, because obviously he took my project and made a few changes and now is trying to make a PR without even mentioning my name.

**To all:**
Everyone who wants to add, edit or remove parts of what has been done here WILL be recognized, and WILL get the credit.

### CODE REVIEW

**Comment by Software-Noob** [comment]
I am not in any way related to any other people, please stop thrash talking my name.

**Comment by CastBlacKing** [comment]
I have presented evidence, but the decision is in Parkervcp's hands, if he tells me to delete everything, I will.

**Comment by Software-Noob** [comment]
> I have presented evidence, but the decision is in Parkervcp's hands, if he tells me to delete everything, I will.

I don't see any evidence nor do I care what beef you have with other users, it's not a valid reason to talk trash about my name. If you have issues with someone, report them to staff and don't publicly witch hunt.

A simple view of the Discord/Github profile would clearly indicate that we're entirely different people. Especially, considering that I made my own image and egg in one day yesterday; which you appear to have copied and accuse me of being another user and stealing your work. I was literally the person helping you in Discord.

**Comment by gOOvER** [comment]
> I have presented evidence, but the decision is in Parkervcp's hands, if he tells me to delete everything, I will.

You have nothing; i don't know, where exact your Problem is, stop spreading lies. I only tell you in Discord, that ur egg don't work. If you can't live with the truth; your Problem.

Same with this Egg:

- You submit an own Image, but u use debian_source
- I got following error:
```
Using anonymous user.
/entrypoint.sh: line 22: ./steamcmd/steamcmd.sh: No such file or directory
```
I can't connect the Server after install

**Comment by CastBlacKing** [comment]
Are you really not gOOvEr?

**Why** when I went to your GitHub profile did I find a Fork of my repository that is now deleted?
**Why** when I accused "gOOvEr" saying: "...and claim it as your "test"." in discord of having copied me he said "Yeah, i use it for testing but your egg was totally wrong" when I went to your repository, Softwarenoob and that's where I saw "Test" written, why you have Noob in the name and he has Noob in the picture, why do you speak in different time intervals and every time you say something he agrees?
**Why** did another user comment in your PR: "Looks to be someone working on this idea but they are stuck with an auto update issue affecting both the server and umod"?
**Why** do you both have sites that don't work, as if it was just to give more credit to the profile?

And finally, take a look at this similarity of the installation scripts:

Mine:
```
#!/bin/bash
# Valheim Installation Script
# Colors
GR='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Server Files: /vhs/server
# Image to install with is 'debian:buster-slim'
apt update && apt upgrade -y
apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
```

Yours:
```
#!/bin/bash
# Valheim Installation Script

# Server Files: /vhs/server
# Image to install with is 'debian:buster-slim'
apt update && apt upgrade -y
apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
```
(Note, that /vhs/server was a comment I made on my code, DAYS before you published yours.)


Mine:
```
## create files to install server
mkdir -p /mnt/server
cd /mnt/server
chown -R root:root /mnt
export HOME=/mnt/server

# uMod fails otherwise for some reason, even running as root.
# This is changed at the end of the install process anyways.

# fixes Couldn't find a valid ICU package installed on the system
cd /mnt/server

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile
export PATH="$PATH:/mnt/server/.dotnet/tools/"

log "Installing uMod global tool..."
dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
```

Yours:
```
## Initialize folder permissions
mkdir -p /mnt/server
cd /mnt/server
chown -R root:root /mnt
export HOME=/mnt/server


# Configure dotnet
cd /mnt/server
dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
echo "PATH=\$PATH:\$HOME/.dotnet/tools; export PATH" >> ~/.profile
echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile

mkdir .dotnet && cd .dotnet
curl -sSL -o dotnet-sdk.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.103/dotnet-sdk-5.0.103-linux-x64.tar.gz.
tar -xvf dotnet-sdk.tar.gz && rm dotnet-sdk.tar.gz && cd /mnt/server
```

Mine:
```
$HOME/.dotnet/tools/umod complete --install
clear

chmod +x /mnt/server/.dotnet/tools/umod

## install game using uMod Tool
. ~/.profile
umod install valheim -P
umod new launcher valheim -P --force
chmod +x valheim_server.x86_64
```

Yours:
```
## install game
chmod +x /mnt/server/.dotnet/tools/umod
.dotnet/tools/umod complete --install
. ~/.profile
umod install valheim -P
umod new launcher valheim -P --force
chmod +x valheim_server.x86_64

# Delete unnecessary files
if [ -f /mnt/server/start_server.sh ]; then
rm launcher.sh umod-install.sh start_server.sh start_server_xterm.sh
rm "Valheim Dedicated Server Manual.pdf"
fi
```

Really? You don't even have the courage to say, "Yes I INSPIRED my code in your code."

**Comment by CastBlacKing** [comment]
> 
> 
> > I have presented evidence, but the decision is in Parkervcp's hands, if he tells me to delete everything, I will.
> 
> You have nothing; Again; I never Forked your Egg and so i can't delete it allready. I don't know, where exact your Problem is, but stop spreading lies. I only tell you in Discord, that ur egg don't work. If you can't live with the truth; your Problem.
> 
> I testet this PR. I got following errors:
> 
>     * You submit an own Image ([parkervcp/images#78](https://github.com/parkervcp/images/pull/78)), but u use debian_source. So why you submit it, when u don't use it
> 
>     * I got following error:
> 
> 
> ```
> Using anonymous user.
> /entrypoint.sh: line 22: ./steamcmd/steamcmd.sh: No such file or directory
> ```
> 
> I can't connect the Server after install
> 
> And as Tip; when u save your PR you have Checkboxes to click in the Submit form :)

I made a PR for a new image, because on it, I install the uMod Tool to be used later, and also install DotNet.

I tested everything, in Pterocatyl version 1.0 and 0.7, there is nothing wrong.
But, I can look, maybe I did something wrong, send me the LOGS of the installation.

**Comment by gOOvER** [comment]
Sry, i'm out here. This guy is only a little childish boy, which want to play childhood. Have fun in your life. Igno alsoi for here and next report to abuse team for you.

**Comment by gOOvER** [comment]
btw: when u use my modifications, remove images, which u don't know what i added ;)

**Comment by gOOvER** [comment]
> Are you really not gOOvER? @Software-Noob
> 
> **Why** when I went to your GitHub profile did I find a Fork of my repository that is now deleted?
> **Why** when I accused "gOOvEr" saying: "...and claim it as your "test"." in discord of having copied me he said "Yeah, i use it for testing but your egg was totally wrong" when I went to your repository, Softwarenoob and that's where I saw "Test" written, **why** you have Noob in the name and he has Noob in the picture, **why** do you speak in different time intervals and every time you say something he agrees?
> **Why** did another user comment in your PR: "Looks to be someone working on this idea but they are stuck with an auto update issue affecting both the server and umod" you said "I am not sure how is that related to my egg"?
> **Why** do you both have sites that don't work, as if it was just to give more credit to the profile?
> 
> ## And finally, take a look at this similarity of the installation scripts:
> Mine:
> 
> ```
> #!/bin/bash
> # Valheim Installation Script
> # Colors
> GR='\033[0;32m'
> RED='\033[0;31m'
> NC='\033[0m' # No Color
> 
> # Server Files: /vhs/server
> # Image to install with is 'debian:buster-slim'
> apt update && apt upgrade -y
> apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
> apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
> ```
> 
> Yours:
> 
> ```
> #!/bin/bash
> # Valheim Installation Script
> 
> # Server Files: /vhs/server
> # Image to install with is 'debian:buster-slim'
> apt update && apt upgrade -y
> apt -y install libgcc1 lib32gcc1 gdb libc6 git wget curl tar zip unzip net-tools ca-certificates
> apt update -y && apt upgrade -y && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt update -y && apt install -y dotnet-sdk-5.0 aspnetcore-runtime-5.0 libgdiplus
> ```
> 
> ### (Note, that /vhs/server was a comment I made on my code, DAYS before you published yours.)
> ( Which, by the way, is wrong, there is no /vhs/ folder, it EXISTED when I was starting my project, I didn't know yet that i had to put it in /mnt/ )
> 
> Mine:
> 
> ```
> ## create files to install server
> mkdir -p /mnt/server
> cd /mnt/server
> chown -R root:root /mnt
> export HOME=/mnt/server
> 
> # uMod fails otherwise for some reason, even running as root.
> # This is changed at the end of the install process anyways.
> 
> # fixes Couldn't find a valid ICU package installed on the system
> cd /mnt/server
> 
> export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
> echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile
> export PATH="$PATH:/mnt/server/.dotnet/tools/"
> 
> log "Installing uMod global tool..."
> dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
> dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
> ```
> 
> Yours:
> 
> ```
> ## Initialize folder permissions
> mkdir -p /mnt/server
> cd /mnt/server
> chown -R root:root /mnt
> export HOME=/mnt/server
> 
> 
> # Configure dotnet
> cd /mnt/server
> dotnet tool update uMod --version "*-*" --global --add-source https://www.myget.org/f/umod/api/v3/index.json
> dotnet new -i "uMod.Templates::*-*" --nuget-source https://www.myget.org/f/umod/api/v3/index.json &>/dev/null
> echo "PATH=\$PATH:\$HOME/.dotnet/tools; export PATH" >> ~/.profile
> echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT" >> ~/.profile
> 
> mkdir .dotnet && cd .dotnet
> curl -sSL -o dotnet-sdk.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.103/dotnet-sdk-5.0.103-linux-x64.tar.gz.
> tar -xvf dotnet-sdk.tar.gz && rm dotnet-sdk.tar.gz && cd /mnt/server
> ```
> 
> Mine:
> 
> ```
> $HOME/.dotnet/tools/umod complete --install
> clear
> 
> chmod +x /mnt/server/.dotnet/tools/umod
> 
> ## install game using uMod Tool
> . ~/.profile
> umod install valheim -P
> umod new launcher valheim -P --force
> chmod +x valheim_server.x86_64
> ```
> 
> Yours:
> 
> ```
> ## install game
> chmod +x /mnt/server/.dotnet/tools/umod
> .dotnet/tools/umod complete --install
> . ~/.profile
> umod install valheim -P
> umod new launcher valheim -P --force
> chmod +x valheim_server.x86_64
> 
> # Delete unnecessary files
> if [ -f /mnt/server/start_server.sh ]; then
> rm launcher.sh umod-install.sh start_server.sh start_server_xterm.sh
> rm "Valheim Dedicated Server Manual.pdf"
> fi
> ```
> 
> **Really? You don't even have the courage to say, "Yes I INSPIRED my code in your code."**

Childhood

**Comment by CastBlacKing** [comment]
This image is not yours, and I only used it at the beginning of my project because I didn't know how to make one, you saying this now makes me think even more that you gOOvER is Softwarenoob.

**Comment by CastBlacKing** [comment]
Ahh... and that /vhs/server broke you, you Softwarenoob know that it was in my code, there is no point in lying, and you also know that /vhs/server is an ERROR, an ERROR that I made when I was learning how to do EGG, I thought I could create this /vhs/ folder at the root, but I can't, it has to be /mnt/ and if you are so good that you made an EGG in one day, why do you have a /vhs/ in your code?

Did you make the same mistake as me thinking you could create a folder called /vhs/?
Do you know what VHS is, did you know it means Valheim Host Server? Did you think to abbreviate the same name as me?

And your autoupdate, which is nothing more than LITERALLY ``umod update....`` that was already in MY code for some time and you just added IF'S, but ok, you did a good job, and I GIVE YOU YOUR CREDITS, because I recognize your work, but you WANT TO TAKE MY WORK AND STEAL IT FROM ME AND TAKE MY CREDITS, and that I will not accept.

**Comment by CastBlacKing** [comment]
I am sending this message to make one thing clear, if you @gOOvER in fact are not @Software-Noob , then I apologize.

Anyway, this account called @Software-Noob  is stealing my project and I have clear evidence and similarities and even mistakes made by me in the code that Software-noob posted, he is stealing my project, it is very obvious.

**Comment by gOOvER** [comment]
@parkervcp please stop that here and delete the posts 

@CastBlacKing your image? ok, now i build in a Backdoor. When its your image, then u know where to search

**Pull request closed without merging**
