### PR TITLE
added workshop support

### PR DESCRIPTION
**Pull request by fenpaws**
Added support to automatically download and apply workshop content linked to the used Steam account.

### All Submissions:

* [ X] Have you followed the guidelines in our Contributing document?
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [X ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ X] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
Why not just add the loop to the bottom instead of the middle of the script I wrote?

Also I get this error on install using your script - `ERROR! Missing parameters.`

**Comment by parkervcp** [comment]
I also ask that you make PR's for a branch that isn't "master" in your own repo. Which you acknowledged that you didn't but you clearly have.

**Comment by fenpaws** [comment]
> Why not just add the loop to the bottom instead of the middle of the script I wrote?
> 
> Also I get this error on install using your script - `ERROR! Missing parameters.`

I didn't get that error, I'm currently using it. But I get a different error that resolves itself after you reinstall that server. I'm currently investigating why this happens.

**Comment by fenpaws** [comment]
> I also ask that you make PR's for a branch that isn't "master" in your own repo. Which you acknowledged that you didn't but you clearly have.

Oh damn, yeah there is an excuse for that. I will change it now, I'm sorry. 
After I fixe everything, and that counts your error of a Missing parameter, I will make a PR to my branch thats it not the master branch.

**Comment by fenpaws** [comment]
made a new [PR](380), this time in the correct way. Sorry again

**Pull request closed without merging**
