### PR TITLE
add Citadel: Forged with Fire

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### CODE REVIEW

**Comment by gOOvER** [comment]
resolves #451

**Comment by gOOvER** [comment]
Pls test it and let me know, if there any Issues

**Comment by lakilla21** [comment]
Tried running the egg and got:
`[Pterodactyl Daemon] No server egg configuration could be located; aborting startup.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.`

**Comment by gOOvER** [comment]
> Tried running the egg and got:
> `[Pterodactyl Daemon] No server egg configuration could be located; aborting startup. [Pterodactyl Daemon] Server marked as OFF [Pterodactyl Daemon] A fatal error was encountered while starting this server.`

i take a look for it. Ty :)

**Comment by gOOvER** [comment]
Found the Problem. String will not be saved as it should. Try to fix it now :)

**Comment by gOOvER** [comment]
The problem, i have is this line:

`(ServerName="Citadel Server",Password="YourServerPassword",ServerType=PVP,PlayerLimit=20,bPrivate=true,ExperienceMultiplier=1.000000,InventoryCapacityMultipler=1.000000,KnowledgePointEarnedMultiplier=1.000000,CharacterPointEarnedMultiplier=1.000000,bUnlimitedResources=false,PlayerDamageMultiplier=1.000000,ArmorMultiplier=1.000000,BaseManaRegen=1.000000,bInventoryWeightRestrictions=true,MagicFindMultiplier=1.000000,CraftingMagicFindChanceMultiplier=1.000000,FlyingCostMultiplier=1.000000,FlyingSpeedMultiplier=1.000000,ResourceCollectionMultiplier=1.000000,StructureDamageMultiplier=1.000000,bRespectNoBuildZones=true,MagicStructureManaRegenerationMultiplier=1.000000,MagicStructureManaConsumptionMultiplier=0.000000,bFreeBuildMode=false,TimeOfDayLock=Auto,NPCPopulationMultiplier=1.000000,StructureDecayMultiplier=2.000000,bThronesDecay=true)`

nothing is replaced :/

**Comment by gOOvER** [comment]
@lakilla21 pls test last commit. YOu must change your Values in the World Creation Field.

**Comment by gOOvER** [comment]
Pls test it and let me know, if u can connect. Yesterday i can, now i can't. i get crazy :/

**Comment by lakilla21** [comment]
I will try tomorrow when I wake up. For some reason when trying to add the egg to my nests it gives me:
'The import file must be a file of type: application/json, text/plain.'
Idk if it's me or something with the json file

**Comment by gOOvER** [comment]
Found the problem. One Guide said 7777 is Query Port, another said 27015.

For declaration:

7777 is the ConnectionPort
27015 is the QueryPort 

:)

**Comment by lakilla21** [comment]
Still getting the same error of "The import file must be a file of type: application/json, text/plain." I even tried making a new file with just the code. I don't know if it matters but what version of pterodactyl are you using to make the egg? 1.0?

**Comment by gOOvER** [comment]
> Still getting the same error of "The import file must be a file of type: application/json, text/plain." I even tried making a new file with just the code. I don't know if it matters but what version of pterodactyl are you using to make the egg? 1.0?

How do you import?

I delete Egg and import new. Never see this error

**Comment by parkervcp** [comment]
@lakilla21 

right click the raw button here and save as. don't copy and paste the json.

https://github.com/parkervcp/eggs/blob/b0b1ca98e9ce76ef45f8ec4304ff778387f6c8b8/steamcmd_servers/citadel/egg-citadel--forged-with-fire.json

**Comment by lakilla21** [comment]
@parkervcp that is what I do. But for some reason its with this egg it shows the error. When I try one from your repo it works just fine.

**Comment by gOOvER** [comment]
> @lakilla21
> 
> right click the raw button here and save as. don't copy and paste the json.
> 
> https://github.com/parkervcp/eggs/blob/b0b1ca98e9ce76ef45f8ec4304ff778387f6c8b8/steamcmd_servers/citadel/egg-citadel--forged-with-fire.json

Funny thing is Parker, i also can't import it :/ i get the same error now.

I export it normal via Ptero

**Comment by gOOvER** [comment]
i take a look atm and try to figure out, whats wrong

**Comment by gOOvER** [comment]
Let's try again

**Pull request merged**
