### PR TITLE
Added Vintage Story

### PR DESCRIPTION
**Pull request by NgLoader**
### Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

### Informations:
Game: https://vintagestory.at
Tested: yes (about 4 hours with a friend)

Note: the latest version is not able to fetch! (you need a account to see the latest version but not to download it...)

### CODE REVIEW

**Comment by parkervcp** [comment]
Can you move that so it's alphabetical in the main readme please

**Comment by NgLoader** [comment]
like this?

**Comment by parkervcp** [comment]
after terraria before xonotic

**Comment by NgLoader** [comment]
Ok

**Comment by Homie20006** [comment]
Found a way to fetch the latest version without the need to login.
Do your thing if you want to shrink it down but for me it works well, try it from any bash ^^

```
URL="https://account.vintagestory.at/files/stable/"; LATEST=`curl -s4 $URL | awk -F 'vs_server' '{print $2}' | sed -r '/^\s*$/d' | sed -r 's/_//' | sed -r 's/"//' | sed -r 's/>//' | grep ".tar.gz$" | sort --version-sort | tail -n 1`; echo "version: $LATEST" && echo "url: ${URL}vs_server_$LATEST"
```

only the final download url in variable:
```
LATEST=`curl -s4 https://account.vintagestory.at/files/stable/ | awk -F 'vs_server' '{print $2}' | sed -r '/^\s*$/d' | sed -r 's/_//' | sed -r 's/"//' | sed -r 's/>//' | grep ".tar.gz$" | sort --version-sort | tail -n 1`; LATEST="https://account.vintagestory.at/files/stable/vs_server_$LATEST";
```

**Comment by NgLoader** [comment]
Thanks @Homie20006

**Pull request merged**
