### PR TITLE
Update Minecraft-Paper (Paper API V2)

### PR DESCRIPTION
**Pull request by Doc94**
The version of paper API used in this egg has been deprecated for the v2 of the API.
The v2 change the format of requests.
V2 API Docs: https://papermc.io/api/

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- Updated Paper API to v2
- Remove check-if for "latest" value in build because Paper API v2 dont support this
- Add more info about the build and version in echos
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by Doc94** [comment]
Notes:

- the v2 api dont support the latest value for get the build number.
- currently the line `BUILD_EXISTS=`curl -s https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION} | jq -r --arg BUILD ${BUILD_NUMBER} '.builds[] | contains($BUILD)' | grep true`` generate a error. (for this its a draft PR)

**Comment by kruton** [comment]
This  is using Alpine, but changed the script to use "bash" instead of "ash" and "apt" instead of "apk"  Does that work?

```
docker run --rm -it alpine:3.9 /bin/bash -c "apt update"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

**Comment by Doc94** [comment]
I fix the issue in:
`BUILD_EXISTS="curl -s https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION} | jq -r --arg BUILD ${BUILD_NUMBER} ".builds[] | contains($BUILD)" | grep true`
adding a toString for correctly check values.
`BUILD_EXISTS="curl -s https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION} | jq -r --arg BUILD ${BUILD_NUMBER} ".builds[] | tostring | contains($BUILD)" | grep true"`

Tested in panel.
image

**Comment by Doc94** [comment]
> This is using Alpine, but changed the script to use "bash" instead of "ash" and "apt" instead of "apk" Does that work?
> 
> ```
> docker run --rm -it alpine:3.9 /bin/bash -c "apt update"
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
> ```
> 
> vs
> 
> ```
> docker run --rm -it alpine:3.9 /bin/ash -c "apk update"
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> v3.9.6-120-g7ba7650582 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
> v3.9.6-114-ga7f52c345a [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
> OK: 9777 distinct packages available
> ```

I have a question about this.. in my case when export from my panel i get in instalation
`"container": "debian:buster-slim",
            "entrypoint": "bash"` (and its the default) in this PR only change the script nothing more.

**Comment by Software-Noob** [comment]
Your retrieval of the latest paper version is starting from the wrong end and would retrieve 1.8.8 as the latest which is false

Retrieve latest paper version using this:

`curl -s https://papermc.io/api/v2/projects/paper | jq -r '.versions' | jq -r '.[-1]'`

**Comment by Doc94** [comment]
Currently working egg with not issues in install.

**Pull request merged**
