### PR TITLE
Wurm unlimited/wurm unlimited

### PR DESCRIPTION
**Pull request by NgLoader**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [ ] Did you PR the nesessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

Requested: https://github.com/parkervcp/eggs/issues/160
Image: https://gitlab.com/_pterodactyl/images/tree/wurm-unlimited

### CODE REVIEW

**Comment by parkervcp** [comment]
Your image doesn't exist on gitlab anymore. @NgLoader

**Comment by NgLoader** [comment]
Its on gitlab [Link](https://gitlab.com/_pterodactyl/images/tree/wurm-unlimited)

**Comment by parkervcp** [comment]
So with some looking at the image and every thing.

why not put the `wurm.ini` in the repo and have it get pulled on install instead of on startup in the entrypoint.

In fact many of the things you install during the startup in the entrypoint should be in the install script.

**Comment by NgLoader** [comment]
Okay thanks, I commit some changes the next days :)

**Comment by NgLoader** [comment]
Is it now better?

**Comment by NgLoader** [comment]
@parkervcp Is it now better?

**Comment by parkervcp** [comment]
@NgLoader Does this require java to run?

I am going to say no as you still use a custom image where you are doing things there like keeping the start command in the image.

**Comment by NgLoader** [comment]
Its more user friendly if you only have to change the config and there's no need to "rebuild" it every time.

**Comment by parkervcp** [comment]
It's not more user friendly. If your image gets out of date and the start command changes they need to wait on a rebuild of your image. This is why we have a configurable start command and variables.

If you change a variable you still rebuild the container so either way you are wasting time here.

This is also why I ask for a generic image and not some custom thing people are hosting themselves.

**Pull request closed without merging**
