### PR TITLE
add openrct 2

### LINKED ISSUE #381: Game Request: OpenRCT2
Service: OpenRCT2

Does this expand an already existing service: Y (Tycoon Games)

Link to game: https://openrct2.org/

Links for server downloads: https://openrct2.org/downloads

Links for install steps/docs: https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer

### PR DESCRIPTION
**Pull request by parkervcp**
resolves #381

### All Submissions:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:
1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by MrMelon54** [comment]
Awesome 🚀

**Comment by MrMelon54** [comment]
Hi are there any updates for when this will be finished?

**Comment by koutsie** [comment]
+1 any news?

**Comment by MrMelon54** [comment]
Why was this issue closed? It hasn't been resolved as it?

**Comment by Software-Noob** [comment]
> Why was this issue closed? It hasn't been resolved as it?

It's not an issue. It's a pull request that has been superseeded by another one

**Comment by MrMelon54** [comment]
oh um yea it is a PR lol

ok thx

**Pull request closed without merging**
