### PR TITLE
Add DDRaceNetwork

### LINKED ISSUE #2273: [Egg Request]: DDRaceNetwork
### Does this expand an already existing service

Yes

### Link to a game or software

https://ddnet.org/

### Links for the download

https://ddnet.org/downloads/

### Links for the install docs

https://forum.ddnet.org/viewtopic.php?t=5095 (this is a windows version, but the linux version has the same files so it's almost the exact process)

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
# Description
In this PR I've added an egg for DDRaceNetwork server.

closes #2273 

There are still 2 features i need to implement, but i'll probably need some help with it since i'm not sure how to do it.
## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [X] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by diedyesterdaywashere** [comment]
so i only have 2 things that are in need to be fixed...

* "Configuration Files" field in the egg settings, i wasnt sure which settings are needed to be tracked
* "failed to open myServerconfig.cfg". I already know what's the cause of it, just need help with implementing it

**Comment by diedyesterdaywashere** [comment]
I'll probably fix the second problem when i wake up tmrw

**Comment by diedyesterdaywashere** [comment]
so the egg is kinda ready now, feel free to give some feedback if needed

**Comment by QuintenQVD0** [comment]
I added some extra features and remove some commands, as tar has a flag to skip 1 folder.
Also, the port is now automatically set

**Comment by diedyesterdaywashere** [comment]
alright, thanks

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you.

**Pull request merged**
