### PR TITLE
Add Sven Co-op

### PR DESCRIPTION
**Pull request by coolnickname**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image? No
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by parkervcp** [comment]
@coolnickname It looks like you missed the VAC port on the README. Can you please add that please? 

default is 26900

**Comment by mclucario** [comment]
Is this gonna get merged someday?

**Comment by coolnickname** [comment]
@mclucario I still need to add the VAC port, but you could just download the egg yourself from my repo and install it since it's functional.

**Comment by parkervcp** [comment]
i mean the VAC port just needs to be in the readme.

**Comment by mclucario** [comment]
Thank you

**Comment by mclucario** [comment]
grafik
It doesn't seem to run for me.

**Pull request merged**
