### PR TITLE
Add TerraTech Worlds egg

### PR DESCRIPTION
**Pull request by durzo**
# Description

Add egg for steamcmd game: TerraTech Worlds

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@durzo What is the name of the log file located in  /home/container/TT2/Saved/Logs/ ?

**Comment by durzo** [comment]
TT2.log, but looks like its getting rotated out, i now have files named:
```
TT2-backup-2024.03.23-11.54.58.log
TT2-backup-2024.03.23-11.56.09.log
TT2.log
```

I guess depending how they are being rotated, tailing one might not always be reading the latest.

**Comment by QuintenQVD0** [comment]
> TT2.log

I will make it work ;)

**Comment by QuintenQVD0** [comment]
@durzo I changed some things in the egg. can you please re-test it (a fresh server as the startup and insall logic changed and their now will be console output)

And can you fill in the README template with the port? and is there no need for a query port?

**Comment by durzo** [comment]
Game only has 1 port, have to do IRL things but will update & test in a few hours. thanks

**Comment by durzo** [comment]
README.md updated, fresh server installed.
Console output on server start (trimmed to near end):
```
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2533070' already up to date.
:/home/container$ rm /home/container/TT2/Saved/Logs/TT2.log; proton run ./TT2/Binaries/Win64/TT2Server-Win64-Shipping.exe -log & TTW_PID=$!; tail -c0 -F /home/container/TT2/Saved/Logs/TT2.log --pid=$TTW_PID
tail: cannot open '/home/container/TT2/Saved/Logs/TT2.log' for reading: No such file or directory
esync: up and running.
tail: '/home/container/TT2/Saved/Logs/TT2.log' has appeared;  following new file
Log file open, 03/23/24 15:30:40
LogOnline: OSS: Created online subsystem instance for: EOS
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for module [EOS]
[2024.03.23-15.30.40:365][  0]LogMemory: Platform Memory Stats for WindowsServer
[2024.03.23-15.30.40:365][  0]LogMemory: Process Physical Memory: 219.80 MB used, 219.80 MB peak
[2024.03.23-15.30.40:365][  0]LogMemory: Process Virtual Memory: 195.84 MB used, 195.84 MB peak
[2024.03.23-15.30.40:365][  0]LogMemory: Physical Memory: 699.40 MB used,  23357.68 MB free, 24057.08 MB total
[2024.03.23-15.30.40:366][  0]LogMemory: Virtual Memory: 699.41 MB used,  23357.68 MB free, 24057.09 MB total
[2024.03.23-15.30.40:671][  0]LogNetVersion: TT2 1.0.0, NetCL: 0, EngineNetVer: 30, GameNetVer: 0 (Checksum: 151539014)
[2024.03.23-15.30.41:064][  0]LogNetVersion: Set ProjectVersion to 334ca8b90d_2024-03-22_20-31-31. Version Checksum will be recalculated on next use.
```

Game client connects and all seems to be working.

**Comment by durzo** [comment]
There may be a need to add more settings at a later date, the game only launched into early access on Friday and there is little to no documentation on server configuration options.

Once installed, aside from the root level `dedicated_server_config.json` file, the game dirs look a lot like Ark SA/AS in that there is a folder named `TT2/Saved/Config/WindowsServer` which contains a familiar `GameUserSettings.ini` although I have yet to test anything in this file.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
