### PR TITLE
fix:  ftb modpacksch server installation script

### PR DESCRIPTION
**Pull request by kylhuk**
# Description

Previous discussion at #2093 

Fixed the installation script so FTB modpacks can be used again. Works for minecraft-pre-1.17 and -post-1.17.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]
You always have to make the changes in the panel and export the egg and fully replace the egg not just what you want

**Comment by parkervcp** [comment]
@kylhuk They are asking that you use the panel to export the egg.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 I just modified the JSON so it works. Could you please tell me what exactly isn't working with my changes?

That is not allowed. You edit the install script on the imported egg, press export then you get a updated .json and you replace the whole .json here with the .json you jsut exported

**Comment by QuintenQVD0** [comment]
What is so difficult about this? You must always update the whole .json file when you make a PR. and a startup cmd can not be a user editable script

**Comment by parkervcp** [comment]
@kylhuk I didn't check if you had exported the egg from the panel. I checked the script changes first. That was my primary concern. Quintens concerns are still valid as it guarantees that the format is correct.

As for your fix. I see you are just updating the start script. That is fine, but the main start command for the server is staying as it is. Please make the start changes a separate function with a check the file exists before running the.

**Comment by parkervcp** [comment]
@kylhuk I am sorry this was a negative experience. I realized that I didn't explain fully why I closed the other PR. In our discussion I thought I got the point across. As for using the start script as the start command, that is a security issue that I should have also called out a long time ago in the rules.

I am updating the CONTRIBUTING.md and the pull request template right now as a response of this. I do appreciate that you were looking for a way to handle the issue with the egg.

**Pull request closed without merging**
