### PR TITLE
icarus hotfix for config

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

changes:
- only set wine staging as a image option
- move `export HOME=/mnt/server` from line 6 to 16
- add config download as it is buged atm
afbeelding
- add extra variables for wine to hide some fixme + tell wine it is a 64 bit install + a variable so wine find the config and correctly maps it to z:\
- add corefonts to winetricks to fix console text

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by gOOvER — APPROVED** [review]
Egg and changes work for me. I see the server in Serverlist:

Icarus-Win64-Shipping_NO9HXHPFfK

And i can connect:

```
LogConnectedPlayers: Display: FinaliseConnectedPlayerInitialisation - PlayerCharacterID: 76561197962941250_1
[2022.12.10-11.19.07:476][861]LogConnectedPlayers: Display: FinaliseConnectedPlayerInitialisation - PlayerCharacterID: 76561197962941250_1
LogConnectedPlayers: Display: FinaliseConnectedPlayerInitialisation - PlayerName: gOOvER|OldNoobTV
[2022.12.10-11.19.07:477][861]LogConnectedPlayers: Display: FinaliseConnectedPlayerInitialisation - PlayerName: gOOvER|OldNoobTV
LogIcarusGameModeSurvival: Display: OnConnectedPlayerInitialised - PlayerCharacterID: 76561197962941250_1
[2022.12.10-11.19.07:477][861]LogIcarusGameModeSurvival: Display: OnConnectedPlayerInitialised - PlayerCharacterID: 76561197962941250_1
LogIcarusGameModeSurvival: Display: InitialisePlayerForProspect player not restored from database
[2022.12.10-11.19.07:478][861]LogIcarusGameModeSurvival: Display: InitialisePlayerForProspect player not restored from database
LogIcarusGameModeSurvival: Display: InitialisePlayerForProspect starting new player initialisation
[2022.12.10-11.19.07:479][861]LogIcarusGameModeSurvival: Display: InitialisePlayerForProspect starting new player initialisation
[2022.12.10-11.19.07:479][861]LogIcarusGameModeSurvival: Using D_ProspectList defined spawn zone (0)
[2022.12.10-11.19.07:479][861]LogIcarusGameModeSurvival: Custom selected spawn point was found (0). Using this as override instead of D_ProspectList defined zon
e
LogWeatherController: Display: gOOvER|OldNoobTV just entered new biome: Styx_TheGreatRiver
[2022.12.10-11.19.07:486][861]LogWeatherController: Display: gOOvER|OldNoobTV just entered new biome: Styx_TheGreatRiver
LogLocalSessionSubsystem: Display: UpdateActiveProspectInfo - ProspectID: goover test | ProspectDTKey: OpenWorld_Styx
[2022.12.10-11.19.07:487][861]LogLocalSessionSubsystem: Display: UpdateActiveProspectInfo - ProspectID: goover test | ProspectDTKey: OpenWorld_Styx
```

**Comment by gOOvER** [comment]
@QuintenQVD0  please4 fix this

move export HOME=/mnt/server from line 6 to 16

It ends everytime in an error, because $HOME is not defined. Test it wit 2 other servers and when its on beginning there is no Error. I dont understand, why this was moved down; this can not work;

Or better use Parkers Script without modifying it

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 please fix this: `move export HOME=/mnt/server from line 6 to 16`
> 
> It ends everytime in an error, because $HOME is not defined. Tested it with 2 other servers and when its on beginning there is no Error. I dont understand, why this was moved down; this can not work;
> 
> Or better use Parkers Script without modifying it

$HOME is normaly not used anymore in the egg

**Comment by gOOvER** [comment]
i see no commit for it

**Comment by QuintenQVD0** [comment]
> i see no commit for it

I did not push it, ....

**Comment by QuintenQVD0** [comment]
Now it should be the default script, exept that I removed the beta and validate flag of steamcmd

**Comment by QuintenQVD0** [comment]
> i see no commit for it
> 
> Edit:
> 
> is it in
> 
> switch download config to offical github repo?

The first yes but I forgot it still 2 times , so I just moved to almost the full script of github

**Review by gOOvER — APPROVED** [review]

**Review by gOOvER — APPROVED** [review]
Now the error is gone:

```
steam user is not set.
Using anonymous user.
steamcmd.sh
linux32/steamcmd
linux32/steamerrorreporter
linux32/libstdc++.so.6
linux32/crashhandler.so
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 57385 KB)...
[  0%] Downloading update (0 of 57385 KB)...
[  0%] Downloading update (0 of 57385 KB)...
[  0%] Downloading update (2661 of 57385 KB)...
[  4%] Downloading update (6665 of 57385 KB)...
[ 11%] Downloading update (9142 of 57385 KB)...
[ 15%] Downloading update (11613 of 57385 KB)...
[ 20%] Downloading update (14339 of 57385 KB)...
[ 24%] Downloading update (16816 of 57385 KB)...
[ 29%] Downloading update (19287 of 57385 KB)...
[ 33%] Downloading update (22013 of 57385 KB)...
[ 38%] Downloading update (24485 of 57385 KB)...
[ 42%] Downloading update (26233 of 57385 KB)...
[ 45%] Downloading update (28959 of 57385 KB)...
[ 50%] Downloading update (31426 of 57385 KB)...
[ 54%] Downloading update (33897 of 57385 KB)...
[ 59%] Downloading update (36624 of 57385 KB)...
[ 63%] Downloading update (39099 of 57385 KB)...
[ 68%] Downloading update (40856 of 57385 KB)...
[ 71%] Downloading update (42101 of 57385 KB)...
[ 73%] Downloading update (43345 of 57385 KB)...
[ 75%] Downloading update (44714 of 57385 KB)...
[ 77%] Downloading update (45958 of 57385 KB)...
[ 80%] Downloading update (47327 of 57385 KB)...
[ 82%] Downloading update (48572 of 57385 KB)...
[ 84%] Downloading update (49816 of 57385 KB)...
[ 86%] Downloading update (51185 of 57385 KB)...
[ 89%] Downloading update (52429 of 57385 KB)...
[ 91%] Downloading update (53670 of 57385 KB)...
[ 93%] Downloading update (55043 of 57385 KB)...
[ 95%] Downloading update (56287 of 57385 KB)...
[ 98%] Downloading update (57385 of 57385 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
```

**Comment by BolverBlitz** [comment]
"add config download as it is buged atm" i would be interested where those bugs show?
Downloading the config would enable setting variables for player count & passwort, but other than that where are bugs?

**Comment by gOOvER** [comment]
> "add config download as it is buged atm" i would be interested where those bugs show? Downloading the config would enable setting variables for player count & passwort, but other than that where are bugs?

the server crash, when no config is located in path.

**Comment by BolverBlitz** [comment]
I did read them, and thats why i assumed its fine the way it was. The test deploys from yesterday also still run. One ran out of memory though and one dosn´t support the network it runs on.
grafik
Looking at icarus, 6 out of 7 (possible) also seem fine Join, choose mission etc
grafik

**Comment by gOOvER** [comment]
you need 6gb+ RAM for every server. Did you read the notice for the ServerSettings.ini in their wiki?

**Pull request merged**
