### PR TITLE
Update egg-risk-of-rain2.json to allow SteamAPI being correctly loaded by installing APP 1007 and copy the *64.so files

### PR DESCRIPTION
**Pull request by KenRen98**
# Description

Fix Dependency and ServerList not visiable in ServerList problem (Added *64.so by installing 1007 to allow steamAPI being correctly loaded)
## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by gOOvER** [comment]
cant confirm, that it work. the: `Loading Steam API...dlmopen steamservice.so failed: steamservice.so` error can be ignored

**Comment by gOOvER** [comment]
@KenRen98 - I updated RoR2, because you missed a lot of things, like the serverport, where was not set in config and a lot of other things

**Comment by KenRen98** [comment]
@gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.

**Comment by QuintenQVD0** [comment]
> @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.

The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.

**Comment by KenRen98** [comment]
> > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> 
> The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.

well I just tested his build, which rolls out errors.

`[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ 服务器运行状态更新为: starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest 
Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.7
Current timezone: Etc/UTC
wine-8.0.1
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1689642531
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '1180760' already up to date.
First launch will throw some errors. Ignore them
Installing mono
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: could not load kernel32.dll, status c0000135
:/home/container$ xvfb-run wine ./"Risk of Rain 2.exe"
wine: could not load kernel32.dll, status c0000135
container@pterodactyl~ 服务器运行状态更新为: offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
`

**Comment by QuintenQVD0** [comment]
> > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > 
> > 
> > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> 
> well I just tested his build, which rolls out errors.
> 
> `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `

your install faild or something and your test is not valid as I see Chinese messages so you modified the panel in some way and we have no idea what you have done

**Comment by KenRen98** [comment]
> > > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > > 
> > > 
> > > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> > 
> > 
> > well I just tested his build, which rolls out errors.
> > `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `
> 
> your install faild or something and your test is not valid as I see Chinese messages so you modified the panel in some way and we have no idea what you have done

Its the official Chinese version of the Panel so its the same as the English one no more than just translation, Anyway, never mind, could be a config error, just reinstalled and it works.

**Comment by QuintenQVD0** [comment]
> > > > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > > > 
> > > > 
> > > > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> > > 
> > > 
> > > well I just tested his build, which rolls out errors.
> > > `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `
> > 
> > 
> > your install faild or something and your test is not valid as I see Chinese messages so you modified the panel in some way and we have no idea what you have done
> 
> Its the official Chinese version of the Panel so its the same as the English one no more than just translation, Anyway, never mind, could be a config error, just reinstalled and it works.

There is no "official Chinese version" but I am testing it myself rn

**Comment by QuintenQVD0** [comment]
I am closing this in favor or https://github.com/parkervcp/eggs/pull/2380 as it does the same but also rewrites the egg.

I still want to thank you for your time and finding this fix!

**Comment by KenRen98** [comment]
😅we need more crowdsourcing , debug is painful.
________________________________
发件人: Quinten ***@***.***>
发送时间: 2023年7月22日 5:33
收件人: parkervcp/eggs ***@***.***>
抄送: Dexuan Ren ***@***.***>; Mention ***@***.***>
主题: Re: [parkervcp/eggs] Update egg-risk-of-rain2.json to allow SteamAPI being correctly loaded by installing APP 1007 and copy the *64.so files (PR #2379)


I am closing this in favor or #2380<https://github.com/parkervcp/eggs/pull/2380> as it does the same but also rewrites the egg.

I still want to thank you for your time and finding this fix!

**Comment by gOOvER** [comment]
> > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > 
> > 
> > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> 
> well I just tested his build, which rolls out errors.
> 
> `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `

this error indicate, that you missed to delete the .wine folder before reinstalling ;)

**Comment by KenRen98** [comment]
> > > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > > 
> > > 
> > > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> > 
> > 
> > well I just tested his build, which rolls out errors.
> > `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `
> 
> this error indicate, that you missed to delete the .wine folder before reinstalling ;)

Seems like it, but it worked, thanks bro. Will be testing more eggs and help with debugging.😅

**Comment by KenRen98** [comment]
> > > > @gOOvER Well if you can read its clearly stated update for fixing the SteamAPI not loaded, and the game not listed in server list. It is just simple modification of the original one, so dont blame me on the missing component.
> > > 
> > > 
> > > The egg needed a full rewrite as this docker image is way to old and not update anymore. He rewrote the whole egg and added what you did.
> > 
> > 
> > well I just tested his build, which rolls out errors.
> > `[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ 服务器运行状态更新为: starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/yolks Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_latest Digest: sha256:471d3ecbe70b24123951642fa4fa72d778b80b351847272e964868b0ba9a7366 [Pterodactyl Daemon]: Finished pulling Docker container image Running on Debian 11.7 Current timezone: Etc/UTC wine-8.0.1 steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1689642531 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK "@sSteamCmdForcePlatformType" = "windows" Success! App '1180760' already up to date. First launch will throw some errors. Ignore them Installing mono _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. wine: could not load kernel32.dll, status c0000135 :/home/container$ xvfb-run wine ./"Risk of Rain 2.exe" wine: could not load kernel32.dll, status c0000135 container@pterodactyl~ 服务器运行状态更新为: offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 53 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago. `
> 
> this error indicate, that you missed to delete the .wine folder before reinstalling ;)

BTW, see if you can add Server Tags and Game Mode option in GUI, I didnt find proper documentation about the value of parameters. It would be good if you can add them too.

**Comment by gOOvER** [comment]
> 
> BTW, see if you can add Server Tags and Game Mode option in GUI, I didnt find proper documentation about the value of parameters. It would be good if you can add them too.

i'll take a look into it tomorrow

**Pull request closed without merging**
