### PR TITLE
Ree6 Egg update

### PR DESCRIPTION
**Pull request by DxsSucuk**
# Description
This PR aims to update the Ree6 Bot Egg to support the newer V3 version.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by DxsSucuk** [comment]
I am confused aswell, since as far as I remember the commits got merge, but github dos not think that apperantly

**Comment by DxsSucuk** [comment]
But as Github says it is up to date.

**Comment by QuintenQVD0** [comment]
> I am confused aswell, since as far as I remember the commits got merge, but github dos not think that apperantly

your fork of this repo was not at the same commit when you stared adding those + the guidelines sas to never use the master branch but always create a seperate branch based of the current master

**Comment by DxsSucuk** [comment]
Well thats sucks.
I could just reset the fork and stash my changes, make a new branch and then try again

**Comment by QuintenQVD0** [comment]
my advise if you want to make changes to a current egg. go in this repo to the file that you first are going to edit, then hit the edit icon , make you changes, and it will force you to create a new branch, that branch will be added to your local fork and will be up to date

**Comment by QuintenQVD0** [comment]
> Well thats sucks. I could just reset the fork and stash my changes, make a new branch and then try again

it is fine for now, I just squash merge it then you can not see it if I have confiremed that it is working

**Comment by DxsSucuk** [comment]
> my advise if you want to make changes to a current egg. go in this repo to the file that you first are going to edit, then hit the edit icon , make you changes, and it will force you to create a new branch, that branch will be added to your local fork and will be up to date

Ooooh didn't know this well great to know for next time!

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you

**Pull request merged**
