### PR TITLE
Add ATLAS server

### LINKED ISSUE #512: Atlas Game
Service: Atlas

Does this expand an already existing service: N

Link to game: https://store.steampowered.com/app/834910/ATLAS/

Links for server downloads: https://atlas.gamepedia.com/Server_setup#Downloads

Links for install steps/docs: https://atlas.gamepedia.com/Server_setup#Downloads

Steam-Server-ID: 1006030

I tried around using the ark egg and changed some settings in the startup command, but I can't get this running.
Also on cmd based steamcmd, I didn't get the ShooterGame binary, maybe I'm just stupid :D

### PR DESCRIPTION
**Pull request by parkervcp**
resolves #512

### All Submissions:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:
1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by gOOvER** [comment]
I get following errors on startup:

```
/entrypoint.sh: line 36: trap: -e: invalid signal specification
/entrypoint.sh: line 36: trap: "ctrl-c: invalid signal specification
/entrypoint.sh: line 36: trap: caught": invalid signal specification
```
`/entrypoint.sh: line 36:    44 Segmentation fault      (core dumped) ./ShooterGameServer ${SERVER_MAP}?listen?SessionName="${SESSION_NAME}"?ServerPassword=${GAME_PASSWORD}?ServerAdminPassword=${ADMIN_PASSWORD}?Port=${SERVER_PORT}?RCONPort=${RCON_PORT}?QueryPort=${QUERY_PORT}?RCONEnabled=${ENABLE_RCON}$( [ "${BATTLE_EYE}" == "0" ] && printf %s "?-NoBattlEye" ) -server -log`

**Comment by parkervcp** [comment]
Pretty sure I know the issue and will look at it.

**Comment by Gizmo0320** [comment]
I am having this same issue
`/entrypoint.sh: line 36:    49 Segmentation fault`

**Comment by KRServersDE** [comment]
any updates?

**Comment by parkervcp** [comment]
I am closing this out but the files will still be around.

**Comment by cody-rees** [comment]
> I am closing this out but the files will still be around.

Also getting segmentation fault errors. Any updates on this specific issue ?

**Comment by parkervcp** [comment]
I haven't looked at the egg or server since I opened this in the first place. I am not looking into segfaults.

**Pull request closed without merging**
