### PR TITLE
Fix 301 Moved for Gyser-Spigot.jar download

### PR DESCRIPTION
**Pull request by computersandstuff**
# Description

The download for the Gyser plugin instead saves a 301 permanent redirect body to the .jar file in the plugins folder, rather than the actual plugin itself being saved. I changed to the updated url (https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/build/libs/Geyser-Spigot.jar)

I tested the egg and the server started successfully with the correct plugin being loaded.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]
You need to use the panel export feature and update the whole egg not one part

**Comment by QuintenQVD0** [comment]
also, please add something like `echo "install finished"` to the end of the install script

**Comment by computersandstuff** [comment]
Ah, I see now. I exported the egg from my instance and there are some updated lines with it. I also added that echo command at the end.

**Comment by QuintenQVD0** [comment]
Thank you!

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
LGTM!

**Pull request merged**
