### PR TITLE
Update beamMP server egg

### PR DESCRIPTION
**Pull request by O1LER**
# Description

Added variables for server description and chat toggle
Updated variable "private" to accept only "true" or "false" string
Updated variable "max cars" to accept numbers up to 10

## Checklist for all submissions

* [X ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X ] Have you tested and reviewed your changes with confidence that everything works?
* [ X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
you will need to edit the install script to when making a config file so it addes those lines by default

**Comment by O1LER** [comment]
I see. I had no issue with it when testing the changes, since the beamMP server binary creates the serverConfig.toml itself upon first startup. So i guess the install script would not need to create the same file just prior. I will look into it, thanks for the hint

**Comment by QuintenQVD0** [comment]
> I see. I had no issue with it when testing the changes, since the beamMP server binary creates the serverConfig.toml itself upon first startup. So i guess the install script would not need to create the same file just prior. I will look into it, thanks for the hint

You will have to manual add it to the install script as the configuration parser will prevent the server bin from writing its config as it is still editing it.

**Comment by O1LER** [comment]
Updated the install script section by adding the LogChat variable
Corrected a typo (lower/upper case) in config file section, renamed chat logging (used to be called chat toggle)
Used same default description as beamMP

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
