### PR TITLE
Update Valheim Plus, Valheim Vanilla and main readme

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### Changelog for this PR:

- Updated Valheim Plus to use ghcr Images
- Added update of BepInex to latest version on reinstall in ValheimPlus egg
- Updated Valheim Vanilla egg to use new ghcr images
- fixed missing link in Readme

### CODE REVIEW

**Comment by Software-Noob** [comment]
This fails to start for me, while the old one works fine. Did something change in the bepinex regarding steam client?

```
[Pterodactyl Daemon]: Finished pulling Docker container image
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
Setting breakpad minidump AppID = 892970
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
```

**Comment by gOOvER** [comment]
@Software-Noob i check that. for me it works when in PR it

**Comment by gOOvER** [comment]
I set this to DRAFT, because i need to figure out, why this happens. BepInex didn't change anything.

**Comment by hz-ad** [comment]
Attached is a working version, with explicit export paths, and some other stuff that I don't remember the changes for. Customers say this version works. Its not a great solution or a nice one, but it does indeed work for those that are having issues. May even be able to make it work by just removing the reference to "./" in the paths or the quotes in the bash export statements. Who knows..... But this one works. 

Also I dont think i took the latest version with the ghcr images....

A gentle reminder to people that you will likely to change/update the affected container start command (reinstall isn't enough). to reflect the changed startup. Sorry for the zip/lazy attachment instead of a PR. 
[egg-valheim-plus-mod-host-e-z.zip](https://github.com/parkervcp/eggs/files/7631786/egg-valheim-plus-mod-host-e-z.zip)

**Comment by gOOvER** [comment]
> Attached is a working version, with explicit export paths, and some other stuff that I don't remember the changes for. Customers say this version works. Its not a great solution or a nice one, but it does indeed work for those that are having issues. May even be able to make it work by just removing the reference to "./" in the paths or the quotes in the bash export statements. Who knows..... But this one works.
> 
> Also I dont think i took the latest version with the ghcr images....
> 
> A gentle reminder to people that you will likely to change/update the affected container start command (reinstall isn't enough). to reflect the changed startup. Sorry for the zip/lazy attachment instead of a PR. [egg-valheim-plus-mod-host-e-z.zip](https://github.com/parkervcp/eggs/files/7631786/egg-valheim-plus-mod-host-e-z.zip)

I think, the startup is notr the problem, because the error happens, when entrypoint.sh runs on autoupdate. 

```
[Pterodactyl Daemon]: Finished pulling Docker container image
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
Setting breakpad minidump AppID = 892970
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
```

**Pull request closed without merging**
