### PR TITLE
Added Starbound

### PR DESCRIPTION
**Pull request by rouing**
Signed-off-by: Rouing <rouing@waterfallnetwork.net>

### CODE REVIEW

**Comment by parkervcp** [comment]
I have made major changes to how things are organized in the repo. Can you update to match please. I would put this under source servers as it needs steamcmd to install.

Is there a way to not use user/pass auth and use a token to install?

**Comment by rouing** [comment]
Currently, no there is not. I will reorg the PR

**Comment by rouing** [comment]
If you do happen to find a way to bypass login, please tell me. It is the most ANNOYING thing ever.

**Comment by parkervcp** [comment]
Can you add to the main README and then the local server README. Please check the warband to get a good idea.

**Comment by rouing** [comment]
Ive moved away from Pterodactyl fully. This is abandoned by me. If you want you can take over this PR.

**Pull request closed without merging**
