### PR TITLE
Add Umod Servers folder - Add Valheim to Umod Servers (Draft)

### PR DESCRIPTION
**Pull request by J-Pster**
### All Submissions:

* [Yes] Have you followed the guidelines in our Contributing document?
* [Yes, and have] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [No, sorry I misunderstood, but I already have another branch here to publish my changes.] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [Yes] Does your submission pass tests (server is connectable)?
2. [Yes] Does your server use a custom docker image?
    * [Yes] Have you tried to use a generic image?
    * [Yes] Did you PR the necessary changes to make it work?
3. [Yes] Have you added the server to the main README.md?
4. [Yes] Have you added a unique README.md for the server you are adding?

**To Parketvcp:**
I started working on an EGG for Valheim when I bought the game, a week ago, I exposed my work on GitHub on the 19/02 a few days later I divulged my project on Pterodactyl's discord and uMod's discord, I was working on the project and perfecting it to only later make a PR, but I see that this was my mistake, another user whose name you know what it is, created on the 26/02 a PR with the same idea as my project, this user talked to me in the Pterodactyl discord, being arrogant and saying that he had a project that worked, in the GitHub of this user, there was (but he deleted) a Fork of my project a few days ago, I believe that this user, got my repository, modified (and congratulations for his work) and made an AutoUpdate, however, removed any credit that I had from the project.

The evidence of what I said here, is saved in messages, such as the message I sent to you, Parkervcp, on Feb 21st.
And also the messages from Software-Noob talking to me at Pterodactyl's discord.

My intention then is to take my now-completed project, merge parts of the Software-Noob's project, credit both, and then, make the PR.

Read this comment: https://github.com/parkervcp/eggs/pull/1010#issuecomment-786911853

**To all:**
Everyone who wants to add, edit or remove parts of what has been done here WILL be recognized, and WILL get the credit.

### CODE REVIEW

**Comment by CastBlacKing** [comment]
I believe that: Softwarenoob#5650 and gOOvER#9999 are the same person.

Why?
See for yourself:
Screenshot_508

**Comment by gOOvER** [comment]
i never forked and never do a PR of umod. stop that. 

and no, both are not the same

**Comment by CastBlacKing** [comment]
> 
> 
> i never forked and never do a PR of umod. stop that.
> 
> and no, both are not the same

It's okay gOOvER, I just want my credit, for what I did.
I was never angry with you, but you were always arrogant with me.

But if parkervcp doesn't want it, that's fine.
At least I tried, and also learned a lot about Pterodactyl, about Dockers, about Bash, about Linux.

**Comment by gOOvER** [comment]
> > i never forked and never do a PR of umod. stop that.
> > and no, both are not the same
> 
> It's okay gOOvER, I just want my credit, for what I did.
> I was never angry with you, but you were always arrogant with me.
> 
> But if parkervcp doesn't want it, that's fine.
> At least I tried, and also learned a lot about Pterodactyl, about Dockers, about Bash, about Linux.

@parkervcp please remove these Screeeshots. This have nothing to do with this PR

**Comment by gOOvER** [comment]
> I believe that: Softwarenoob#5650 and gOOvER#9999 are the same person.
> 
> Why?
> See for yourself:
> Screenshot_508
> 
> His GitHub account name is Software-Noob, there is a user named: Softwarenoob#5650, when I said that gOOvER#9999 copied my repository, he replied:
> i copied yours? Ohh the uMod thing 😄 Yeah, i use it for testing but your egg was totally wrong 😄 btw thats the sense of Github :slight_smile:
> 
> But I don't blame him, and I'm not angry with him either, I give him credit for what he did.
> I just want to give myself credit, for spending nights trying to do this and trying to learn, I tried calling other developers to help, I wasted hours learning how to work with Pterodactyl...

Remove that or i open a ticket to Github Team, thet they remove that

**Comment by gOOvER** [comment]
@CastBlacKing see https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md

Step 3 ;)

**Comment by CastBlacKing** [comment]
I will only remove it if Parkervcp asks me to, I'm only providing proof and I have many other pictures here, you can do whatever you want, say it's not you, ask GitHub to remove my pictures, ban my account, it doesn't matter.

I am struggling for days to learn and get this EGG done, and yes, I am mature enough to tell you, CONGRATULATIONS YOU DID A GOOD JOB CREATING THE AUTOUPDATE, THANK YOU. But remove my credits, hide me, silence me? No.

I will not argue with you, this PR is not for that, **the decision is in Parkervcp's hands**, so, parker, if you want I remove, I delete what I did, I delete even my repository if YOU want, the decision is yours

**Comment by gOOvER** [comment]
> I will only remove it if Parkervcp asks me to, I'm only providing proof and I have many other pictures here, you can do whatever you want, say it's not you, ask GitHub to remove my pictures, ban my account, it doesn't matter.
> 
> I am struggling for days to learn and get this EGG done, and yes, I am mature enough to tell you, CONGRATULATIONS YOU DID A GOOD JOB CREATING THE AUTOUPDATE, THANK YOU. But remove my credits, hide me, silence me? No.
> 
> I will not argue with you, this PR is not for that, **the decision is in Parkervcp's hands**, so, parker, if you want I remove, I delete what I did, I delete even my repository if YOU want, the decision is yours

Allready reported to Github Abuse Team ;)

**Comment by Software-Noob** [comment]
> I believe that: Softwarenoob#5650 and gOOvER#9999 are the same person.
> 
> Why?
> See for yourself:
> Screenshot_508
> 
> His GitHub account name is Software-Noob, there is a user named: Softwarenoob#5650, when I said that gOOvER#9999 copied my repository, he replied:
> i copied yours? Ohh the uMod thing :smile: Yeah, i use it for testing but your egg was totally wrong :smile: btw thats the sense of Github :slight_smile:
> 
> But I don't blame him, and I'm not angry with him either, I give him credit for what he did.
> I just want to give myself credit, for spending nights trying to do this and trying to learn, I tried calling other developers to help, I wasted hours learning how to work with Pterodactyl...

Please don't bring me into some nonsense drama. I have no idea what personal issues you are having with others, but leave me out of it.

**Review by gOOvER — CHANGES_REQUESTED** [review]
You use your Master and don't use an Branch

See: https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md
-> Step 3

**Comment by gOOvER** [comment]
Can be closed, because he open a new PR #1010

**Pull request closed without merging**
