### PR TITLE
Added nodejs 18 support to the code server

### PR DESCRIPTION
**Pull request by BestRazer**
# Description

The Code-server egg only supports node versions up to 17. I simply added 18.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You did not read the checklist. This is not edited and exported from a panel.

**Comment by gOOvER** [comment]
feel free to add a PR

**Comment by gOOvER** [comment]
Egg is not exported from panel

**Review by parkervcp — APPROVED** [review]

**Review by parkervcp — CHANGES_REQUESTED** [review]
Please use the panel to export the egg.

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
