### PR TITLE
[V Rising (Vanilla)] Secrets of Gloomrot Update

### PR DESCRIPTION
**Pull request by lilkingjr1**
# Description

- Adds support for new settings in ServerHostSettings.json, including: ListOnSteam, ListOnEOS, CompressSaveFiles, and API Enabled.
- Changes stop command to accommodate latest Wings version by force-stopping the server. This is not ideal, but utilizing the current image with `eval` OR `exec` (I tested it) still does not seem to pass the SIGINT correctly (or maybe it does and WINE just doesn't listen; I don't know).
- Improved [SYSTEM] startup parameters.
- Updated the install script to check for successful installation and use the default ServerHostSettings.json that ships with the server.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Review by gOOvER — APPROVED** [review]
Egg works like charm.

- [x] Server install without errors
- [ ] Server starts
- [ ] Server visible in Serverlist
- [ ] can connect to the server

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by AeonLucid** [comment]
I noticed you added the option `API.Enabled`. Do you have some information on what this enables?

**Comment by lilkingjr1** [comment]
Not really... I just saw that it was a new option added to the config file.

Closest thing I could find is this:
https://www.reddit.com/r/vrising/comments/ux1a4v/public_api_update_for_vrising/

**Pull request merged**
