### PR TITLE
Add Sinusbot

### PR DESCRIPTION
**Pull request by ki2007**
This is my first take at an custom egg.

Feedback is more than welcome.
Sometime this week I try to streamline the docker image and look if it is possible to use alpine.

Just wanted to get it out to see if someone has any recommendations.

### CODE REVIEW

**Comment by parkervcp** [comment]
Please check out https://github.com/parkervcp/eggs/blob/master/HOWTO.md and work on this PR if possible. 

I am mainly calling out the custom container you have. There is no public dockerfile I can see. I want the eggs to be as open as possible.

**Comment by ki2007** [comment]
I will work on it after my exam. 

Dockerfile is currently here: https://github.com/ki2007/images/tree/sinusbot

It just needs many packages as of now. I just wanted to make it work. I will condense the packages to the really needed ones, and try to move to alpine. As it needs e.g. pulseaudio I don't think that there are many other services that could use that container.

**Comment by parkervcp** [comment]
I have one just for my bot in my images repo. It's a very specific build and I get that. and I have no issue with a Sinusbot specific image. Just pared down and cleaned up.

**Comment by parkervcp** [comment]
Also if you are looking at alpine use the frolvlad glibc image.

**Comment by parkervcp** [comment]
There has been no movement on this in over a week. I am closing it for now.

**Comment by ki2007** [comment]
The egg is working what do you need me to do?

I updated the Dockerfile to only use the needed packages. Alpine did not work. I linked the file up there.

**Comment by parkervcp** [comment]
Let me look at this later. I saw no note on updates. All I saw was you said you'd work on it after exams.

**Comment by parkervcp** [comment]
@ki2007 Can I ask you to push the image over to my image repo? I want to try and keep all the images in one place.

**Comment by parkervcp** [comment]
@ki2007 I will accept this PR now. Just update the image used and sub a PR for the change.

**Pull request merged**
