### PR TITLE
Update egg-discord-java.json

### PR DESCRIPTION
**Pull request by James-Discord**
Imagine advertising in a egg... can't be sneaky hub the scummiest company/one of the scummiest on hosting

### CODE REVIEW

**Comment by gOOvER** [comment]
Why you change the Author?

**Comment by James-Discord** [comment]
because why not, its basically a walking advertisement for a company that runs crypto miners and has its own fuckin money that is worth more than 1 dollar

**Comment by gOOvER** [comment]
> because why not, its basically a walking advertisement for a company that runs crypto miners and has its own fuckin money that is worth more than 1 dollar

he wrote the egg, so he's the Author. No need to change it. If you dont like him, then thats your problem

**Comment by James-Discord** [comment]
okay whatever u say

**Review by gOOvER — CHANGES_REQUESTED** [review]
You can't change the Author

**Comment by Software-Noob** [comment]
This has nothing to do with advertising as it's the app author that's set and used for all new eggs. It's a way to show who created the egg.

**Pull request closed without merging**
