### PR TITLE
Add Minetest Egg

### PR DESCRIPTION
**Pull request by niansa**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the nesessary changes to make it work? (https://github.com/parkervcp/images/pull/31)
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by niansa** [comment]
@parkervcp?

**Comment by parkervcp** [comment]
You never answered my questions on the image. This fell by the wayside for me.

**Comment by niansa** [comment]
Wow stupidity of myself. :100:

**Comment by parkervcp** [comment]
@niansa can you update per my review?

**Comment by DeathSkullPain** [comment]
@niansa , could you update this to MT 5.1.1?

**Comment by niansa** [comment]
Done!

**Comment by DeathSkullPain** [comment]
This egg worked on Pterodactyl 0.7.16.  The game wouldn't start until I had a proper minetest.conf set up and I kept getting "No server egg configuration" messages which was a little confusing but after configuring things it worked great.

**Comment by niansa** [comment]
Interesting, "worked on my machine"
What is your error message without any valid minetest.conf?

**Comment by DeathSkullPain** [comment]
The Pterodactyl dashboard just kept reporting "No server egg configuration" with no additional information when trying to start the server.  Set up a basic minetest and the problem stopped.  Could also be linked to noobish incompetence but unable to verify as root cause.

**Comment by parkervcp** [comment]
You need to restart the daemon after importing an egg.

**Comment by DeathSkullPain** [comment]
Ah.  Noobish incompetence confirmed.

Worked great otherwise!

**Comment by parkervcp** [comment]
@niansa an you please resolve the image issue.

**Comment by niansa** [comment]
I am not getting further at it. Sorry. My docker knowledge is simply too low.

**Comment by Aaronstar-McClure** [comment]
i have a friend interested in using this egg, what was the issue? maby i could figure it out...

**Comment by Aaronstar-McClure** [comment]
so from reading the comments in the image pr, here is the big question i came up with for parker: if we use the install script to install apt dependencies, does this get saved to the server, or is it only the files saved to mnt/server?
if you dont like the game specific egg, we could add these non minetest specific deps to your normal image, would it be alright to add it to base/ubuntu, or would you not want to bloat the image further?
as far as i can tell, the new packages are as follows (excluding adduser, as you said that was already included.): init-system-helpers libcurl3-gnutls libjsoncpp1 libleveldb1v5 liblua5.1-0 libluajit-5.1-2 libsqlite3-0 
i am of course unable to check the docker build logs to see if any of these are already installed in ubuntu:18.04

**Comment by parkervcp** [comment]
The install image is only used to get the files to run the server into /mnt/server and nothing else. Any packages installed are thrown away.

**Comment by Aaronstar-McClure** [comment]
hey, i cant make changes to this pr so i will tell you here... i tested the minetest egg with the standard image and it seems to have installed and run correctly (although i do not know much about minetest itself, the install process seemed rather complicated and long. maby consider looking into it at some point?)
here is my updated egg file (renamed to .txt so i could upload it), i also updated the default version variable.

[egg-minetest.json.txt](https://github.com/parkervcp/eggs/files/5479233/egg-minetest.json.txt)

**Comment by parkervcp** [comment]
@Aaronstar-McClure you can submit a new pr with your own egg

**Pull request closed without merging**
