### PR TITLE
add Myth of Empires

### LINKED ISSUE #2747: [Egg Request]: Myth of Empires
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1371580/Myth_of_Empires/

### Links for the download

https://steamdb.info/app/1794810/

### Links for the install docs

On Official discord. info in comments

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

closes #2747 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [ ] Does your submission pass tests (server is connectable)? @ValhallaCommunityOfficial The testing is for you
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by ValhallaCommunityOfficial** [comment]
Very nice! I assume no support for server clusters yet?

**Comment by QuintenQVD0** [comment]
> Very nice! I assume no support for server clusters yet?

Yea no.

**Comment by QuintenQVD0** [comment]
> What is the status of this egg?
> 
> I started the server yesterday. Are there any features that still need to be added?

on my side it is done, it worked for me. if anyone can confirm this then this can me merged

**Review by HerrSammyDE — APPROVED** [review]
yes, you can merge them

**Review by parkervcp — APPROVED** [review]

**Comment by Davinel17** [comment]
How can we configure a cluster and world ? 

We can add server and cluster ID but it seems to missing something to combine both. 
Somoene can share how to do it with pterodactyl panel ? 

Thank you

**Comment by QuintenQVD0** [comment]
> How can we configure a cluster and world ?
> 
> We can add server and cluster ID but it seems to missing something to combine both together. Somoene can share how to do it with pterodactyl panel ?
> 
> If is not possible, is that something can be in a futur closer ?
> 
> Thank you

Currently this is not possible. To litte documentation. And mounts will be needed but you can not mount over /home/container.

**Comment by DTX-Customs** [comment]
They've just announced cluster support for Linux servers: 

> Added the cluster servers support for Linux server

**Comment by gOOvER** [comment]
> They've just announced cluster support for Linux servers:
> 
> > Added the cluster servers support for Linux server

full link?

**Comment by DTX-Customs** [comment]
> > They've just announced cluster support for Linux servers:
> > > Added the cluster servers support for Linux server
> 
> full link?

Added in edit my previous message

**Comment by gOOvER** [comment]
> > > They've just announced cluster support for Linux servers:
> > > > Added the cluster servers support for Linux server
> > 
> > 
> > full link?
> 
> Added in edit my previous message

but there a still no guide for the Linux server, because they have no linux server yet ;)

https://steamdb.info/app/1794810/

**Comment by DTX-Customs** [comment]
> > > > They've just announced cluster support for Linux servers:
> > > > > Added the cluster servers support for Linux server
> > > 
> > > 
> > > full link?
> > 
> > 
> > Added in edit my previous message
> 
> but there a still no guide for the Linux server, because they have no linux server yet ;)
> 
> https://steamdb.info/app/1794810/

According to their post on discord, I think they'll update tonight. Depending on the time zone

Here is the message: 

> Myth of Empires will undergo a temporary maintenance on 22:30 March 4 - 00:00 March 5 UTC  (1.5 hour). dans 5 heures Make sure to log off before then to avoid any losses. Maintenance time may be extended as needed. Thank you for your understanding.

We have adjusted a lot of game settings and fixed a lot of bugs.

For more details please check:
https://store.steampowered.com/news/app/1371580/view/4160834030794890000

**Comment by gOOvER** [comment]
> > > > > They've just announced cluster support for Linux servers:
> > > > > > Added the cluster servers support for Linux server
> > > > 
> > > > 
> > > > full link?
> > > 
> > > 
> > > Added in edit my previous message
> > 
> > 
> > but there a still no guide for the Linux server, because they have no linux server yet ;)
> > https://steamdb.info/app/1794810/
> 
> According to their post on discord, I think they'll update tonight. Depending on the time zone
> 
> Here is the message:
> 
> > Myth of Empires will undergo a temporary maintenance on 22:30 March 4 - 00:00 March 5 UTC  (1.5 hour). dans 5 heures Make sure to log off before then to avoid any losses. Maintenance time may be extended as needed. Thank you for your understanding.
> 
> We have adjusted a lot of game settings and fixed a lot of bugs.
> 
> For more details please check: https://store.steampowered.com/news/app/1371580/view/4160834030794890000

This maintance have nothing to do with the linux server; more with updating der public servers

**Comment by DTX-Customs** [comment]
I've just checked. They did indeed give a folder with Linux files in the same folder containing the Windows version. 

But I don't know what they've added to help clusters. 
I think that if we still can't change the location of the backup, it won't work. 

I don't know much about Docker, linux and pteroadctyl so I'll let you professionals have a look on this. ^^

**Pull request merged**
