### PR TITLE
Fixed Mindustry typo

### PR DESCRIPTION
**Pull request by vntxx**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by parkervcp** [comment]
Please fill out the template I provided. It's there for a reason. @vntxx

**Comment by vntxx** [comment]
Thought such a minor pr wouldn't need this as it is just some letter swapping

**Comment by parkervcp** [comment]
It literally says "all submissions"

**Comment by vntxx** [comment]
I'm sorry about that

**Pull request merged**
