### PR TITLE
default fivem to recommended

### PR DESCRIPTION
**Pull request by parkervcp**
resolves the current issue with the bad fivem release from using the latest instead of recommended.

still supports latest release as an option.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
  * 
### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
@Software-Noob Please review

**Comment by gOOvER** [comment]
i would set Install Image to:
`ghcr.io/parkervcp/installers:debian
`
Lesser packages updates and faster reinstall

**Review by gOOvER — APPROVED** [review]
recommended works fine, also when Server was allready updated to latest. 

Switch to recommended und reinstall made server working again

**Review by Software-Noob — APPROVED** [review]

**Comment by parkervcp** [comment]
@Software-Noob Please re-approve,

**Review by Software-Noob — APPROVED** [review]

**Pull request merged**
