### PR TITLE
A discord bot

### PR DESCRIPTION
**Pull request by Aaronstar-McClure**
converted https://github.com/ATLauncher/discord-bot to work on pterodactyl. while i did not directly use his docker file, the install script was somewhat based off of it. docker github at https://github.com/Aaronstar-McClure/npm, auto built at https://hub.docker.com/r/aaronstar/npm/

### CODE REVIEW

**Comment by Aaronstar-McClure** [comment]
working on an alert for incomplete configs now...

**Comment by parkervcp** [comment]
Would you mind horribly updating the description for the bot to have links to the ATL repos?

Also do you have links to the dockerfile for this? I am sure there is a way we can add a node container to the pterodactyl repo.

**Comment by parkervcp** [comment]
I have been working on tweaking this service myself while I wait.  
So far I have
1. Bot installing and running using node:8.9 alpine.  
2. Have a container for nodejs that I will most likely be doing a PR for to the main repo.
    The files are on my https://github.com/parkervcp/Containers repo.
3. Added variables for the config.

**Comment by Aaronstar-McClure** [comment]
alright, here are the links, origional bot github: https://github.com/ATLauncher/discord-bot origional bot dockerhub: https://hub.docker.com/r/atlauncher/discord-bot/ my version github: https://github.com/Aaronstar-McClure/npm my version dockerhub: https://hub.docker.com/r/aaronstar/npm/

**Comment by parkervcp** [comment]
@Aaronstar-McClure I am about to accept this PR but I will be tearing it apart and updating it with what I have.

Please take a look after I get my stuff up.

**Comment by Aaronstar-McClure** [comment]
i used node 8, because that was what he used, im not sure which distro that was built off of, so all the commands were trial and error. i shyed away from config parseing because i had some trouble with it for a different egg. things of note though: the file in /configs/ needs to be renamed to remove the .example...

**Comment by Aaronstar-McClure** [comment]
also, the install script uses node 8 because it needs to build the server before passing it to the run docker

**Pull request merged**
