### PR TITLE
Allow server owners to disable the query port all together.

### PR DESCRIPTION
**Pull request by StealWonders**
### Changes to existing Eggs: minecraft_java/*

I have removed `\"enable-query\": \"true\",\r\n` from all of the Minecraft Java eggs as this would prevent server owners from disabling the query port if they didn't want that feature.

Having enable-query set to true allows 3rd parties to use the GameSpy4 protocol ( http://wiki.vg/Query )
to query information about the server.

I have not tested the changes to the eggs. They should work though as nothing major has been changed.

This is my first pull request here, please be nice :)

### CODE REVIEW

**Comment by parkervcp** [comment]
This was a hold over from the panel supporting using the minecraft queries.

Test these changes first.

**Comment by StealWonders** [comment]
Sure, will soon.

**Comment by StealWonders** [comment]
I tested the eggs, seem to do their job. I cannot find the conflicting eggs in your repo for some reason...

**Comment by parkervcp** [comment]
I removed the eggs on my side while cleaning up files. If you remove the files on your side there will be no conflilct.

**Comment by StealWonders** [comment]
Alright, I've gone ahead and removed them. If I may ask, why were they removed @parkervcp?

**Comment by parkervcp** [comment]
Mostly pairing down and avoiding anything to specific like mod pack specific eggs.

**Pull request merged**
