### PR TITLE
Add Satisfactory Egg

### PR DESCRIPTION
**Pull request by lilkingjr1**
# Add Satisfactory Egg
### Summary
This egg is a culmination of both @iamkubi 's and @matthewpi 's eggs that were posted on the Discord, but with a lot of clean up and polish. One major addition is the use of the new Pterodactyl Yolks images (specifically the `source` one), and also utilizes it's ability to update the server on start (if specified). Cosmetic additions like descriptions were also added, like port redirection clarification. Lastly, a freshly written README was included as well.

Egg has been fully tested on my machine, and clients are able to easily join. Additional testing from the community of this PR is welcome.
___

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
(I know there's currently one #1374 open, but it looked like it might be closed due to thoroughness, and I wanted to keep this PR separate from that one)
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Review by parkervcp — APPROVED** [review]
Works for me. I am on the server and all seems well.

**Comment by kkoshelev** [comment]
It somewhat disappointing that the port user cares the most isn’t the port you see on the pterodactyl status screen. I’m expecting a lot of user confusions

**Comment by lilkingjr1** [comment]
> It somewhat disappointing that the port user cares the most isn’t the port you see on the pterodactyl status screen. I’m expecting a lot of user confusions

I tried it both ways, and users ultimately found it confusing both ways; so it's kind of a wash imo. I ultimately settled on the game port being the Primary port because, currently, the Pterodactyl panel states the Primary port is the "Game Port" in the Build Configuration > Allocation Management UI for an existing server. Maybe the verbiage of this single port being called "Primary", "Main, and "Game" across the panel UI can be consolidated in the future for further clarity.

**Comment by parkervcp** [comment]
> It somewhat disappointing that the port user cares the most isn’t the port you see on the pterodactyl status screen. I’m expecting a lot of user confusions

When you add an ARK or ATLAS server to the steam server browser you add it via the query port. I see this as no different.

**Comment by Zarklord** [comment]
> I tried it both ways, and users ultimately found it confusing both ways; so it's kind of a wash imo. I ultimately settled on the game port being the Primary port because, currently, the Pterodactyl panel states the Primary port is the "Game Port" in the Build Configuration > Allocation Management UI for an existing server. Maybe the verbiage of this single port being called "Primary", "Main, and "Game" across the panel UI can be consolidated in the future for further clarity.
Game Port can also just as easily mean "the port I need to connect to the game."

> When you add an ARK or ATLAS server to the steam server browser you add it via the query port. I see this as no different.
Keeping bad behavior because "we have always done it this way" is the worst possible reason to maintain bad behavior.
Here's a question: Which of the following ports does a player care about when connecting to the dedicated server?
1.  The Server Query Port
2.  The Game Port
3.  The Beacon Port
4.  The Port that allows them to connect to the game.
Which of the following ports does a server hoster care about when broadcasting the details to join the server to their players:
1.  The Server Query Port
2.  The Game Port
3.  The Beacon Port
4.  The Port that allows them to connect to the game.
The answer to both is the same, its 4, because with the exception of the egg authors and the developers of the game, **no one cares what the ports do**, no one goes and double checks to make sure that the game port is okay, no one goes and checks the port its forwarded in their router, because its meaningless.

I know I sure love going into the admin panel or having to read the readme just to know what port I need to connect to the server, that's a great user experience. to add onto this, the terminology of "Game Port" for the Primary Port has already been removed in the upcoming pterodactyl panel v2, how about we make the Primary Port actually useful instead of having it be a waste of text on the screen.

To re-iterate, no user or server hoster cares what the port actually does, if they need to know a port, they only care and want to know the port they need to connect to the server, they could care less whether its the game port, the server query port, the super awesome port, or whatever the game calls the port.
Its fairly sad that just about every single egg in the repository needs modifications to actually have a good experience to the server hoster/admin.

**Pull request merged**
