### PR TITLE
Add Synctube egg

### PR DESCRIPTION
**Pull request by mattman107**
# Description
 
This PR adds an egg for Synctube. It is an application which syncs video playback for multiple clients.

I also added a little change for the SuperTuxKart egg which I also helped to create. I misspelled my username and wanted to fix it so it was consistent with this and any other eggs I contribute in the future.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
The spelling mistake yes, but this egg is just a re-use of the generic nodejs egg.

with no modification at all, just the configuration parser, We do not need that at all.

**Comment by mattman107** [comment]
Got it. Sorry for wasting your time.

**Comment by QuintenQVD0** [comment]
> Got it. Sorry for wasting your time.

you did not waste my time. I am just trying to be straight forward with you without been rude.

**Comment by QuintenQVD0** [comment]
if you would like to still change your mail that can!

**Pull request closed without merging**
