### PR TITLE
add V Rising BepInex

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

since in this PR #1803 is no longer activity, i fixed the existing egg to make V Rising work with BepInex

- updated installscript
- added needed vc2019 & dotnet48 install
- added winedebug

Fixes: #1706 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
3. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Looks fine to me but all those collors in the install script are not needed: https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md `Keep it simple. We don't need 8 miles of the install script.`

**Comment by gOOvER** [comment]
> Looks fine to me but all those collors in the install script are not needed: [`master`/CONTRIBUTING.md](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md?rgh-link-date=2023-01-15T13%3A00%3A30Z) `Keep it simple. We don't need 8 miles of the install script.`

looks worse here in diff than it is. You have a better overview of the installation and see immediately where the error is.

For this all the comments have been removed

**Comment by gOOvER** [comment]
https://user-images.githubusercontent.com/116325/212542370-f02bc24b-898d-4a65-b142-748880e3ee64.mp4

**Comment by QuintenQVD0** [comment]
I know that it looks nice but it generates a lot of install scripts lines

**Comment by gOOvER** [comment]
> I know that it looks nice but it generates a lot of install scripts lines

removed the line, but i didn't removed to coloured messages. Yellow normal, red error, green ok

**Comment by QuintenQVD0** [comment]
> > I know that it looks nice but it generates a lot of install scripts lines
> 
> removed the lines, but i didn't removed to colored messages. Yellow normal, red error, green ok

that is a 100% fine

**Comment by QuintenQVD0** [comment]
Its fine for me, Just someone has to test it.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thx

**Pull request merged**
