### PR TITLE
Updated: SCP:SL for EXILED 6.0.0 and rewrote for better update handeling for EXILED.

### PR DESCRIPTION
**Pull request by OstojaOfficial**
# Description

In EXILED version 6.0.0 maintainers have changed the way EXILED is installed on the server, there is no more need to patch `Assembly-CSharp.dll`, instead EXILED will now load as a NwAPI plugin. I also changed the way EXILED is downloaded using wget, the current way of updating the server is when clicking on `Reinstall Server` button, the server will update using SteamCMD afterwards it will grab the latest EXILED release from GitHub, the problem is that if Exiled.tar.gz already exists the new file will be named Exiled.tar.gz.1 and the server will proceed to extract the old Exiled.tar.gz ignoring Exiled.tar.gz.1 and every time a reinstall occurs the Exiled.tar.gz files will start to pile up, using wget -O we can tell wget to overwrite the Exiled.tar.gz if it exists. And the last thing I have done is instead of using `mv` I switched to `cp` and `rf`, since `mv` will not work if directory is not empty.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by gOOvER** [comment]
Please export the complete Egg. Its still on PTDL_v1

**Comment by OstojaOfficial** [comment]
> Please export the complete Egg. Its still on PTDL_v1

Should be fixed now.

**Comment by gOOvER** [comment]
Some more things:

change the log section to {}

and add in instaqllscript at the end:

echo "-----------------------------------------"
echo "Installation completed..."
echo "-----------------------------------------"

**Comment by OstojaOfficial** [comment]
> Some more things: (i wanted to update the egg this week :D , but now you did the job :D)
> 
>     * add in instaqllscript at the end:
> 
> 
> ```
> echo "-----------------------------------------"
> echo "Installation completed..."
> echo "-----------------------------------------"
> ```
> 
>     * change log configuration to {}
> 
> 
> chrome_6xBkpE7F07

No problem. Please check now.

**Review by gOOvER — APPROVED** [review]
LGTM

Server starts without problems with 6.0.0 Version

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]

**Comment by OstojaOfficial** [comment]
@QuintenQVD0 Please review the changes now.

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
LGTM!

**Pull request merged**
