### PR TITLE
uploaded the sinusbot egg from #2375 instead of the old one

### LINKED ISSUE #2375: [BUG] Sinusbot/TS3 Client does not connect to the TS3 Server
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Sinusbot

### Modified

No, I did not modify the egg

### Expected Behavior

It looks like the Sinusbot is not compatible with the latest version of the TS3 client. Installing and starting the bot works fine, but connecting the bot is not possible.

In the Sinusbot forum it is mentioned that you can make various modifications (LogLevel, etc) - but this does not help.

It would have to be selectable a certain TS3 version, so that one can install and use a previous version.

Sinusbot Links:
https://forum.sinusbot.com/threads/updated-sinusbot-ts3-client.7596/
https://sinusbot.github.io/docs/installation/linux/#compatible-versions

Log:
2023-07-17T14:25:22+02:00 closing channels
2023-07-17T14:25:21+02:00 TSClient quit. LogLevel has been increased, please try to connect again to see more details.
2023-07-17T14:25:20+02:00 TS |INFO | | |SystemInformation: Linux 5.15.108-1-pve #1 SMP PVE 5.15.108-1 (2023-06-17T09:41Z) x86_64 Binary: 64bit
2023-07-17T14:25:20+02:00 TS |INFO | | |TeamSpeak Client 3.6.0 (2023-06-14 13:36:04)
2023-07-17T14:25:20+02:00 Starting instance ts3server://ts.ip-projects.de?port=9987&nickname=SinusBot&password=ipp2&channel=&channelpassword=
2023-07-17T14:25:20+02:00 Could not insert into Profiles-Tableno such table: Profiles
2023-07-17T14:25:20+02:00 Could not delete from Profilesno such table: Profiles
2023-07-17T14:25:20+02:00 Could not insert into Profiles-Tableno such table: Profiles
2023-07-17T14:25:20+02:00 Could not delete from Profilesno such table: Profiles
2023-07-17T14:25:20+02:00 Could not insert into Profiles-Tableno such table: Profiles
2023-07-17T14:25:20+02:00 Could not delete from Profilesno such table: Profiles
2023-07-17T14:25:20+02:00 Could not insert into Profiles-Tableno such table: Profiles
2023-07-17T14:25:20+02:00 Could not delete from Profilesno such table: Profiles
2023-07-17T14:25:20+02:00 Could not insert into Profiles-Tableno such table: Profiles
2023-07-17T14:25:20+02:00 Could not delete from Profilesno such table: Profiles
2023-07-17T14:25:20+02:00 Could not create Notifications-Tabletable Notifications already exists
2023-07-17T14:25:20+02:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists
2023-07-17T14:25:20+02:00 Could not create Chat-Tabletable Chat already exists
2023-07-17T14:23:40+02:00 script command loaded
2023-07-17T14:23:40+02:00 Initialization complete
2023-07-17T14:23:40+02:00 script sinusbot-commands loaded
2023-07-17T14:23:40+02:00 [ :114:12] SinusBot v1.0.2 on linux
2023-07-17T14:23:40+02:00 [ :113:12] Loaded SinusBot Commands v1.1.2 by Jonas Bögle (@irgendwr).

### Actual Behavior

See above

### Steps To Reproduce

Just install a Sinusbot

### Install logs

Logs above

### PR DESCRIPTION
**Pull request by diedyesterdaywashere**
# Description

Since nobody seemed to pr the egg from #2375 i decided to just throw it in there so issue can be closed?

closes #2375

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [X] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by gOOvER** [comment]
@kessel-itde could also make a PR :P But hes on vacation atm :)

**Comment by diedyesterdaywashere** [comment]
> @kessel-itde could also make a PR :P But hes on vacation atm :)

image
it's been almost a month so i figured out i could PR it myself. idk

**Comment by gOOvER** [comment]
I know him personally :D And I know that he has no idea how to make a PR :D

The question is if this change should really be in the egg; this is definitely a bug in Sinusbot and the dev should fix it, not that we have to change the eegg in 4 weeks again

**Comment by QuintenQVD0** [comment]
You are not allowed to change the egg author. Or the name as it is not needed. If you want to hard set the client version of teamspeak that is fine. But don't just trow a otther egg over this. You should just keep the original that is here and edit the startup script.

**Comment by diedyesterdaywashere** [comment]
> You are not allowed to change the egg author. Or the name as it is not needed. If you want to hard set the client version of teamspeak that is fine. But don't just trow a otther egg over this. You should just keep the original that is here and edit the startup script.

I was just PRing an egg that was just left in an unclosed issue, but I don't think I have time fixing all of this so I'll just leave it be

**Pull request closed without merging**
