### PR TITLE
update/valheim-plus

### PR DESCRIPTION
**Pull request by Attackwave**
# Description

Added new command line arguments:
- backup settings (saveinterval, backups, backupshort, backuplong)

Changed Arguments:
- public server as boolean switch

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by Attackwave** [comment]
[Valheim Dedicated Server Manual.pdf](https://github.com/parkervcp/eggs/files/10190486/Valheim.Dedicated.Server.Manual.pdf)

image

**Comment by gOOvER** [comment]
These changes are not needed.

**Comment by Attackwave** [comment]
> These changes are not needed.

These changes are set to default, so they will not affect normal users. Others, however, behave more flexibly for the automatic backup.

Is that a representative answer for all Valheim server operators?

**Comment by r3in3r** [comment]
If all the settings are not needed can we have Crossplay and Public beta support on the Valheim plus egg?

**Comment by Attackwave** [comment]
> If all the settings are not needed can we have Crossplay and Public beta support on the Valheim plus egg?

Crossplay is already in master branch.
Steam beta branch might work. The startup script already checks which Plus version can be used for the installed Valheim version. Can work, but doesn't have to.
However, I had specifically used a Valheim version with a Plus version and deactivated Auto Update. It's a bit more difficult to implement the feature, but I would also need it. Maybe I have some time to test it...or I try the AIO Egg Valheim version again.

**Comment by Attackwave** [comment]
Variables/Descriptions synced and updated.

**Comment by QuintenQVD0** [comment]
thx, but closed as of #2065

**Pull request closed without merging**
