### PR TITLE
Remove unstripped corlib override

### PR DESCRIPTION
**Pull request by ian-otto**
# Description

Starting with [BepInEx 5.4.2201](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/), the unstripped corlib libraries are not shipped with BepInEx as they are no longer required (as of Valheim version 0.217.24). This causes older installs to fail on startup due to mismatched corlib versions being used from older installs of the mod.

This change removes the doorstop override to allow it to use the main Unity versions of the libraries.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: N/A

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by ian-otto** [comment]
For an example of the issue this causes, check here: https://github.com/parkervcp/eggs/pull/2508#issuecomment-1800437577

**Comment by QuintenQVD0** [comment]
You must make all changes in the panel, then export and fully replace the file here!

**Comment by QuintenQVD0** [comment]
also already made sevrers, there does an egg update not update the startup so please add a warning to it in the readme.

**Comment by gOOvER** [comment]
there is allready an pr, which adds Mod Support.

i think, there is No need for 2 pr's. i Ping the author of the other pr, to add these Changes to his pr

**Comment by HoleInTheSeat** [comment]
Added this change to my PR
https://github.com/parkervcp/eggs/pull/2508

**Comment by parkervcp** [comment]
I'll go with favoring the single PR for this change. I'll be closing this in favor of #2508

**Pull request closed without merging**
