### PR TITLE
Update magma egg

### PR DESCRIPTION
**Pull request by JustRed23**
# Description
Add support for the recently released 1.18 server jar. This also removes some unnecessary future proofing

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by JustRed23** [comment]
Woops accidentally uploaded the wrong file

**Comment by JustRed23** [comment]
Should be good now. The only problem i have with this script is that the latest version behaves a little weird. It never checks if there is a server jar so when you use latest and the latest version is 1.18.2 it will try to run the installer jar method and fail. So you will have to set the version manually instead of setting it to latest

**Comment by JustRed23** [comment]
I am not experienced with bash enough to fix this

**Comment by Software-Noob** [comment]
> Should be good now. The only problem i have with this script is that the latest version behaves a little weird. It never checks if there is a server jar so when you use latest and the latest version is 1.18.2 it will try to run the installer jar method and fail. So you will have to set the version manually instead of setting it to latest

That's because you're checking if `MC_VERSION` is `latest` or not set to run the installer.

---

I've refactored a lot of the old code while reviewing it, but can't really finish as the installer hosts have outdated sources for required dependencies at the time of this comment. This makes testing the installer impossible.

What all versions currently have a custom bundled magma jar instead of relying on Forge UNIX args? According to my quick test and API results, all of them currently have a jar and don't need the installer. 

I'll try to run through all the jars later and drop the installer completely for current known versions if they indeed have a jar.

**Comment by JustRed23** [comment]
Yea the current versions all support the server jar, the installer jar is kind of obsolete now.

**Comment by QuintenQVD0** [comment]
This shoud already be fixt by: https://github.com/parkervcp/eggs/pull/1882

**Pull request closed without merging**
