### PR TITLE
fivem compatibility update

### PR DESCRIPTION
**Pull request by DarKiiii**
Update of the fivem egg. Make it compatible with `2417+` versions (with txadmin monitor preinstalled)
(I updated the egg to make auto server.cfg download work)

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1.  [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2.  [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
@DarKiiii Please read my comments

**Comment by DarKiiii** [comment]
@parkervcp  i had read your comments and I don't know what should I modify else.
I'm not realy good in commenting my work.
Should I create a new egg directory for the update ?

**Comment by DarKiiii** [comment]
and sorry I don't look at github often so I didnt saw your message

**Comment by parkervcp** [comment]
Can you at least explain what this changes to make it compatible with "new" versions of the fivem software. So far it changes nothing I can see.

**Comment by DarKiiii** [comment]
It makes the egg able to lauch txAdmin correctly (the parameters and the server.cfg in your egg are incomplete for newer versions of fivem)

**Comment by DarKiiii** [comment]
to make fast, the lauch command parameters were deprecated and needed to be set in server.cfg file

**Comment by parkervcp** [comment]
Command parameters work perfectly fine. I am using them with build 2431 right now.

As for updating the default server config I am fine with that.

**Comment by parkervcp** [comment]
So looking at my egg and seeing what the difference was. 

All it took to use tsAdmin was removing `+exec server.cfg` from the startup.

The rest is a good idea for the config and startup file config.

**Comment by DarKiiii** [comment]
thanks ^^ @parkervcp

**Comment by parkervcp** [comment]
@DarKiiii if anything I will soft "no" this and add the requested features to the egg I already have. If that works for you.?

**Comment by DarKiiii** [comment]
ok np

**Comment by parkervcp** [comment]
Closing this out in favor of a new change

**Pull request closed without merging**
