### PR TITLE
add/Reposilite egg

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

* [x] Does your submission pass tests (server is connectable)?
* [x] Have you added the server to the main README.md?
* [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by yesBad** [comment]
Fix the things that say "Reposile" to "Reposilite" :D

**Comment by DylanDeNewb** [comment]
Works great, currently got this running and I'm able to upload and download repositories.

**Comment by Software-Noob** [comment]
There's no "latest" version on their maven repository. The release name of "all-jar" only exists on pre-releases, making this invalid for any stable releases as you're hard-coding all.jar into the download url.

They use[ Github](https://github.com/dzikoysk/reposilite/releases) for releases as well, so it might be easiest to use our Github release grabber script with it

**Comment by gOOvER** [comment]
> There's no "latest" version on their maven repository. The release name of "all-jar" only exists on pre-releases, making this invalid for any stable releases as you're hard-coding all.jar into the download url.
> 
> They use[ Github](https://github.com/dzikoysk/reposilite/releases) for releases as well, so it might be easiest to use our Github release grabber script with it

Sometime browser_url is not shipped  with api

**Pull request closed without merging**
