### PR TITLE
add startup variable as it is recommended in the console

### PR DESCRIPTION
**Pull request by Panda260**
# Description

add startup variable as it is recommended in the console from Purpur

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@Panda260  all changes must be made in a panel and then exported!

**Comment by Panda260** [comment]
Why? i have only added a Startup variable

**Comment by Panda260** [comment]
so i edited it now

**Comment by QuintenQVD0** [comment]
@Panda260 where did you see that flag as I do not see it on there website?

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
