### PR TITLE
Add suport to branches SCP:SL

### LINKED ISSUE #2559: [Egg Request]: SCP: Secret Laboratory
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/

### Links for the download

https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/

### Links for the install docs

https://scpsl.notion.site/How-to-create-a-Dedicated-Server-ccf69233330e4d28a68c0c4cf5cc961d

### PR DESCRIPTION
**Pull request by SrLicht**
# Description

* I added 2 variables and modified the installation script to support branch and branch password.
* Resolves #2559 

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by SrLicht** [comment]
I would have liked to do something like EXILED but I don't know how to make dockers and I don't know if it is possible to add a custom docker image.
https://github.com/Exiled-Team/pterodactyl

**Comment by QuintenQVD0** [comment]
> I would have liked to do something like EXILED but I don't know how to make dockers and I don't know if it is possible to add a custom docker image. https://github.com/Exiled-Team/pterodactyl

there is no need for special docker images

**Comment by SrLicht** [comment]
> > I would have liked to do something like EXILED but I don't know how to make dockers and I don't know if it is possible to add a custom docker image. https://github.com/Exiled-Team/pterodactyl
> 
> there is no need for special docker images

Really ? what Exiled does is to set a bool that if true runs the installation script without the need to use "reinstall server".

**Comment by QuintenQVD0** [comment]
> > I would have liked to do something like EXILED but I don't know how to make dockers and I don't know if it is possible to add a custom docker image. https://github.com/Exiled-Team/pterodactyl
> 
> there is no need for special docker images

Not related to this PR

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
