### PR TITLE
Add Python 11 Yolk

### PR DESCRIPTION
**Pull request by Loki-101**
# Description

Update Python Generic Egg to have the Python 11 Yolk

## Checklist for all submissions

* [ X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X ] Have you tested and reviewed your changes with confidence that everything works?
* [ X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by QuintenQVD0 — CHANGES_REQUESTED** [review]
You need to upload the while egg not just that 1 line.

**Comment by Loki-101** [comment]
But the egg is already there. Adding that one line tells it to optionally use the newer yolk.

**Comment by QuintenQVD0** [comment]
> But the egg is already there. Adding that one line tells it to optionally use the newer yolk.

No aq the time stap also has to be updated. So always upload the whole egg

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! Thx

**Pull request merged**
