### PR TITLE
Add egg for Rising World

### LINKED ISSUE #328: Rising World Dedicated server egg
Please fill out the information bellow and remove from the line up
Please understand how Pterodactyl works when you are requesting an egg. (ie. docker-compose doesn't work for a pterodactyl server)
---------------

Service: Rising World  dedicated server egg

Does this expand an already existing service: N this is new to pterodactyl panel

Link to game: https://store.steampowered.com/app/324080/Rising_World/

Links for server downloads: i know it says no forum but this is the official dedicated server setup post on the rising world website forum : https://forum.rising-world.net/thread/8075-dedicated-server-setup/

Links for install steps/docs: same as above https://forum.rising-world.net/thread/8075-dedicated-server-setup/

### PR DESCRIPTION
**Pull request by iamkubi**
Fixes #328.  Waiting for someone who owns the game to verify the server is connectable.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by alhassanv** [comment]
There seems to be an issue with the server's connection.
https://i.alhassan.best/u/evq32OcFC9.png
The blurred areas are personal ip address

**Comment by iamkubi** [comment]
Did you add allocations for all 7 of the required ports?

**Comment by gOOvER** [comment]
Your egg does not working. You must Fix the Paths.

if you wish, contact me via Discord and i send you the corrected Egg

**Review by gOOvER — CHANGES_REQUESTED** [review]
You must create the dir linux64 and copy the steamclient.so in there. Else egg is not working

**Comment by iamkubi** [comment]
> You must create the dir linux64 and copy the steamclient.so in there. Else egg is not working

Hmm gotcha.  I think something must have changed because previously I was able to get the server to "start" (not sure if it was accessible online), but now the install fails when it tries to find the linux64 steamclient.so.  Will update it, probably this weekend.

**Comment by gOOvER** [comment]
i can send you the Working egg, if you wish

**Comment by gOOvER** [comment]
As long @iamkubi not is interessted in having the  weoirking egg, i will open a own PR

**Comment by iamkubi** [comment]
Feel free.  I don't have the game to test it, so if you do then you're in a better position to finish this.

**Comment by gOOvER** [comment]
Oh, don't know this. I own the Game and i have a working egg for it

**Pull request closed without merging**
