### PR TITLE
Read me fix

### PR DESCRIPTION
**Pull request by HoleInTheSeat**
# Description

Just a couple small things I noticed in the ReadMe.

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@HoleInTheSeat any other things you found missing?

**Comment by HoleInTheSeat** [comment]
> @HoleInTheSeat any other things you found missing?

That should be everything. Thanks!

**Comment by QuintenQVD0** [comment]
> > @HoleInTheSeat any other things you found missing?
> 
> That should be everything. Thanks!

are you sure? ;)

**Comment by HoleInTheSeat** [comment]
Now it should be. lol

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
Hopefully it should be good rn

**Pull request merged**
