### PR TITLE
Add Magical Fidget Bot

### PR DESCRIPTION
**Pull request by DomiiBunn**
### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:
Outstanding PR

### New Server Submissions:

1. [x ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x ] Have you added the server to the main README.md?
4. [ x] Have you added a unique README.md for the server you are adding?

For more info @BlueExorc1st

### CODE REVIEW

**Comment by DomiiBunn** [comment]
That merge conflict already looks fun ^.^

**Comment by parkervcp** [comment]
@DomiiBunn Please rebase your PR on the latest master...

**Comment by DomiiBunn** [comment]
Sure!

**Comment by Software-Noob** [comment]
Your readme contains League Sandbox, yet such egg does not exist in the master yet

**Comment by DomiiBunn** [comment]
#786 Waiting on it :/

**Comment by Software-Noob** [comment]
> #786 Waiting on it :/

I can see the PR, but it's not related to this PR and if this gets merged there will be a conflict with the readme. You should 
remove it from this PR and it would be added from #786 if it gets merged

**Comment by DomiiBunn** [comment]
Yeah ik. I'll rebase it as i have time like I said above ^.^

**Comment by parkervcp** [comment]
Please rebase on my current master and PR from a branch.

**Comment by DomiiBunn** [comment]
I am just gonna remove the reppo and redo it. Messing with rebase has my head spinning

**Pull request closed without merging**
