### PR TITLE
Add the isle evrima

### PR DESCRIPTION
**Pull request by Rage-GitHub**
### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by gOOvER** [comment]
you missed to add the Game to main readme

**Comment by gOOvER** [comment]
btw - duplicate of #1660

**Comment by Rage-GitHub** [comment]
> btw - duplicate of #1660

Doesn't include the newly pushed update changes for server launch parameters, essentially breaking the server installation.

**Comment by enozii** [comment]
> > btw - duplicate of #1660
> 
> Doesn't include the newly pushed update changes for server launch parameters, essentially breaking the server installation.

I tested your egg and yes the extra line in startup command works, but the rest is just copy paste of mine, and yet you manage to not have variables working after initial install? If you're gonna steal others work and not credit them, at least do it properly. I haven't updated my egg since it's been 3 months with no replies/action and people like you just rip it off.

**Comment by Rage-GitHub** [comment]
> > > btw - duplicate of #1660
> > 
> > 
> > Doesn't include the newly pushed update changes for server launch parameters, essentially breaking the server installation.
> 
> I tested your egg and yes the extra line in startup command works, but the rest is just copy paste of mine, and yet you manage to not have variables working after initial install? If you're gonna steal others work and not credit them, at least do it properly. I haven't updated my egg to whats actually my most recent build where the launch parameters work, since it's been 3 months with no replies/action and people like you just rip it off.

I didn't realize using open source software and modifying it wasn't allowed. It's better to provide something that functions for people than something that doesn't that hasn't been updated in 3 months. You can at least continue to work on it even if your PR hasn't had a reply or reviews.

**Comment by gOOvER** [comment]
but removing the Author or Not adding any Info is Not the fine way. ;) 

If you really c&p the Egg, readd the original Author and add any Credit to the readme

**Comment by Rage-GitHub** [comment]
> but removing the Author or Not adding any Info is Not the fine way. ;)
> 
> If you really c&p the Egg, readd the original Author and add any Credit to the readme

Wasn't aware that that was an issue then, wasn't mentioned anywhere in the repo or contributing.md file. I'll add credit, but I can't help when something is undermined without context.

**Comment by enozii** [comment]
[#1660](https://github.com/parkervcp/eggs/pull/1660) has been updated to work with Update 5

**Pull request closed without merging**
