### PR TITLE
Minor fixes: SCP:SL Exiled tar extract

### PR DESCRIPTION
**Pull request by OstojaOfficial**
# Description

Proposal to add `-m` parametar to set all of the modified times on the unpacked files to the current system time.
img

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy is that needed?

**Comment by OstojaOfficial** [comment]
> Wy is that needed?

Stops tar from complaining about time stamps from the future.

**Comment by QuintenQVD0** [comment]
wy did you add a - before the tar flags? normaly that is not needed anymore in modern versions of tar

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by QuintenQVD0** [comment]
LGTM! thx

**Pull request merged**
