### PR TITLE
Fix Valheim stop command following server update

### PR DESCRIPTION
**Pull request by Magi1053**

### CODE REVIEW

**Comment by gOOvER** [comment]
Didn't u miss in -public the 1?

-public 1

**Comment by gOOvER** [comment]
And please increse Server Name to 60. 20 Chars are a bit low :)

**Comment by Magi1053** [comment]
Thank you for pointing out the missing 1 🤦

**Comment by gOOvER** [comment]
> Thank you for pointing out the missing 1 🤦

But as i see on their Discord, -public 1 was removed from reference Server_start.sh and its not longer needed:

https://discord.com/channels/391142601740517377/806216652742983700/809066366945984513
https://discord.com/channels/391142601740517377/806216652742983700/809061346699771904

**Comment by DSczyrba** [comment]
I can't get it running. 
Its keeps stuck with the new updatet egg with this:

```
02/10/2021 22:49:29: Initializing world generator seed: ( 0 )   menu:True  worldgen version:1
02/10/2021 22:49:29: Using mountain distance: 1000
02/10/2021 22:49:29: Render threading mode:SingleThreaded
FormatException: Input string was not in a correct format.
  at System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) [0x00057] in <b6074dacdf2142f38da4050b03a225bb>:0 
  at System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00013] in <b6074dacdf2142f38da4050b03a225bb>:0 
  at System.Int32.Parse (System.String s) [0x00007] in <b6074dacdf2142f38da4050b03a225bb>:0 
  at FejdStartup.ParseServerArguments () [0x000b2] in <03b79dc1743d450a8ed6ae4aa6288a75>:0 
  at FejdStartup.Awake () [0x00104] in <03b79dc1743d450a8ed6ae4aa6288a75>:0 
02/10/2021 22:49:29: Missing audio clip in music respawn
02/10/2021 22:49:29: Builder started
Unloading 15 unused Assets to reduce memory usage. Loaded Objects now: 85927.
Total: 94.737035 ms (FindLiveObjects: 5.072894 ms CreateObjectMapping: 13.497165 ms MarkObjects: 75.499247 ms  DeleteObjects: 0.666107 ms)
Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak 
```

I already tried a new server and reinstall and whatever.

**Comment by gOOvER** [comment]
This Sounds more like a Bug in the Server. For me the egg Runs and server works

**Pull request merged**
