### PR TITLE
add corpbot

### LINKED ISSUE #444: [Request] corpbot
Service: Bots/Discord

Does this expand an already existing service: Y

Link to game: https://github.com/corpnewt/CorpBot.py

Links for server downloads: https://github.com/corpnewt/CorpBot.py

Links for install steps/docs:
An install script is included in the files

### PR DESCRIPTION
**Pull request by parkervcp**
adds corp bot

resolves #444 

can't pull the config file until it's merged. Here is my example one.
https://gist.githubusercontent.com/parkervcp/f5a9c0162b3298a50f5cff3e94093897/raw/83aa868ddd96b11d4ed03d13333108141947fcd9/settings_dict.json

### All Submissions:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:
1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by lrmtheboss** [comment]
the bot takes a long time to install
not sure if bug or not.

**Comment by parkervcp** [comment]
It's not a bug. It just takes a long time to install.

**Comment by lrmtheboss** [comment]
left running overnight and still has not installed

**Comment by parkervcp** [comment]
You need to check your daemon logs @lrmtheboss . This is probably not the egg.

**Comment by lrmtheboss** [comment]
its stuck on Do you want to continue? [Y/n]

**Comment by parkervcp** [comment]
Can you get the install log please. I don't see why it would be asking a question.

`tail -n 100 /srv/daemon/config/servers/${server-uuid}/install.log | nc bin.ptdl.co 99`

**Comment by lrmtheboss** [comment]
http://bin.ptdl.co/7dk1a

**Comment by lrmtheboss** [comment]
installed but now i get "[Pterodactyl Daemon] No server egg configuration could be located; aborting startup." when starting the bot

**Comment by parkervcp** [comment]
@lrmtheboss You need to restart the daemon after importing an egg. I call it out all over the place.

**Comment by lrmtheboss** [comment]
yea forgot that
now i get "[Pterodactyl Daemon] Starting server container.
:/home/container$ python Main.py
Could not load settings_dict.json!
- Extra data: line 1 column 4 (char 3)
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 3
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds" when starting

**Comment by parkervcp** [comment]
Yes. The current settings file doesn't exist in a place where it can be pulled from. It's looking for the file in the repo. Where it will be when I add the bot...

**Comment by lrmtheboss** [comment]
yeap can confirm that it works now

**Pull request merged**
