### PR TITLE
Update Cryofall to use SteamCMD

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### Changelog:

- Update egg to use SteamCMD
- move egg to correct folder

### CODE REVIEW

**Review by parkervcp — APPROVED** [review]
LGTM

**Review by Software-Noob — COMMENTED** [review]
Would you mind adding the AUTO_UPDATE variable to disable auto-updates for users who'd like that since we didn't force auto-update in the past? A boolean value of 0 disables it, and 1 enables.

Other than that, LGTM and works as it should.

**Comment by gOOvER** [comment]
> Would you mind adding the AUTO_UPDATE variable to disable auto-updates for users who'd like that since we didn't force auto-update in the past? A boolean value of 0 disables it, and 1 enables.
> 
> Other than that, LGTM and works as it should.

Then i need to create a source_dotnet Image first. Cryofall needs dotnet5 :)

**Comment by Software-Noob** [comment]
> > Would you mind adding the AUTO_UPDATE variable to disable auto-updates for users who'd like that since we didn't force auto-update in the past? A boolean value of 0 disables it, and 1 enables.
> > Other than that, LGTM and works as it should.
> 
> Then i need to create a source_dotnet Image first. Cryofall needs dotnet5 :)

Ah, I completely missed that. That's fine.

**Review by Software-Noob — APPROVED** [review]

**Pull request merged**
