### PR TITLE
Fix/forge generic

### PR DESCRIPTION
**Pull request by shanehughes1990**
### All Submissions:

* [YES] Have you followed the guidelines in our Contributing document?
* [YES] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [YES] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* Changed the way it searches for the download link, I have not worked out the latest parameter yet so its currently removed, but it now finds the correct link for the modpack version variable
* Also some modpacks when downloaded are buried in a subdirectory, added a fix for that aswell to look for universal.jar and extract whatever else that is in the same directory to root of server folder
* ~~Added variable to run server.jar with java parameters specific to modpack you are running,~~ Removed by request by @parkervcp https://github.com/parkervcp/eggs/pull/270#issuecomment-516408654

2. [YES] Have you tested your Egg 
* Thoroughly with multiple modpacks from curseforge, I use twitch app to download all my modpacks
* Tested with Skyfactory 4, Project Ozone 3, Digsite, Onmifactory, All the mods 3

### CODE REVIEW

**Comment by parkervcp** [comment]
@shanehughes1990 First don't add the JAVA_VARIABLES to the startup please.

This should just update the install script.

**Comment by shanehughes1990** [comment]
ahh alright I will fix or make a new pull for the variables change. I will do that this evening

**Comment by shanehughes1990** [comment]
@parkervcp Have a look at it now, removed JAVA_PARAMETERS from the pull request, also you said not in startup, where would you put it then?

**Comment by parkervcp** [comment]
I don't want it in by default in any way. Let the server hosts decide. The flags that someone sets are probably good for all their servers. but it doesn't need to be a variable.

**Comment by shanehughes1990** [comment]
Alright was just curious the branch should be good to merge whenever your good.

**Pull request merged**
