### PR TITLE
Eco - added autoupdate; update readme

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

- update to PTDL_v2
- added autoupdate
- added more Variables; Webserver URL, Max Connections (important for low performance servers), Playtime (to modify Playtime), DetailedDescription (for a detailed description in the server browser)
- update readme

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by parkervcp** [comment]
> * added autoupdate

You appear to have added more than just the auto update. Care to add the rest of what you added to the notes @gOOvER ?

**Comment by gOOvER** [comment]
> > * added autoupdate
> 
> You appear to have added more than just the auto update. Care to add the rest of what you added to the notes @gOOvER ?

you're right :D was my egg for running :) added more Variables :) 5 mins its fixed :)

**Comment by gOOvER** [comment]
> > * added autoupdate
> 
> You appear to have added more than just the auto update. Care to add the rest of what you added to the notes @gOOvER ?

fixed

**Comment by QuintenQVD0** [comment]
Can you add back steam_disk_space

**Comment by gOOvER** [comment]
> Can you add back steam_disk_space

thats really annoying, th its removed, when it was never added; thats part of Pterodactyl, but API things for hosters are more important. I'll add it back

**Comment by QuintenQVD0** [comment]
What is that pteroforge install image? + please add the install finished echo to the end of the install

**Comment by QuintenQVD0** [comment]
last thing, remove this: apt -y update
apt -y --no-install-recommends install curl lib32gcc-s1 ca-certificates

Then I merge it

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
