### PR TITLE
add Palworld proton

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- add a Palworld egg with proton RE-UE4SS and winmm.dll
- Update the parser application to v1.0.10 so now the PUBLIC_IP variable is not needed anymore (thats wy I removed it from the startup) so if the PUBLIC_IP variable does not exitis or is empty then SERVER_IP will be used. if it is set then it will be used 
https://github.com/QuintenQVD0/Palword-server-config-parser/blob/main/main.go#L372-L381
- The linux binary can now based if the variable WINEPREFIX is found or the proton binary exits switch to use the windows path on the linux binary

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by ValhallaCommunityOfficial** [comment]
Getting this on a fresh install

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Digest: sha256:68c362b3c2117b839e2424675d7229a1ae9c2c2b3c7437fe68b9c32225ae3ce4 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:proton 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(22) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
Logging directory: '/home/container/.steam/steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2394010' already up to date.
:/home/container$ ./PalworldServerConfigParser; (while read cmd; do rcon -s -a "localhost:$RCON_PORT" -p "$ADMIN_PASSWORD" "$cmd";done) < /dev/stdin & proton run /home/container/Pal/Binaries/Win64/PalServer-Win64-Test.exe EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -port=${SERVER_PORT} -publicport=${SERVER_PORT} -servername="${SERVER_NAME}" -players=${MAX_PLAYERS} $(if [ -n "$SERVER_PASSWORD" ]; then echo "-serverpassword=\"${SERVER_PASSWORD}\""; fi) -adminpassword="${ADMIN_PASSWORD}"
Program Version: v1.0.9
Error copying file: open /home/container/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: no such file or directory
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by jbdevic** [comment]
Same problem here

**Comment by gOOvER** [comment]
why using Proton, when there is a Linux Server?

**Comment by QuintenQVD0** [comment]
> why using Proton, when there is a Linux Server?

Many want to use mods, such as palguard what is windows only

**Comment by QuintenQVD0** [comment]
I remake this PR as with the latest palworld egg things changed

**Pull request closed without merging**
