### PR TITLE
Added Steam Auth for Starbound

### PR DESCRIPTION
**Pull request by NgLoader**
Supporting steam auth (only to download the server)

### CODE REVIEW

**Comment by NgLoader** [comment]
You must own the game to instsll it and the auth token is not requierd only when you using steam auth for mobile

**Comment by parkervcp** [comment]
I didn't realize this is for starbound. I didn't read that far into it.

**Comment by parkervcp** [comment]
@NgLoader I see you added both starbound and arma 3 to this. I only accespt PR's to single services not multiple.

**Comment by NgLoader** [comment]
@parkervcp Okay

**Comment by parkervcp** [comment]
I am closing this PR out please submit individual ones for each game you want to update.

**Pull request closed without merging**
