### PR TITLE
Add Neverwinter Nights: Enhanced Edition

### LINKED ISSUE #507: Neverwinter Nights Egg Request
Hi Parker!!! 

It would be awesome to get NWN running on ptero. Thank you for all your hard work maintaining this REPO!!

Service: NeverWinter Nights Egg
Does this expand an already existing service: N

Link to game: https://store.beamdog.com/products/neverwinter-nights-enhanced-edition

Links for server downloads: https://forums.beamdog.com/post/googleplus/discussion?id=67157

Links for install steps/docs: https://hub.docker.com/r/beamdog/nwserver/
Link to the commands, windows version but the game commands are the same, if you scroll down you will see the section.
http://neverwinternights.info/dedicatedserver.htm

### PR DESCRIPTION
**Pull request by RStivanson**
# Description

Adds an egg for Neverwinter Nights: Enhanced Edition. There was [an open PR](https://github.com/parkervcp/eggs/pull/1582) for this already, but it looks to be stale and broken so I'm opening a new one. Credits go to @NgLoader for the foundations for this though.

I added some extra information on data deployment to the README. There really isn't a ton of documentation on this game anymore it seems, and the info that is there is scattered in the wind. Figured I would consolidate some of it here so people have a good grip on how to get starting playing on the server.

closes #507 

**One important** thing to note is that due to [a bug/oversight](https://github.com/pterodactyl/panel/issues/3830) in the Wings daemon containers are started with an invalid user which causes the server to crash. This egg will only work if you set the environment variables `WINGS_UID` and `WINGS_GID` to `1000` and restart your Wings daemon. For context, the server tries to determine its base working directories based on the current user, which is invalid thus causing a segfault.

It's possible that we would want a specific yolk for this instead, similar to the DayZ workaround. Though I figured I would throw this up now where it could be discussed.

Feedback appreciated. Thanks.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
  * I did, there is [an open PR](https://github.com/parkervcp/eggs/pull/1582) though it is stale.
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Thank you. There is a fix in PR for the wings that creates a fake /etc/passwd file what will fix this. Its just not yet merged.

**Comment by killertobyd** [comment]
Any Updates?

**Comment by RStivanson** [comment]
The egg itself is good to go with the stated workaround, just needs reviewed. I believe [this](https://github.com/pterodactyl/wings/pull/172) is the wings PR that @QuintenQVD0 was referring to, but doesn't look like it has been merged yet.

**Comment by QuintenQVD0** [comment]
I am approving this, it works with the linked wings PR (even that it is closed now and not merged)

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
