### PR TITLE
Pocketmine MP egg (Minecraft Bedrock Engine)

### PR DESCRIPTION
**Pull request by onekintaro**
For all who need it :) now in the correct folder :)

### CODE REVIEW

**Comment by Tomoli75** [comment]
GG on the egg creation, someone please **accept the PR**.

**Comment by r7vmc** [comment]
what about adding "--disable-ansi" to the start command? it will fix the spam
https://forums.pmmp.io/threads/is-there-a-way-to-disable-cli_set_process_title.6052/

**Comment by onekintaro** [comment]
Ah this fixes the spam :) thank you i added the command to startup

**Comment by parkervcp** [comment]
Fist things first I won't let you have an egg that uses a shell script to start. It's too easy to modify and have it run other things.

Second there has to be a better image for this. I have yet to look through any of it other than that.

**Comment by onekintaro** [comment]
Okay i will look to fix this things :)

**Comment by parkervcp** [comment]
I am trying it out as well. I am just poking around right now.

**Pull request merged**
