### PR TITLE
Add Pavlov VR egg

### PR DESCRIPTION
**Pull request by TASelwyn**
This egg is for Pavlov VR. I started this a month ago, set it up, posted about it in the open issue about pavlov vr (https://github.com/parkervcp/eggs/issues/481) which sat for a month because of school mainly, until someone brought it back up (smishcraft) whom suggested fixing the port startup to use {{SERVER_PORT}}, since fixed, I think this egg is ready for use.

This fixes https://github.com/parkervcp/eggs/issues/481.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by smishcraft** [comment]
The latest game update has broken the ability to run the server in docker without manually copying files over, I have contacted the devs to see if it was an intentional change and will update here with their response.

**Comment by TASelwyn** [comment]
> Current Status: Will not work due to the latest update to the game.
> 
> The latest game update has broken the ability to run the server in docker without manually copying files over, I have contacted the devs to see if it was an intentional change and will update here with their response.

Update on this:

M1DN1GHT and I have fixed this by using the base/debian dockerfile and adding the libc++-dev package. However, that requires using a seperate docker image, which m1dn1ght is hosting on his quay. Not sure if that's acceptable to be merged or not, but it does, in fact work now.

**Comment by Software-Noob** [comment]
> > Current Status: Will not work due to the latest update to the game.
> > The latest game update has broken the ability to run the server in docker without manually copying files over, I have contacted the devs to see if it was an intentional change and will update here with their response.
> 
> Update on this:
> 
> M1DN1GHT and I have fixed this by using the base/debian dockerfile and adding the libc++-dev package. However, that requires using a seperate docker image, which m1dn1ght is hosting on his quay. Not sure if that's acceptable to be merged or not, but it does, in fact work now.

You should PR the image required to make it run to the [images repository](https://github.com/parkervcp/images)

**Comment by TASelwyn** [comment]
> > > Current Status: Will not work due to the latest update to the game.
> > > The latest game update has broken the ability to run the server in docker without manually copying files over, I have contacted the devs to see if it was an intentional change and will update here with their response.
> > 
> > 
> > Update on this:
> > M1DN1GHT and I have fixed this by using the base/debian dockerfile and adding the libc++-dev package. However, that requires using a seperate docker image, which m1dn1ght is hosting on his quay. Not sure if that's acceptable to be merged or not, but it does, in fact work now.
> 
> You should PR the image or changes required to make it run to the [images repository](https://github.com/parkervcp/images)

https://github.com/TASelwyn/images/blob/game/pavlov/Dockerfile

**Comment by Software-Noob** [comment]
> > > > Current Status: Will not work due to the latest update to the game.
> > > > The latest game update has broken the ability to run the server in docker without manually copying files over, I have contacted the devs to see if it was an intentional change and will update here with their response.
> > > 
> > > 
> > > Update on this:
> > > M1DN1GHT and I have fixed this by using the base/debian dockerfile and adding the libc++-dev package. However, that requires using a seperate docker image, which m1dn1ght is hosting on his quay. Not sure if that's acceptable to be merged or not, but it does, in fact work now.
> > 
> > 
> > You should PR the image or changes required to make it run to the [images repository](https://github.com/parkervcp/images)
> 
> https://github.com/TASelwyn/images/blob/game/pavlov/Dockerfile
> 
> It doesn't seem I can PR into a new branch on github, soo I'm not entirely sure how I'm supposed to PR this.

Parker will move it to a different branch if required, if all you need is one package then it can be added to the existing base/debian image

**Comment by M1DN1GHT01** [comment]
Gonna be deleting the current docker file its using, make sure to set it to Parkers base Debian before having anyone use it.

**Comment by TASelwyn** [comment]
As per https://github.com/parkervcp/images/pull/80 that was just merged.

I think this PR is now ready to merge. The download url for the configs are still from my repo, but until it's merged here it'd just 404 if I switch them.

**Review by Software-Noob — APPROVED** [review]

**Comment by Software-Noob** [comment]
The RCON port variable should have some kind of example default value to give an idea on what to use, since it is marked as required.

You have leftover commented symlink lines in the script. Using `curl -ssL -o <filename> <url>` is cleaner than the wget redirect outputs. Change the download path of the .ini files to Parkers repository and this is ready for a merge.

**Comment by Software-Noob** [comment]
Thank you for the contribution!

**Pull request merged**
