### PR TITLE
Update intaller script

### PR DESCRIPTION
**Pull request by adrijanb**

### CODE REVIEW

**Comment by Software-Noob** [comment]
What's the reason behind this request? There's no difference between ubuntu 18.04 or 20.04 in the install container, also all new eggs move towards using debian:buster-slim for installations

**Comment by adrijanb** [comment]
In the old installation process the command "apt -y update" was used, unfortunately the command did not work and leads to errors because it cannot update the packages. So I changed the command in the installation command to "apt update".

The changed Ubuntu version only serves to ensure that the container uses the latest version.

**Comment by Software-Noob** [comment]
Oh, I just noticed that it's using 18.10 cosmic release and not 18.04, which is pretty stupid.

 I'd recommend changing to `debian:buster-slim` as that's the lightweight image that all new containers are moving towards

**Comment by parkervcp** [comment]
I agree with converting to `debian:buster-slim` from ubuntu

**Comment by parkervcp** [comment]
@adrijanb Please see my prior comment about using the debian image instead of ubuntu.

**Comment by parkervcp** [comment]
As the PR template wasn't filled in I am closing this.

**Pull request closed without merging**
