### PR TITLE
Mariadb use ghcr.io image

### LINKED ISSUE #1569: [Bug]: MariaDB: Update to use the correct images
### Does this expand an already existing service

Yes

### Link to a game or software

database/sql/mariadb

### Links for the download

https://github.com/parkervcp/yolks/tree/master/mariadb

### Links for the install docs

I don't know what type to issue to open so. My request is to update the mariadb egg to use the correct docker images. Thanks

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- update the egg to use the 10.3 image
- closes #1569

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by parkervcp** [comment]
@QuintenQVD0 Can we also rename it to `mariaDB 10.3`

**Comment by gOOvER** [comment]
> @QuintenQVD0 Can we also rename it to `mariaDB 10.3`

10.3 is eol sind 6 monts and not really needed, since newer versions backwards compatible

**Comment by parkervcp** [comment]
> > @QuintenQVD0 Can we also rename it to `mariaDB 10.3`
> 
> 10.3 is eol since 6 months and not really needed, since newer versions backwards compatible
> 
> Better would be to update the egg to latest LTS 10.11

I am still waiting on my PR for wings to resolve an issue with updated mariadb versions. 10.3 is the last one we can use until then.

**Comment by gOOvER** [comment]
> > > @QuintenQVD0 Can we also rename it to `mariaDB 10.3`
> > 
> > 
> > 10.3 is eol since 6 months and not really needed, since newer versions backwards compatible
> > Better would be to update the egg to latest LTS 10.11
> 
> I am still waiting on my PR for wings to resolve an issue with updated mariadb versions. 10.3 is the last one we can use until then.

ohh, sry, i forgot that. So it comes never :/

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 Can we also rename it to `mariaDB 10.3`

That's certainly possible. 
Can we use the nss wrapper in the images for now?

**Comment by parkervcp** [comment]
> > @QuintenQVD0 Can we also rename it to `mariaDB 10.3`
> 
> That's certainly possible. Can we use the nss wrapper in the images for now?

I would rather not. I just updated my PR to meet some requests from Matthew. The delay was my fault.

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
