### PR TITLE
[Minecraft] Add support for Modrinth modpacks

### PR DESCRIPTION
**Pull request by dhkatz**
# Description

With the recent issues the Minecraft community has been facing with CurseForge, it seems like Modrinth is positioned to grow in popularity quickly due to its open-source nature. This adds support for Modrinth modpacks, including Forge, Fabric, and Quilt

[Here is a gist so you can see the installation script by itself](https://gist.github.com/dhkatz/edfa7f2efd6f819d0884760602daadd8#file-modrinth-sh)

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
* [x] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by dhkatz** [comment]
I would like to potentially add an update mechanism to the script.

This would involve saving a list of the mods installed on the initial server installation. We would then delete those and download the new mods. This would also allow users to add extra mods/jars which would not be deleted on an update.

Will need to warn players that their configs may be potentially overwritten (maybe make a backup for them in config-old?)

**Review by Tunakirkoc — APPROVED** [review]
Worked for me, Thanks.

**Comment by dhkatz** [comment]
There are a few changes I want to make to this still before having it merged if it does get merged

**Comment by QuintenQVD0** [comment]
Let me know when it is ready for review

**Comment by dhkatz** [comment]
@QuintenQVD0 Ready for review now! 😊

**Comment by dhkatz** [comment]
Would it be okay if I opened a second PR to replace the [current CurseForge egg](https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/java/forge/curseforge-generic) with one similar to this that also supports Fabric and Quilt (instead of just Forge)?

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you

**Pull request merged**
