### PR TITLE
Adding a NodeJS server

### PR DESCRIPTION
**Pull request by ducksquaddd**
Simply a NodeJS server

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Have you added the server to the main README.md?
3. [x] Have you added a unique README.md for the server you are adding?

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by parkervcp** [comment]
So if I am reading this right you just want to run raw nodejs?

**Comment by Software-Noob** [comment]
Discord.js egg already does this? You are also using old node 8 docker image and ubuntu 16 for the install container

**Comment by ducksquaddd** [comment]
> 
> 
> Discord.js egg already does this? You are also using old node 8 docker image and ubuntu 16 for the install container

If it already can run any NodeJS server why not say that somewhere? It could help people who dont understand what there doing know that it also can host any node based project.

**Comment by ducksquaddd** [comment]
> 
> 
> So if I am reading this right you just want to run raw nodejs?

Yep

**Comment by Software-Noob** [comment]
> > 
> > 
> > Discord.js egg already does this? You are also using old node 8 docker image and ubuntu 16 for the install container
> 
> If it already can run any NodeJS server why not say that somewhere? It could help people who dont understand what there doing know that it also can host any node based project.

The discord.js egg can run any javascript application with nodejs 12-16 images and  github pulling. It's mainly created for bots in mind hence the name

**Pull request closed without merging**
