### PR TITLE
Removed, Useless

### PR DESCRIPTION
**Pull request by Lycol50**
you can't connect to it if you change the Server IP.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
1. How often are you changing the IP?
2. The public ip is outside the container and this guarantees that the right ip gets advertised.

**Comment by Lycol50** [comment]
1. Not much
2. but the problem is if the port changed and the IP of that node (via Network Allocation on panel) is set to 0.0.0.0, it will just not work, because 0.0.0.0 is used by the listener.
- Changing IP on the config file, will not just work, it will just revert it back based on the config script of the egg every server restart.

**Comment by parkervcp** [comment]
The ip is set from the allocations which is how IP changes should be made,

**Comment by Lycol50** [comment]
yeah, but to be able to broadcast the server, the PublicIP should be set to 127.0.0.1, instead of 0.0.0.0

**Comment by gOOvER** [comment]
That was on my first commit 127.0.0.1, but someone told me to make public ip changeble

**Pull request merged**
