### PR TITLE
Egg Space Engineers Torch v1

### PR DESCRIPTION
**Pull request by PaludanC**
- [x]  Have you followed the guidelines in our Contributing document?

- [x]  Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

- [x]  Did you branch your changes and PR from that branch and not from your master branch?

This is my first egg i took most part from space_engineers egg

But add the part that download torch and replace config with Instance.

Torch downloader steamcmd but its the Windows version so that why i i used the Linux steamcmd. I have test it and running a server atm with it. But i think it need some more testing before you can release it, Is not the best but is a start.
I hope you can use it and change what that need to be change.

Is the issue #1349 that need it

### CODE REVIEW

**Comment by CrazyGladiator** [comment]
Please make a new one for new torch api

**Comment by includes08** [comment]
@PaludanC You still working on this?

**Comment by gOOvER** [comment]
i think, this can be closed. I created a new egg from scratch, because this egg here do not work and the Author stopped developing this

**Comment by QuintenQVD0** [comment]
Closed because of inactivity and a new egg is being made

**Pull request closed without merging**
