### PR TITLE
Updates to latest paper api and more

### PR DESCRIPTION
**Pull request by TASelwyn**
- Utilizes Paper API v2
- Makes the installation script more generalized using the ${PROJECT} variable which works between paper/waterfall/travertine. Literally all the papermc api projects shown on
https://papermc.io/api/v2/projects/
- Updated docker images to use Java 11 (LTS), seeing that papermc will stop supporting previous versions for MC 1.17.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
Yes
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
There was one for paper, which I utilized to make this general script for all papermc projects (paper/waterfall/travertine)
* [x] Did you branch your changes and PR from that branch and not from your master branch?
yes

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
Yes
2. [x] Have you tested your Egg changes?
Yes, they reinstall & download new jars and everything just fine.

### CODE REVIEW

**Comment by TASelwyn** [comment]
I thought this would be a nice addition seeing that the old travertine install scripts said "paper" and whatnot on them, thus a more standardized script with a project variable made sense to me.

**Comment by acl1704** [comment]
Paper API v2 has been merged already in #810

**Comment by TASelwyn** [comment]
> Paper API v2 has been merged already in #810

Well aware. This also updates Waterfall & Travertine.

**Comment by parkervcp** [comment]
Literally already done

**Comment by TASelwyn** [comment]
> Literally already done

For Paper Spigot, yes.
Not for Waterfall or Travertine.

**Comment by parkervcp** [comment]
Paper doesn't need an update you can skip it.

**Comment by parkervcp** [comment]
@TASelwyn If you want you can remove the paper edit and update the other two.

**Pull request closed without merging**
