### PR TITLE
image updates

### PR DESCRIPTION
**Pull request by notAreYouScared**
# Description

replaced basic Debian with installers
Changed pterodactyl images to use Parker images
## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by parkervcp** [comment]
I have been discussing this with them already and I am checking the eggs already.

**Comment by QuintenQVD0** [comment]
Check my images-update branch here in this repo. Removal of all quay.io images. All tested

**Comment by QuintenQVD0** [comment]
And mine are all exported from a panel. But you have more.

**Comment by QuintenQVD0** [comment]
and on all commits here a an extra space is added
afbeelding

**Comment by QuintenQVD0** [comment]
wait I see, you forked my branch and continued it

**Comment by parkervcp** [comment]
This was their own branch. I watched them make it.

**Comment by QuintenQVD0** [comment]
> This was their own branch. I watched them make it.

no?
https://github.com/parkervcp/eggs/compare/master...images-update
afbeelding

so its a continue but worse of my branch

**Comment by parkervcp** [comment]
no. They used the same name not checking the main repo. It should have been names update-install-images or something similar.

**Comment by QuintenQVD0** [comment]
> no. They used the same name not checking the main repo. It should have been names update-install-images or something similar.

so the github UI messed up agaon, sorry

**Comment by QuintenQVD0** [comment]
For me this is fine and can be merged, but some things like node need the same OS in the install script and game server so that would need to merge PR 230 of the yolks.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
