### PR TITLE
Add: SFTP Storage Share

### PR DESCRIPTION
**Pull request by lilkingjr1**
# Description

Adds a simple "empty" egg that acts as a private SFTP storage share by utilizing Pterodactyl's built in SFTP system for servers.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?

### CODE REVIEW

**Review by QuintenQVD0 — APPROVED** [review]

**Comment by scharez** [comment]
Is it possible to limit the disk space? When i leave the server running it should work, am i right?

**Comment by lilkingjr1** [comment]
> Is it possible to limit the disk space? When i leave the server running it should work, am i right?

@scharez Currently, the start up script just prints something and then the server shuts down. It may get rebooted a couple of times by Pterodactyl because it "crashed", but it will eventually stay off. Disk space is only checked if the server is running, and is a limitation of Pterodactyl. If you modify the startup command to run something on loop to keep the server alive, that may work.

**Comment by scharez** [comment]
> > Is it possible to limit the disk space? When i leave the server running it should work, am i right?
> 
> @scharez Currently, the start up script just prints something and then the server shuts down. It may get rebooted a couple of times by Pterodactyl because it "crashed", but it will eventually stay off. Disk space is only checked if the server is running, and is a limitation of Pterodactyl. If you modify the startup command to run something on loop to keep the server alive, that may work.

Thanks for the reply. Do you have an idee which command i can define, to run something like ah loop?

**Comment by QuintenQVD0** [comment]
> > > Is it possible to limit the disk space? When i leave the server running it should work, am i right?
> > 
> > 
> > @scharez Currently, the start up script just prints something and then the server shuts down. It may get rebooted a couple of times by Pterodactyl because it "crashed", but it will eventually stay off. Disk space is only checked if the server is running, and is a limitation of Pterodactyl. If you modify the startup command to run something on loop to keep the server alive, that may work.
> 
> Thanks for the reply. Do you have an idea which command i can define, to run something like a loop?

You can not. Even if you make a program that like checks disk space every 5 minutes on top of the wings build in one. It will shut the server and prevent it from starting. But the sftp will always keep working even of the server is ofline and the diskspace is full.

**Comment by lilkingjr1** [comment]
@QuintenQVD0 He meant something that will keep the server running so Ptero will check disk space, but I don't remember if disk space is continuously checked by Ptero, or only on startup.

**Pull request merged**
