### PR TITLE
rewrite minetest

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

rewrite the minetest egg so the binary is in the image, use the file parser to set some needed variables. 
- change game images
- change installer image
- rewrite install script
- add a lot of variables
- make use of the file parser
- add a note to the README that the console is a little broken
- update the egg to PTDL_v2

Test image: `quintenqvd/pterodactyl_images:games_minetest`
closes: #2130 

DEPTENTS ON: https://github.com/parkervcp/yolks/pull/133 !!
## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by Tealk** [comment]
Hi,

I just tested the egg, I get the following output. It is also missing the minetest binary

```
~ Starting installation process, this could take a few minutes...
Log file does not exist. Making one...
Config file does not exist. Making one...
Installation was successfully completed!
```

**Comment by Tealk** [comment]
I would not include the World as a setting. About the serverconfig you can select the different games and also the world, that would be easier to handle.

**Comment by QuintenQVD0** [comment]
> include

I don't play this game.
be more specific about what you want to changed
the world name is setup with a varaible on startup cmd and in the config file
also the config file is only like 1/15 off the full config file, only the server part

**Comment by Tealk** [comment]
Remove
```
--world \/home\/container\/.minetest\/{{WORLD_NAME}}
```
and
```
            "name": "World name",
            "description": "The name of the world",
            "env_variable": "WORLD_NAME",
            "default_value": "world",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|max:32",
            "field_type": "text"
```

it makes more sense that it is set in the server configuration file than in the start parameter.
minetest supports a lot of game types (I don't know how to explain it in a more understandable way) and for each game type the world has to be regenerated.
So it is easier to change game type and world in the config file and not in two different places.

**Comment by Tealk** [comment]
The installation seems to be faulty, because the minetest binary is missing

```
container@pterodactyl~ Starting installation process, this could take a few minutes...
Log file already exists.
Config file does not exist. Making one...
Installation was successfully completed!
```

```
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Finished pulling Docker container image
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
container@pterodactyl~ Error Event [ebd01230-5b4c-4d68-8bd1-19b8516d38bb]: environment/docker: failed to run pre-boot process: environment/docker: failed to pull "ghcr.io/parkervcp/games:minetest" image for server: Error response from daemon: manifest unknown
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Server crash was detected but an error occurred while handling it.
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Finished pulling Docker container image
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

image

**Comment by Tealk** [comment]
Where can I find the install logs?

**Comment by QuintenQVD0** [comment]
It looks like your install has failed.
We need your install logs to see why the install may have failed. Use the command below on your Wings machine SSH terminal.

If you are on 1.0
```tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99```
If you are on or upgraded from 0.7
```tail -n 1000 $(ls -Alrt /srv/daemon/config/servers/*/install.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99```

**Comment by Tealk** [comment]
Thank you. Here is the log: https://pteropaste.com/33gvdg8vsugp

**Comment by QuintenQVD0** [comment]
> Thank you. Here is the log: https://pteropaste.com/33gvdg8vsugp

Wait, what image are u using?

**Comment by Tealk** [comment]
The one from the Egg: 'ghcr.io/parkervcp/games:minetest'.

**Comment by QuintenQVD0** [comment]
> The one from the egg-minetest.json: 'ghcr.io/parkervcp/games:minetest'.

Did you read the desc? That is not even pusshed. Use my test image

**Comment by Tealk** [comment]
Still does not seem to work
image

i have now entered the test image here and reinstalled the server
image


https://pteropaste.com/7uunsvwqqypx

**Comment by QuintenQVD0** [comment]
> Still does not seem to work image
> 
> i have now entered the test image here and reinstalled the server image
> 
> https://pteropaste.com/7uunsvwqqypx

Then try to start the server.

**Comment by Tealk** [comment]
Then i get this message:

```
container@pterodactyl~ Starting installation process, this could take a few minutes...
Log file already exists.
Config file does not exist. Making one...
Installation was successfully completed!
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from quintenqvd/pterodactyl_images 
Digest: sha256:29445e0a6ba3ee73a2cc16478cb5b58032f6d123aed82c8abfcb5a2c9622bce8 
Status: Image is up to date for quintenqvd/pterodactyl_images:games_minetest 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ minetest --version
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
:/home/container$ eval minetest --server --port ${SERVER_PORT} --world /home/container/.minetest/${WORLD_NAME} --terminal --config /home/container/minetest.conf --logfile /home/container/server.log
2023-02-21 17:48:47: WARNING[Main]: Couldn't find a locale directory!
2023-02-21 17:48:47: ERROR[Main]: Game specified in default_game [minetest] is invalid.
2023-02-21 17:48:47: ERROR[Main]: ServerError: Supplied invalid gamespec

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by Tealk** [comment]
Can't you just use the images that minetest provides?
https://github.com/minetest/minetest#docker

**Comment by QuintenQVD0** [comment]
> Can't you just use the images that minetest provides? https://github.com/minetest/minetest#docker

No! Wy does no one release that. Pterodactyl does not woek with regular docker images

**Comment by QuintenQVD0** [comment]
I update the image. Give me 5 min

**Comment by Tealk** [comment]
ok thanks, I don't quite understand how pterodactyl works in the background.

What I still do not quite understand, the switches look different in the minetest manual than in the egg.

There it is called e.g. worldname not world and there is also no path given but only the name.

https://wiki.minetest.net/Setting_up_a_server#Linux_2

how is the server actually started if the binary is missing in the folder .minetest?

**Comment by QuintenQVD0** [comment]
> alled e.g. worldname not world and there is als

the binary is in the docker image, only the config gets downloaded. as they do not provide rebuild bins for linux

**Comment by Tealk** [comment]
Is it possible that the game is missing in the docker image?
[minetest](https://github.com/minetest/minetest) is just an engine and [minetest_game](https://github.com/minetest/minetest_game) is the game, maybe it needs that to start.

I tried to put it under games/minetest_game but it doesn't seem to load from it.

**Comment by QuintenQVD0** [comment]
the image is rebuilding, try again now

**Comment by QuintenQVD0** [comment]
> Is it possible that the game is missing in the docker image? [minetest](https://github.com/minetest/minetest) is just an engine and [minetest_game](https://github.com/minetest/minetest_game) is the game, maybe it needs that to start.
> 
> I tried to put it under games/minetest_game but it doesn't seem to load from it.

it should be shiped by default

**Comment by Tealk** [comment]
Server is starting, nice <3

could you add this variable too?
```
        {
            "name": "Game name",
            "description": "Default game when creating a new world. This will be overridden when creating a world from the main menu.",
            "env_variable": "DEFAULT_GAME",
            "default_value": "minetest",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|max:32",
            "field_type": "text"
        }
```

default_game is the most important variable

**Comment by QuintenQVD0** [comment]
The problem is only minetest the game itself is shiped. And any other games will first have to be downloaded by the install script. The world dir i just adapted as i first did not add the arg and is put the world there.  I am fine moving it. I need to have a look to download other games and how to properly set them

**Comment by Tealk** [comment]
I would not automate the download, just give the option in the settings to change the game.
This can be easily downloaded from https://content.minetest.net/packages/?type=game and upload the zip in pterodactyl and there tauch immediately unpack.

I am trying to see if it is not possible to use the original configuration.

**Comment by Tealk** [comment]
Here is my suggestion:
https://gist.github.com/Tealk/611bf11b08321bec4b2e3abb2a431fa3

**Comment by QuintenQVD0** [comment]
Thank you, (I don't play any minetest), i have a look later.

**Comment by Tealk** [comment]
> The config i downloaded was a stripes down version as almost everything is client settings. I only downloaded server settings.

I just followed the official instructions. Thought that would be the best, then also changes to the file with downloaded
https://wiki.minetest.net/Setting_up_a_server/Debian#Configuration_of_the_server


Now the only thing missing is the possibility to change the game.

---

I have updated the gist once again

**Comment by Tealk** [comment]
I edited the gist again, now the minetest.conf is created by install script. And the examle file is placed next to it; this way we have stored everything important for starting the server and are not dependent on a download.

**Comment by QuintenQVD0** [comment]
Fine for me. I test it later. Already thank you for your help. I add your name and donation link if you have one to the readme later

**Comment by Tealk** [comment]
now that i found out that you can work with bash i am hyped xD

If I can help somewhere else let me know.

**Comment by QuintenQVD0** [comment]
> I edited the gist again, now the minetest.conf is created by install script. And the examle file is placed next to it; this way we have stored everything important for starting the server and are not dependent on a download.
> 
> is there a technical reason why world and port are set as switches in the start command? Or can we also add this to the minetest.conf?

I just saw that I never responded to this.
 I force the world and port (world is not that needed but nice if we ever need to debug something) but port as the port should always be bind to the allocated port and if something's go wrong with the config then it will error.
 
 Furthermore, I was thinking for the games. 1 Variable that would match the game name (example:  MineClone2 ) and then get the download url from https://content.minetest.net/packages/?type=game and then download it. by default I read that is hould be placed $HOME/.minetest/games what would be /home/container/.minetest/games and /mnt/server/.minetest/games  in the install script. so if they want a difrend game they first have to reinstall and the game files would get downloaded.
 
 this is also wy I placed the worlds folder there as that was the default

**Comment by Tealk** [comment]
> by default I read that is hould be placed $HOME/.minetest/games what would be /home/container/.minetest/games and /mnt/server/.minetest/games in the install script. so if they want a difrend game they first have to reinstall and the game files would get downloaded.

True, but does it make sense to put another folder in the container?

> I was thinking for the games. 1 Variable that would match the game name (example: MineClone2 ) and then get the download url from https://content.minetest.net/packages/?type=game and then download it.

I would prefer if i can put the game in the "game" folder, so you can also start your own games and not only those that are published on contentdb

**Comment by QuintenQVD0** [comment]
> > by default I read that is hould be placed $HOME/.minetest/games what would be /home/container/.minetest/games and /mnt/server/.minetest/games in the install script. so if they want a difrend game they first have to reinstall and the game files would get downloaded.
> 
> True, but does it make sense to put another folder in the container?
> 
> > I was thinking for the games. 1 Variable that would match the game name (example: MineClone2 ) and then get the download url from https://content.minetest.net/packages/?type=game and then download it.
> 
> I would prefer if i can put the game in the "game" folder, so you can also start your own games and not only those that are published on contentdb

Then we add a select variable. Download the  game or just use a local on. Normaly we like to use defaulr directories. I dont think we can move the game folder

**Comment by Tealk** [comment]
so in the "old" egg the folders are also all in the root directory
image

can you do the download directly into the games folder or can you only do it into the docker container?

**Comment by Tealk** [comment]
you can't just do something like that:
```
    volumes:
      - /home/container:/config/.minetest
```

**Comment by QuintenQVD0** [comment]
> 

No this is pterodactyl not regular docker

**Comment by QuintenQVD0** [comment]
> so in the "old" egg the folders are also all in the root directory image
> 
> can you do the download directly into the games folder or can you only do it into the docker container?

That compiled the bin. The world and mods and games folder in the root is fine.

**Comment by Tealk** [comment]
then i would leave world, mods and games in the root directory.

The automatic download of the games will not work so well, the download probably contains a random number:
https://content.minetest.net/packages/Wuzzy/mineclone2/releases/16650/download/

**Comment by QuintenQVD0** [comment]
> then i would leave world, mods and games in the root directory.
> 
> The automatic download of the games will not work so well, the download probably contains a random number: https://content.minetest.net/packages/Wuzzy/mineclone2/releases/16650/download/

That is not a problem in any way. I made a script for that. The user would just need to put in the author and game name. Example: Wuzzy, mineclone2. It will auto get the latest version. That is not a problem

**Comment by Tealk** [comment]
I do not think the effort is worth it, especially this could again lead to problems with the mods, if the game get updatet but the mods not

**Comment by QuintenQVD0** [comment]
> I do not think the effort is worth it, especially this could again lead to problems with the mods, if the game get updatet but the mods not

There indeed is no game version control. But downloading games will not be the issue

**Comment by Tealk** [comment]
Ok, personally I don't find the function that relevant. I guess you will have to implement that in docker?

**Comment by QuintenQVD0** [comment]
> Ok, personally I don't find the function that relevant. I guess you will have to implement that in docker? Or should this be included in the installation script?

The way minetest is download. There is no option for version control. So that will not be implemented

**Comment by Tealk** [comment]
Then I wait for your changes and like to test it

**Comment by QuintenQVD0** [comment]
> Then I wait for your changes and like to test it

I am working rn. This evening. I post what i have

**Comment by QuintenQVD0** [comment]
@Tealk I added what you added + the logic for game downloading. please try it out

**Comment by Tealk** [comment]
games download and folder seems to work, but the mods folder is not loaded, respectively the mods

**Comment by QuintenQVD0** [comment]
> games download and folder seems to work, but the mods folder is not loaded, respectively the mods

So out of the downloaded .zip. i need to coppy the contence of the mods dir to the mods dir in /home/container/mods?

**Comment by Tealk** [comment]
exactly the mods that need to be loaded are located in "/home/container/mods". The mods which are activated in "/home/container/worlds/mineclone2/world.mt" are loaded from this folder.

**Comment by Tealk** [comment]
Why is the server stop command no longer shotdown?
/shutdown—Shuts down the server

**Comment by QuintenQVD0** [comment]
> Why is the server stop command no longer shotdown? /shutdown—Shuts down the server

It does not work anymore. It sas missing permissions. Try it with any mod

**Comment by Tealk** [comment]
Ok this is probably a problem because you have to give yourself the server permission first in the game
then I guess we will have to leave it like this

**Comment by Tealk** [comment]
> exactly the mods that need to be loaded are located in "/home/container/mods". The mods which are activated in "/home/container/worlds/mineclone2/world.mt" are loaded from this folder.

That's why I [asked this question](https://github.com/parkervcp/eggs/pull/2137#issuecomment-1440795056) above, because then everything would be loaded from the container.

**Comment by QuintenQVD0** [comment]
> > exactly the mods that need to be loaded are located in "/home/container/mods". The mods which are activated in "/home/container/worlds/mineclone2/world.mt" are loaded from this folder.
> 
> That's why I [asked this question](https://github.com/parkervcp/eggs/pull/2137#issuecomment-1440795056) above, because then everything would be loaded from the container.

That is not posible with pterodactyl in any way!

**Comment by Tealk** [comment]
> That is not posible with pterodactyl in any way!

yes i understood that, but how do you handle it then? do you have to map each folder you want to use individually?
this may be easy with minetest with 3 folders and 1 file; but there are still much more complex games

**Comment by QuintenQVD0** [comment]
> > That is not posible with pterodactyl in any way!
> 
> yes i understood that, but how do you handle it then? do you have to map each folder you want to use individually? this may be easy with minetest with 3 folders and 1 file; but there are still much more complex games

This is a sort of generic egg. it works for most games. Not all. I make the mods' folder (.zip) be moved in to the mods' folder in /home/container not much more I can do

**Comment by Tealk** [comment]
That confuses me now, the mods are unpacked in the folder /mods stored and then read out when starting the game, I believe even live, so I can change mods while playing.

image

**Comment by QuintenQVD0** [comment]
> That confuses me now, the mods are unpacked in the folder /mods stored and then read out when starting the game, I believe even live, so I can change mods while playing.
> 
> image

if you download a game from the community site. it comes with a folder called mods:
afbeelding
I likly need to move the contence of that folder to 
afbeelding

**Comment by Tealk** [comment]
> if you download a game from the community site. it comes with a folder called mods:

but the mods folder has nothing to do with the mods folder in the root directory.
These must not be mixed !

**Comment by Tealk** [comment]
it works
only the mods from /mods are not loaded

**Comment by QuintenQVD0** [comment]
> it works only the mods from /mods are not loaded
> 
> also stopping via ^^C is not so good, then no save of the world is triggered

I know that it is indeed not a proper way, the mods I have a look
I need to use ^^C as /shutdown does not work if a game is loaded other than minetest the game itself.

**Comment by Tealk** [comment]
> I know that it is indeed not a proper way, the mods I have a look

i don't understand, what is not the right way for the mods?

> I need to use ^^C as /shutdown does not work if a game is loaded other than minetest the game itself.

too bad, you end up losing data when you stop the server.

**Comment by QuintenQVD0** [comment]
> too bad, you end up losing data when you stop the server.

oké so the stop has to be fixt, I will note that.
I am looking at the docs rn to change the mods default dir as by default it is in the .minetest folder

**Comment by QuintenQVD0** [comment]
> If there is no other way we move everything to .minetest

does it load them in the .minetest folder?

**Comment by Tealk** [comment]
> does it load them in the .minetest folder?

Yes, when I put the mods folder in .minetest, the mods are loaded.

**Comment by QuintenQVD0** [comment]
> > does it load them in the .minetest folder?
> 
> Yes, when I put the mods folder in .minetest, the mods are loaded.

Then we will move the mods folder to there. now we have to fix the shutdown issue

**Comment by Tealk** [comment]
But then I would put all files in .minetest, so it is consistent

**Comment by Tealk** [comment]
Have create a new egg.json
https://gist.github.com/Tealk/611bf11b08321bec4b2e3abb2a431fa3

Changes:
- Paths adjusted
- games download improved

**Comment by QuintenQVD0** [comment]
What was wrong with the game download code?

**Comment by QuintenQVD0** [comment]
wait, I see you nested it. that is fine

**Comment by Tealk** [comment]
Wanted to take the exit out, the script should not abort if the variable is missing

**Comment by Tealk** [comment]
the stop command as variable is not possible?

**Comment by QuintenQVD0** [comment]
> the stop command as variable is not possible?

It is possible

**Comment by Tealk** [comment]
would be a possibility that the user can enter the stop command that is available for his gamemode

**Comment by QuintenQVD0** [comment]
> would be a possibility that the user can enter the stop command that is available for his gamemode

Normaly we dont allow the user to change it only of we set it to a list of options. Letting them enter it is normaly a no go

**Comment by Tealk** [comment]
then I can't think of any more solutions, I'm going to change my settings anyway; I don't want to lose any data.

**Comment by QuintenQVD0** [comment]
> then I can't think of any more solutions, I'm going to change my settings anyway; I don't want to lose any data.

ofc, then we will just add a note that they must give the server user the permission server or else no date will be saved

**Comment by QuintenQVD0** [comment]
I rewrote your egg a litte more, removing the games.zip file, adding the flag -o to unzip, so it overrides if needed. I moved the config and log file to /home/container as that always should be easy to find

**Comment by Tealk** [comment]
> I moved the config and log file to /home/container as that always should be easy to find

does it make sense to separate this?

**Comment by QuintenQVD0** [comment]
> > I moved the config and log file to /home/container as that always should be easy to find
> 
> does it make sense to separate this?

yes, it is way easyer if we need to ask for logs or they want to look at the config
the mods , games and world in the .minetest folder is fine as normaly a user only has to be there if they want to upload there own game or mods

**Comment by Tealk** [comment]
The games and mods must also be set in the .minetest.cfg and activated in the /home/container/.minetest/worlds/worldname/world.mt.

Now you have to jump back and forth a lot for each mod.

**Comment by QuintenQVD0** [comment]
> the stop command as variable is not possible?

I thought that was possible but apparently not.

**Comment by BasToTheMax** [comment]
Hello. How is the progress going?

**Comment by QuintenQVD0** [comment]
> Hello. How is the progress going?

The egg is ready and can be used. It is up to someone with perms to merge it. You can always test it.

**Comment by Tealk** [comment]
Yes I can confirm, use it for quite a while.

**Review by Tealk — APPROVED** [review]
Works already for a long time on my server

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
