### PR TITLE
Add VEIN

### LINKED ISSUE #2511: [Egg Request]: Vein
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1857950/VEIN/

### Links for the download

https://store.steampowered.com/app/1857950/VEIN/

### Links for the install docs

https://ramjet.notion.site/Server-Hosting-85f92f43f32548c1b5b33797ddf456ad

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

Add VEIN egg

Closes #2511 

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by ionutshiro** [comment]
**Tested , works like a charm !**

**Review by ionutshiro — APPROVED** [review]
Tested , works like a charm !

**Comment by ValhallaCommunityOfficial** [comment]
It wont let me remove the password for the server.

**Comment by QuintenQVD0** [comment]
> It wont let me remove the password for the server.

I know that. That can be fixt

**Comment by ValhallaCommunityOfficial** [comment]
> > It wont let me remove the password for the server.
> 
> I know that. That can be fixt

What would I need to do to fix it?

**Comment by ValhallaCommunityOfficial** [comment]
Nevermind! I figured out how to disable the requirement :)

**Comment by ValhallaCommunityOfficial** [comment]
On a fresh install

[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/steamcmd 
Digest: sha256:65ec60e20a987f7da80a183d272af03af3b964f11028deb4e3374586ee5be393 
Status: Image is up to date for ghcr.io/parkervcp/steamcmd:debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
tid(23) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709170084
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '2131400' already up to date.
:/home/container$ ./Vein/Binaries/Linux/VeinServer -Port=${SERVER_PORT} -QueryPort=${QUERY_PORT} -log
/entrypoint.sh: line 87: ./Vein/Binaries/Linux/VeinServer: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false

**Comment by QuintenQVD0** [comment]
> VeinServer

they renamed their binary and changed some things in the config. by Wednesday evening this should be fixt (I do not have time rn)

**Comment by QuintenQVD0** [comment]
@ValhallaCommunityOfficial I updated what I could based of the documentation (currently have no access to a running pterodactyl instance)

The Game.ini will fail to download as long as this egg is not merged, if you want to test then you will have to place it their before the first server start.

**Comment by ValhallaCommunityOfficial** [comment]
> @ValhallaCommunityOfficial I updated what I could based of the documentation (currently have no access to a running pterodactyl instance)
> 
> The Game.ini will fail to download as long as this egg is not merged, if you want to test then you will have to place it their before the first server start.

Works! server shows in list and can join. Thank you once again :)

**Review by parkervcp — APPROVED** [review]

**Comment by parkervcp** [comment]
community validated

**Pull request merged**
