### PR TITLE
Add DayZ (Experimental) Egg

### PR DESCRIPTION
**Pull request by lilkingjr1**
Related to Issue #1348, but my not close it entirely since this is Experimental branch only.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by lilkingjr1** [comment]
Forgot to add `modlist.html` feature to egg. Will add it soon.

**Comment by Prophet731** [comment]
Nice, was just searching for an egg for DayZ. I'll try it out and let you know if I encounter bugs with the installation.

**Comment by Prophet731** [comment]
@lilkingjr1 You have a typo in the startup script. No variable `CLIENT_MODS` exists but `MODIFICATIONS` does. Not sure if that's what it's supposed to be.

**Comment by lilkingjr1** [comment]
> @lilkingjr1 You have a typo in the startup script. No variable `CLIENT_MODS` exists but `MODIFICATIONS` does. Not sure if that's what it's supposed to be.

Yeh, there's some bugs with mods that I'm literally fixing as we speak.

**Comment by lilkingjr1** [comment]
@Prophet731 Actually, that particular thing you mentioned is not a bug. `CLIENT_MODS` is a private entrypoint.sh variable that gets compiled on startup. It's a combination of `MODIFICATIONS` and `MOD_LIST`, but `MOD_LIST` is missing, which is what I am fixing now.

**Pull request merged**
