### PR TITLE
AssaultCube

### PR DESCRIPTION
**Pull request by HoleInTheSeat**
AssaultCube is a FREE, multiplayer, first-person shooter game, based on the CUBE engine.

Taking place in realistic environments, with fast, arcade gameplay, it's addictive and fun!

With efficient bandwidth usage, it's low-latency and can even run over a 56 Kbps connection. It's tiny too, weighing in at a lightweight about 50 MB package available for Windows, Mac and Linux. On the correct settings, it can even run on old hardware (Pentium III and above).

# Description

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [x] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Is this your first time making an public egg?

also you can not make any changes directly in the .json file , everything must be done in a panel and then fully exported

**Comment by QuintenQVD0** [comment]
@HoleInTheSeat I cleaned your egg a little.

What I did:
- shorten the name 
- everywhere remove your caps where it said that 2 ports are needed, this is for in the README.md here
- used our git release script as hard coding a version is not done
- move to Debian 11 install image
- remove the win32 folder as we can not use them and remove all .sh files as there clearly not needed
- shorten some variable descriptions
- added a version variable
- make the default password field empty for security reasons
- use the table format for ports in the readme as that is required


**Things that you still must do**
Add it to the main readme!

**Comment by QuintenQVD0** [comment]
You can also not rename the .json file

**Comment by HoleInTheSeat** [comment]
> Is this your first time making an public egg?
> 
> also you can not make any changes directly in the .json file , everything must be done in a panel and then fully exported

Yes this is my first egg, thanks for the help, I wasn't aware renaming the egg would be an issue.
I thought I had already added it to the main readme, but I will double check.

**Comment by HoleInTheSeat** [comment]
I've Updated the main Readme.
Please let me know if there is anything else I need to fix. Thanks again for the help.

**Comment by QuintenQVD0** [comment]
> I've Updated the main Readme. Please let me know if there is anything else I need to fix. Thanks again for the help.

No problem. Thank you for making the egg. I merge it now as I tested and it installs just fine.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you.

**Pull request merged**
