### PR TITLE
A Teeworlds Server

### PR DESCRIPTION
**Pull request by MatiasMunk**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [x] Did you PR the nesessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
Why does each of these require a unique image? Why can't all of this be done with a generic image that supports all the game types?

**Comment by MatiasMunk** [comment]
> Why does each of these require a unique image? Why can't all of this be done with a generic image that supports all the game types?

You're right! I will see to creating a generic image that can be shared by the server modifications where it's possible. There are a few server modifications that require custom image, thanks for pointing it out, will do this later today and update.

**Comment by parkervcp** [comment]
I doubt specific ones require a specific image. If it does, what makes it so special?

**Comment by MatiasMunk** [comment]
Some of the server modifications require the Dockerfile to install certain packages like C++17 features, where as most of the server modifications don't need it.

**Comment by MatiasMunk** [comment]
I'll create quay.io/matiasmunk/teeworlds:core that includes basic features (Non c++17) and then quay.io/matiasmunk/teeworlds:cpp17 that includes c++17 features.

**Pull request closed without merging**
