### PR TITLE
added foldingathome egg

### PR DESCRIPTION
**Pull request by Fuggschen**
# Description

Added a Folding@Home egg for easy to run worker node to contribute to the project. Only downside is that we can't use the WebUI because it would be exposed unprotected to the web. But I enabled FAHControl access with password protection.
Anonymous and user-specific folding (with username and passkey) is possible.

Team defaults to 0 and user to Anonymous. Power is set to full because cpu limit will limit the usage regardless of system cores. All is set in the startup command because it's pain to work with the XML. It doesn't follow standard XML syntax.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by skittles-fivem** [comment]
add in a max cpu limit of 64 threads allowed to be used in the config.xml or it will only use 1 thread

**Comment by Fuggschen** [comment]
> add in a max cpu limit of 64 threads allowed to be used in the config.xml or it will only use 1 thread

@skittles-fivem can you tell me when this happens?
I never ran into this issue. My cores got all autodetected and utilisation goes up to 1200% on my 12 core CPU

**Comment by QuintenQVD0** [comment]
does it respect the set cpu persentage? so 100% = 1 thread and 200% = 1 core
it can not just detect all resources and use everything. it can only use the allocated amount of cpu and ram

**Comment by skittles-fivem** [comment]
> > add in a max cpu limit of 64 threads allowed to be used in the config.xml or it will only use 1 thread
> 
> @skittles-fivem can you tell me when this happens? I never ran into this issue. My cores got all autodetected and utilization goes up to 1200% on my 12 core CPU
im running 80 cores with Intel(R) Xeon(R) Gold 6138
by default i think the max is 64 anyway
ERROR:80 OpenMP threads were requested. Since the non-bonded force buffer reduction is prohibitively slow with more than 64 threads, we do not allow this. Use 64 or less OpenMP threads.

.
and yes it does respect the cpu % along with how much you set
gave it 64 cores with max of 5000% and it stayed at 5000%

**Comment by Fuggschen** [comment]
> im running 80 cores with Intel(R) Xeon(R) Gold 6138 by default i think the max is 64 anyway ERROR:80 OpenMP threads were requested. Since the non-bonded force buffer reduction is prohibitively slow with more than 64 threads, we do not allow this. Use 64 or less OpenMP threads.
Do you have an example config.xml? I can't find a good documentation about setting a default max core setting. And is this necessary if it's already max 64 threads?

@QuintenQVD0 Yes! If you set your limits to 0 it will use everything. But you can just set a percentage and it won't exceed it. You could also pin it to core 0,1 and it would only use 200% cpu

**Comment by skittles-fivem** [comment]
so on the cpus v is how many cores(threads) you want to apply to it and they dont like more then 64
<config>
  
  <slot id='0' type='CPU'/>
  <cpus v='64'/>
       
</config>

**Comment by Fuggschen** [comment]
> so on the cpus v is how many cores(threads) you want to apply to it and they dont like more then 64 [config.txt](https://github.com/parkervcp/eggs/files/11238830/config.txt) but change it to .xml github didnt like xml

Okay thanks! Thougt this is to overwrite how many cores it HAS to use. Not what it could use. Works on my 12 core and still uses only 6 in light mode. Will add this shortly

**Comment by skittles-fivem** [comment]
it auto detects it but it will attempt all cores unless changed to do so which in my case forces 1 thread since it doesnt know how many to apply

**Comment by skittles-fivem** [comment]
could add in https://apps.foldingathome.org/getpasskey for the passkey help

**Comment by Fuggschen** [comment]
> could add in https://apps.foldingathome.org/getpasskey for the passkey help

Updated. Also added Passkey and Teams to readme

**Comment by skittles-fivem** [comment]
looks good to me

**Comment by Fuggschen** [comment]
Had to fix my mail again. Panel don't want to save the changes in my mail address..

**Comment by QuintenQVD0** [comment]
jus a question. Pterodactyl does support ARM64 and you have arm64 bin so do you mind adding it? if not then that is no problem then I just do it and add the commit to this. If you want to do it yourself that is 100% fine let me know if you need some help.

a hit to get you started: `ARCH=$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")` ( you ofc can change the egg to what you need / what is the easyest for you) is normaly our switching logic to download difrend binary's. 
Note that you will have to change the install image as it is AMD64 only

**Comment by Fuggschen** [comment]
> jus a question. Pterodactyl does support ARM64 and you have arm64 bin so do you mind adding it? if not then that is no problem then I just do it and add the commit to this. If you want to do it yourself that is 100% fine let me know if you need some help.
> 
> a hit to get you started: `ARCH=$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")` ( you ofc can change the egg to what you need / what is the easyest for you) is normaly our switching logic to download difrend binary's. Note that you will have to change the install image as it is AMD64 only

Added it now. Needs testing because I don't have an ARM64 cpu but it should work just fine. It's just a change in the donwload link to 64bit or arm64

**Comment by QuintenQVD0** [comment]
> > jus a question. Pterodactyl does support ARM64 and you have arm64 bin so do you mind adding it? if not then that is no problem then I just do it and add the commit to this. If you want to do it yourself that is 100% fine let me know if you need some help.
> > a hit to get you started: `ARCH=$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")` ( you ofc can change the egg to what you need / what is the easyest for you) is normaly our switching logic to download difrend binary's. Note that you will have to change the install image as it is AMD64 only
> 
> Added it now. Needs testing because I don't have an ARM64 cpu but it should work just fine. It's just a change in the donwload link to 64bit or arm64

I confirmed this works for amd64. I will check as soon as posible for arm64

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thank you

**Pull request merged**
