### PR TITLE
The Forest - Fixed wrong Ports and other things

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### Changelog

- Fixed wrong Gameport
- added missing Query Port to config
- create config.cfg on install, to prevent starting errors
- remove not working args from startup
- switch installimage to Debian Buster-Slim

### CODE REVIEW

**Comment by chriskjpk** [comment]
Testet and it works

**Comment by Software-Noob** [comment]
Server ip:query port is intentional work around, default config has just serverip which does not work for everyone.

**Comment by gOOvER** [comment]
For me and a lot of other, your Egg don't work, because only the defaultports are used and no config is generated; so with these fixes, the Egg work.  Pls show me a log, where your egg, without changes, work ;) @Software-Noob

**Comment by BOOMtheresabanana** [comment]
Running it on pterodactyl 1.2.0, server is marked as running, and was able to see, joined, weird amount of ping seeing as I am in the same building as my server. 63m/s, but game was playable coming out of the plane. I will add more to this as I keep playing and get my friends involved.

**Pull request merged**
