### PR TITLE
Add Operation harsh doorstop

### PR DESCRIPTION
**Pull request by gimmilfactory**
# Description

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * [X] If not, why?: - **N/A**
 
## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [X] Does your egg use a custom docker image? - **N/A**
    * [X] Have you tried to use a generic image? - **N/A**
    * [X] Did you PR the necessary changes to make it work? - **N/A**
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [X] If some script is needed then it is part of a current yolk or a PR to add one - **N/A**
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
I made the base egg so you are not allowed to change the email if you edit / update one.

**Comment by QuintenQVD0** [comment]
Also keep parker install image as the pterodactyl yolks repo is not realy active so if a build fails it can be monrhs before it is fixt

**Comment by QuintenQVD0** [comment]
And dont remove the echo done at the end of the install script

**Comment by gimmilfactory** [comment]
> I made the base egg so you are not allowed to change the email if you edit / update one.

While you posted the github contribution pull request you didn't make the original egg, I was handing it out on OHD and in privet DMs way prior to your intial contribution submition; prior to figuring out how github works and making a MD document all while doing normal daily items took me a minute. This is not your original egg as I made it from scratch from my panel.

**Comment by gimmilfactory** [comment]
> And dont remove the echo done at the end of the install script

This isn't your egg, its mine and original.

**Comment by QuintenQVD0** [comment]
> > I made the base egg so you are not allowed to change the email if you edit / update one.
> 
> While you posted the github contribution pull request you didn't make the original egg, I was handing it out on OHD and in private DMs way prior to your intial contribution submition; it took me a while to figuring out how github works and making a MD document all while doing normal daily items took me a minute so yeah I'm finally posting it now. This is not your original egg as I made it from scratch from my panel and the day they annouced the game.
> 
> > Also keep parker install image as the pterodactyl yolks repo is not realy active so if a build fails it can be monrhs before it is fixt
> 
> The original contribution document says to use pterodactyl egg images over any other, first, so unless I'm instructed to by parkerbvcp, it will stay the original gneric image that pterodactyl asks you to make it with.
> 
> > And dont remove the echo done at the end of the install script
> 
> Again this is my original egg that I am submitting and it installs just fine without any added echo to the end of anything.

wow oke, sorry then. I can't remember that. what is your discord?

**Comment by gimmilfactory** [comment]
> wow oke, sorry then. I can't remember that. what is your discord?
Same as on here.

>  github even marked the first commit under my name

Huh? I'm new to github as I've stated already, only used it in the past for privately to store remote backups of code so this pull/push/request thing is new to me. Should I have made it under a total new commit? Who knows I'm new to this all as I said. Appoligies if I should have, but making 20x pull requests for the same thing seems like clutter and more work for parker so putting it under the /operation_harsh_doorstop sub branch seemed correct to me, I can't help it merged my pull request with yours - thought I was doing them speparately.

**Comment by QuintenQVD0** [comment]
> > wow oke, sorry then. I can't remember that. what is your discord?
> 
> Same as on here.
> 
> > github even marked the first commit under my name
> 
> Huh? I'm new to github as I've stated already, only used it in the past privately to store remote backups of code so this pull/push/request thing is new to me. Should I have made it under a total new commit/branch?? Who knows I'm new to this all as I said. Appoligies if I should have, but making 20x different pull requests for the same thing seems like clutter and more work for parker so putting it under the /operation_harsh_doorstop sub branch seemed correct to me, I can't help it merged my pull request with yours - thought I was doing them speparately.

No it is fine it can be 1 PR with multiple commits.
afbeelding
I never talked to you?

**Comment by gimmilfactory** [comment]
> > > wow oke, sorry then. I can't remember that. what is your discord?
> > 
> > 
> > Same as on here.
> > > github even marked the first commit under my name
> > 
> > 
> > Huh? I'm new to github as I've stated already, only used it in the past privately to store remote backups of code so this pull/push/request thing is new to me. Should I have made it under a total new commit/branch?? Who knows I'm new to this all as I said. Appoligies if I should have, but making 20x different pull requests for the same thing seems like clutter and more work for parker so putting it under the /operation_harsh_doorstop sub branch seemed correct to me, I can't help it merged my pull request with yours - thought I was doing them speparately.
> 
> No it is fine it can be 1 PR with multiple commits. afbeelding I never talked to you?

Okay so I've never talked to you . What about not talking to one another are you trying to state?

**Comment by gimmilfactory** [comment]
image
I was also talking about this OHD's discord not pterodactyl's.

**Comment by parkervcp** [comment]
As a comment on the current status of the egg. The prior PR would take precedence over this one. I hadn't got to accepting it yet.

As I see it, you both made an egg, when following the examples as laid out it makes it easy for there to be many similarities.

@gimmilfactory If you wouldn't mind, I would accept the first PR and close this one. I would appreciate a new PR from you that adds the differences you have, an example being the variables, but keeping things like using the images out of my yolks repo. Please don't update the author or the title. We don't need to call out the fact that it's a dedicated server.

Your contribution will still show up in the repo for the file.

Is this agreeable?

**Comment by gimmilfactory** [comment]
Meh.

So correct me if I'm wrong and am understanding this - So I can put up a generic, barely usebale or configurable and non-well-rounded server egg setup, and I get firsties??? So I can start doing that with every dedicated server that doesn't yet exist and no one will call me out on it and it gets accepted as me being the original creator of the egg? Hmm that kinda seems lop-sided.

**Comment by QuintenQVD0** [comment]
> Meh.
> 
> So correct me if I'm wrong and am if I'm understanding this incorrectly - I can put up a generic, barely usebale or configurable and non-well-rounded server egg setup, and I get firsties??? So I can start doing that with every dedicated server that doesn't yet exist and no one will call me out on it and it gets accepted as me being the original creator of the egg? Hmm that kinda seems lop-sided.

The egg started the server without any  errors and it follow there docs. The egg did the basics. Install a server, handle updates, set the port and let the user configure the basics. I tested that and that worked. I see your egg has more bells and whistles but mine did work. That is wy Parker sugesged my egg gets merged as it was the first functional. Then you make a new pr the changes you think are needed. If there are fundemental this not working in my egg then feel free to comment on the pr. I get that you are upsed that your name will not be on the egg. But still as your then "update" pr was the latest girhub will still show it as it is thr most recent commit to that egg then. 

Or for my part I close this pr., push a commit to this pr to finish the egg to our standards (echo done, parker image) that are small things and we set the email of the egg to a unknown@unknow.com. then the pr is made by you. I co author it and no one gets the email credit. Up to you

**Comment by gimmilfactory** [comment]
> > Meh.
> > So correct me if I'm wrong and am if I'm understanding this incorrectly - I can put up a generic, barely usebale or configurable and non-well-rounded server egg setup, and I get firsties??? So I can start doing that with every dedicated server that doesn't yet exist and no one will call me out on it and it gets accepted as me being the original creator of the egg? Hmm that kinda seems lop-sided.
> 
> The egg started the server without any errors and it follow there docs. The egg did the basics. Install a server, handle updates, set the port and let the user configure the basics. I tested that and that worked. I see your egg has more bells and whistles but mine also did work. That is wy Parker sugesged my egg gets merged as it was the first functional. Then you make a new pr the changes you think are needed. If there are fundemental this not working in my egg then feel free to comment on the pr. I get that you are upsed that your name will not be on the egg. But still as your then "update" pr was the latest girhub will still show it as it is thr most recent commit to that egg then.
> 
> Or for my part I close my pr., push a commit to this pr to finish the egg to our standards (echo done, parker image) that are small things and we set the email of the egg to a [unknown@unknow.com](mailto:unknown@unknow.com). then the pr is made by you. I co author it and no one gets the email credit. Up to you

I think you're misunderstanding the 'meh' and my reply - That wasn't a no, it was a  'its your project do as you wish'. 

You want your name on it that bad that's on you, be my guest. Yeah it'd be nice to have my name as author of it, as you have how many eggs to your name? Pf

Yeah I'm late to the party cos it took me time to learn github before attempting pull a request. I made my egg on Feburary 27th and chose to hold on to it and properly do all of the nesseasry testing before posting it so I could also eventually get around to learning github; guess me being late to the game means someone else gets the main credit; not the one who actually took the time to go from start to finish on a well rounded and optimially featured and well tested product before submitting it to the public for them to have.

I'll close this and submit everything within yours once I can figure out how to. This system is all new to me so - yeah, I had to take my time and end up get a stick for my efforts. Would be nice to actually feel like I made something end-to-end, as well, I did.

**Comment by QuintenQVD0** [comment]
> > > Meh.
> > > So correct me if I'm wrong and am if I'm understanding this incorrectly - I can put up a generic, barely usebale or configurable and non-well-rounded server egg setup, and I get firsties??? So I can start doing that with every dedicated server that doesn't yet exist and no one will call me out on it and it gets accepted as me being the original creator of the egg? Hmm that kinda seems lop-sided.
> > 
> > 
> > The egg started the server without any errors and it follow there docs. The egg did the basics. Install a server, handle updates, set the port and let the user configure the basics. I tested that and that worked. I see your egg has more bells and whistles but mine also did work. That is wy Parker sugesged my egg gets merged as it was the first functional. Then you make a new pr the changes you think are needed. If there are fundemental this not working in my egg then feel free to comment on the pr. I get that you are upsed that your name will not be on the egg. But still as your then "update" pr was the latest girhub will still show it as it is thr most recent commit to that egg then.
> > Or for my part I close my pr., push a commit to this pr to finish the egg to our standards (echo done, parker image) that are small things and we set the email of the egg to a [unknown@unknow.com](mailto:unknown@unknow.com). then the pr is made by you. I co author it and no one gets the email credit. Up to you
> 
> I think you're misunderstanding the 'meh' and my reply - That wasn't a no, it was a 'its your project do as you wish'.
> 
> You want your name on it that bad that's on you, be my guest. Yeah it'd be nice to have my name as author of it, as you have how many eggs to your name? Pf
> 
> Yeah I'm late to the party cos it took me time to learn github before attempting pull a request. I made my egg on Feburary 27th and chose to hold on to it and properly do all of the nesseasry testing before posting it so I could also eventually get around to learning github; guess me being late to the game means someone else gets the main credit; not the one who actually took the time to go from start to finish on a well rounded and optimially featured and well tested product before submitting it to the public for them to have.
> 
> I'll close this and submit everything within yours once I can figure out how to. This system is all new to me so - yeah, I had to take my time and end up get a stick for my efforts. Would be nice to actually feel like I made something end-to-end, as well, I did.

I honestly don't care if my name is on it. I don't want publicity. I just like making eggs. And reading all this you where first. You just had to learn git. As at a further look my egg indeed barly works. So i would like to put your email in my pr. And then you you can make a 2nd pr with your changes with your mail already on it as I already sort if have to deal with all egg issues in this repo. Then I would like to help you with your 2nd pr. Everyone has to learn. Even i wss hell of confused ad first with the first commit to this repo and false accused you

**Comment by parkervcp** [comment]
> > > Meh.
> > > So correct me if I'm wrong and am if I'm understanding this incorrectly - I can put up a generic, barely usebale or configurable and non-well-rounded server egg setup, and I get firsties??? So I can start doing that with every dedicated server that doesn't yet exist and no one will call me out on it and it gets accepted as me being the original creator of the egg? Hmm that kinda seems lop-sided.
> > 
> > 
> > The egg started the server without any errors and it follow there docs. The egg did the basics. Install a server, handle updates, set the port and let the user configure the basics. I tested that and that worked. I see your egg has more bells and whistles but mine also did work. That is wy Parker sugesged my egg gets merged as it was the first functional. Then you make a new pr the changes you think are needed. If there are fundemental this not working in my egg then feel free to comment on the pr. I get that you are upsed that your name will not be on the egg. But still as your then "update" pr was the latest girhub will still show it as it is thr most recent commit to that egg then.
> > Or for my part I close my pr., push a commit to this pr to finish the egg to our standards (echo done, parker image) that are small things and we set the email of the egg to a [unknown@unknow.com](mailto:unknown@unknow.com). then the pr is made by you. I co author it and no one gets the email credit. Up to you
> 
> I think you're misunderstanding the 'meh' and my reply - That wasn't a no, it was a 'its your project do as you wish'.
> 
> You want your name on it that bad that's on you, be my guest. Yeah it'd be nice to have my name as author of it, as you have how many eggs to your name? Pf
> 
> Yeah I'm late to the party cos it took me time to learn github before attempting pull a request. I made my egg on Feburary 27th and chose to hold on to it and properly do all of the nesseasry testing before posting it so I could also eventually get around to learning github; guess me being late to the game means someone else gets the main credit; not the one who actually took the time to go from start to finish on a well rounded and optimially featured and well tested product before submitting it to the public for them to have.
> 
> I'll close this and submit everything within yours once I can figure out how to. This system is all new to me so - yeah, I had to take my time and end up get a stick for my efforts. Would be nice to actually feel like I made something end-to-end, as well, I did.

While I understand the feeling you have that "first come first serve" is how I am approaching this. Please understand that I accept PR's that have a working server, even if they are not perfect. This is why I welcome PR's to update and correct things. Had I accepted the prior PR before this, that is all this would have been.

If you need help with making edits and PR's I am perfectly willing to work with you on that.

**Pull request closed without merging**
