### PR TITLE
Add Config Download to Nukkit

### LINKED ISSUE #38: Nukkit Config Parsing Issue
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.6
Daemon Version: 0.5.5
New Service: no
Service: Nukkit
Modified: no

Expected Behavior: Install server and set the server-port to {{server.build.default.port}} via config parsing.

Actual Behavior: Installs server and server-port is set to default nukkit port

Steps to Reproduce: Install nukkit server and check server.properties to see if the port set correctly.

### PR DESCRIPTION
**Pull request by wraith1200**
Resolves #38

### CODE REVIEW

**Comment by parkervcp** [comment]
@wraith1200 It looks good but you are missing the nukkit.yml in the repo and the script will fail when you try to run it.

**Comment by wraith1200** [comment]
@parkervcp Where is it missing the nukkit.yml? It is in the repo and listed in the eggs install script. Both get pulled down when I tested the script. I didn't make any changes to that so it won't be merging that part.

**Comment by parkervcp** [comment]
@wraith1200 It's not listed as a file in the files changed section. It should be if you added it before subbing the PR.

**Comment by wraith1200** [comment]
@parkervcp Right because there was no changes at all to the nukkit.yml as no changes were needed. It is identical to the one in your repo as seen in my fork https://github.com/wraith1200/eggs/tree/master/Minecraft%20PE/nukkit

**Comment by parkervcp** [comment]
For some reason I swear that wasn't there before.

**Pull request merged**
