### PR TITLE
Adds support for steam accounts,

### PR DESCRIPTION
**Pull request by GreenDiscord**
# Description
Added due to the fact that some hlds depenendent games require the user to log into an account
These games inlcude cstrike and ricochet (from my knowledge).

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Review by parkervcp — DISMISSED** [review]
this could break if a password is set with no username and vice versa.

This "should" work 
```bash
if [ "${STEAM_USER}" == "" ] || [ "${STEAM_PASS}" == "" ]; then
    STEAM_USER=anonymous
    STEAM_PASS=""
    STEAM_AUTH=""
fi
```

**Comment by GreenDiscord** [comment]
Sure, Changing now

**Comment by GreenDiscord** [comment]
Updated, hope its fine now

**Comment by parkervcp** [comment]
@GreenDiscord Did you validate that it worked?

**Comment by GreenDiscord** [comment]
image

**Comment by GreenDiscord** [comment]
image

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thx

**Pull request merged**
