### PR TITLE
Updated download url for tf2c mod

### PR DESCRIPTION
**Pull request by xterm-inator**
# Description

Updating the download url for tf2 classic mod as it has changed.
Changing from: https://wiki.tf2classic.com
To: https://tf2classic.org/tf2c

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You need to change the whole egg not just the install script. Upload the whole exported egg

**Comment by xterm-inator** [comment]
This is updating an existing egg, nothing else has updated in the egg.

**Comment by parkervcp** [comment]
> This is updating an existing egg

While it is existing manually updating the json can break the formatting. I request that you edit the file in the panel and export the whole file. It will update the edit date and over values as well.

**Comment by xterm-inator** [comment]
no worries, I committed the full export from the panel. Hope that is what is needed :)

**Comment by QuintenQVD0** [comment]
I made some extra changes like moving the install script to one of our own images , remove the apt install cmd as this is not needed, change to curl to downloading the bin and add a echo install finished to the end
I also added that the default version should be latest

**Comment by xterm-inator** [comment]
Nice, I'll do some testing with changes

**Comment by QuintenQVD0** [comment]
> Nice, I'll do some testing with changes

let me know if it works then I merge it

**Comment by xterm-inator** [comment]
> let me know if it works then I merge it

Fixed an issue with the latest server version not starting, but all works now 👍

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! Tahnk you

**Pull request merged**
