### PR TITLE
Add/Eco Server

### PR DESCRIPTION
**Pull request by gOOvER**
New PR for ECO Server. Original Author deleted his Account

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [x] Does your server use a custom docker image?
    * [x] Have you tried to use a generic image?
    * [x] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
Need to update the main readme too

**Comment by gOOvER** [comment]
done :) My fault. I only use old files :)

**Comment by parkervcp** [comment]
In the main readme please put this under the "steamcmd server" section

**Comment by gOOvER** [comment]
done

**Comment by parkervcp** [comment]
We can probably update the install script as well to use this one - https://github.com/parkervcp/eggs/blob/master/scripts/steamcmd_installer.sh

The server start command should use absolute paths for mono also. So startup command should be `/usr/bin/mono ./EcoServer.exe -nogui`

**Comment by gOOvER** [comment]
Ok, updated the Startup command and the Installscript

**Comment by parkervcp** [comment]
Needs a variable for the STEAM_USER, STEAM_PASS, and STEAM_AUTH

**Comment by gOOvER** [comment]
Is this really needed? it works with anonymous

**Comment by parkervcp** [comment]
It wouldn't let me install the server with anon.

**Comment by gOOvER** [comment]
funny. I installed the server. For steam not everytime steam user is needed ;)

**Comment by parkervcp** [comment]
My script sets the account to anon if there is no user set.

**Comment by gOOvER** [comment]
Then u must be able to  install. I use your install Script

**Comment by gOOvER** [comment]
before i change the script it works and then it should work after i change the script to the one u told me

**Comment by gOOvER** [comment]
mb it's like ur PixArc egg. A lot of people can't install; the only one is u ;)

**Comment by gOOvER** [comment]
@parkervcp i can't confirm, that it not work, when u not add a Steam User.

- I deleted the Server in Ptero 
- then i removed the Egg. 
- restarted the deamon 
- and upload this Egg again.
- Deamon restart
- Create a new Server

Server install was without Errors and i can connect to the Server.

Egg works fine

I do the same on en other Ptero install, also without using a Steamuser and Server was installed without errors

**Comment by gOOvER** [comment]
See also ECO Server WIKI:

> MANUALLY
>Guide to downloading cthe server manually through SteamCMD: Double Click the steamcmd.exe >Wait until it finishes updating and deploying SteamCMD Once loaded login by typing in:

>login `anonymous

**Comment by parkervcp** [comment]
I re-upped the egg and I get hung on this - `Connecting anonymously to Steam Public...Logged in OK` followed by a `Waiting for user info...FAILED. Timed out.`

**Comment by gOOvER** [comment]
Maybe that helps:
https://steamcommunity.com/discussions/forum/11/1646544161774102517/
https://github.com/ValveSoftware/steam-for-linux/issues/6326

**Comment by gOOvER** [comment]
Updated Egg to use Debian Buster Slim. MB this fix the login issue

**Comment by parkervcp** [comment]
All right. After a system update on my server it looks like it's working.

**Pull request merged**
