### PR TITLE
Update egg-phantom-bot.json

### PR DESCRIPTION
**Pull request by Fuggschen**
# Description

Edited variables because PhantomBot now has a setup page and they are no longer needed. It is recommended to use the setup page after first install. Users on PB Discord are also complaining that their keys are overwritten by the panel so removing them as variables from the panel would fix that too.

Tested the egg on my own instance as an update and as a new egg. Both works fine for me but new bot maybe needs additional testing. I just checked if the setup panel shows up and writes data to the config.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by parkervcp** [comment]
@Fuggschen I feel like there should be a way to bypass the setup pages if you set the values before it starts.

**Comment by Fuggschen** [comment]
> @Fuggschen I feel like there should be a way to bypass the setup pages if you set the values before it starts.

Sorry for late reply. Yeah I could skip it like you do if you just update the bot and have a prefilled botlogin.txt. I have to work something out in bash to setup the file only on install and do nothing with it if it exist and remove the configfile part so it wont be replaced on every start

**Comment by QuintenQVD0** [comment]
> > @Fuggschen I feel like there should be a way to bypass the setup pages if you set the values before it starts.
> 
> Sorry for late reply. Yeah I could skip it like you do if you just update the bot and have a prefilled botlogin.txt. I have to work something out in bash to setup the file only on install and do nothing with it if it exist and remove the configfile part so it wont be replaced on every start

you can always just use bash to check if a file exists like:
```sh
FILE=/mnt/server/botlogin.txt
if [[ ! -f  $FILE]]
then
    echo "$FILE does not exist on your filesystem."
fi
```
I think you can figure out yourself on how to use this

**Comment by Fuggschen** [comment]
> > > @Fuggschen I feel like there should be a way to bypass the setup pages if you set the values before it starts.
> > 
> > 
> > Sorry for late reply. Yeah I could skip it like you do if you just update the bot and have a prefilled botlogin.txt. I have to work something out in bash to setup the file only on install and do nothing with it if it exist and remove the configfile part so it wont be replaced on every start
> 
> you can always just use bash to check if a file exists like:
> 
> ```shell
> FILE=/mnt/server/botlogin.txt
> if [[ ! -f  $FILE]]
> then
>     echo "$FILE does not exist on your filesystem."
> fi
> ```
> 
> I think you can figure out yourself on how to use edit this to your needs

Yeah sure! But I also have to modify the file in order to setup the bot if the user passes the key on installation etc. I'll figure it out. There are plenty eggs where I can look at how to do this lol

**Comment by Fuggschen** [comment]
Okay totally didn't saw that the oauth keys aren't set by the panel. Wouldn't make any sense to force the user to edit the file via the editor when he could do it like now with the panel. And seems that the bug with the keys was some user error.

Closed

**Pull request closed without merging**
