### PR TITLE
Added Waterfall, Paper/Taco Spigot

### PR DESCRIPTION
**Pull request by rouing**
Added Waterfall
Added Paper Spigot
Added Taco Spigot

### CODE REVIEW

**Comment by parkervcp** [comment]
Can we rename these to just waterfall, taco-spigot, and paper-spigot? Other than that I am mostly okay with these.

**Comment by rouing** [comment]
@parkervcp Done, Done, and Done.

**Comment by parkervcp** [comment]
The taco-spigot egg fails to import because the config options are all null.

If you used the "copy settings from" there may be a bug that I will be testing for now.

**Comment by rouing** [comment]
Yeah, they are cascading copy settings from. Taco from Paper from regular.

**Comment by rouing** [comment]
Should I isolate those? I planned on improving configs on both later but make the config changes per fork so it wouldn't be duplicate changes everywhere.

**Comment by parkervcp** [comment]
Isolate them. Easiest fix there is right now.

**Comment by rouing** [comment]
I will do that.

**Comment by rouing** [comment]
Isolated.

**Comment by rouing** [comment]
annnnnnnnd it added it to the pull request. Not sure you want that license in there or not, but if you are ok with it then I will leave it. If not, I will remove it.

**Pull request merged**
