### PR TITLE
Add SCP: Secret Laboratory Server

### PR DESCRIPTION
**Pull request by bbenance**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
Does your server use a custom docker image? - No
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by parkervcp** [comment]
@bbenance I already have a branch for this PR to that one

**Comment by parkervcp** [comment]
The install/startup for this is failing for a missing executable.

**Comment by parkervcp** [comment]
Closing in favor of #237

**Comment by Archerfy** [comment]
This is not working if you have Steam Mobile Guard enabled.
The code will expire in a few seconds and the install script isn't that fast before the new code appears.
When the code expired the install script will fail and the game is not going to be installed because of the Steam Guard code

**Comment by parkervcp** [comment]
@Archerfy Please not this was closed in July. That is an issue for all steam games.

**Pull request closed without merging**
