### PR TITLE
Update PocketMine to use PHP 7.4

### PR DESCRIPTION
**Pull request by RealTriassic**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?

### CODE REVIEW

**Comment by ItzLightyHD** [comment]
I hope they submit the pull request

**Comment by gOOvER** [comment]
Better test Egg in Panel, export it and the commit it. You only change it here in Github

**Comment by gOOvER** [comment]
And you do not fill out the Forms; in my Eye, this PR can be closed

**Comment by parkervcp** [comment]
You need to fill out the forms here. I ask very little when you submit a change.

**Pull request closed without merging**
