### PR TITLE
Add/5e tools

### PR DESCRIPTION
**Pull request by Gorian**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by tmunsch** [comment]
Can't import the egg to even test, Gives invalid JSON error.

**Comment by parkervcp** [comment]
@Gorian This fails to import please look into it.

**Comment by CutestNekoAqua** [comment]
@parkervcp Works on my end. Using this file on a fresh install.
[egg-5e-tools.json.txt](https://github.com/parkervcp/eggs/files/8383424/egg-5e-tools.json.txt)

**Comment by CutestNekoAqua** [comment]
Could start it without any issues while setting it up.

**Review by parkervcp — APPROVED** [review]

**Comment by Wolbaz** [comment]
Fails to import, invalid JSON

**Comment by Wolbaz** [comment]
1.8.1

**Pull request merged**
