### PR TITLE
Updating FiveM egg to support OneSync and have up to 128 players

### PR DESCRIPTION
**Pull request by DoJoMan18**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)? Yes
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md? 
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them? Yes
2. [x] Have you tested your Egg changes? Yes

### CODE REVIEW

**Comment by parkervcp** [comment]
As far as I know this is still a paid feature. Adding a variable and making it a default will either get people complaining that it isn't working on they are stuck at 32 people max when they set it higher than that.

**Comment by DoJoMan18** [comment]
If they don't have the correct license to use OneSync it isn't going to work. That is also the reason that OneSync is switch off at default. However I can add a disclaimer in the discripting to inform the people that they need a specific license before OneSync and/or the users above 32 is going to work. 

If they configure OneSync and set the player limit above 32 without the correct license the server will start up without any problem.

**Comment by parkervcp** [comment]
I don't want to deal with the fallout from that. I also believe OneSync is still a beta feature.

**Comment by parkervcp** [comment]
this is gonna be a no for now. Wait until onesync is at least out of beta.

**Pull request closed without merging**
