### PR TITLE
Add/path of titans

### PR DESCRIPTION
**Pull request by Rage-GitHub**
### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by gOOvER** [comment]
i dont think, that WISP exported eggs are compatible with ptero after a quick look

**Comment by Rage-GitHub** [comment]
> i dont think, that WISP exported eggs are compatible with ptero after a quick look
> 
> WISP and Ptero are technical different systems

Ahhhh, crap that's my bad. I didn't think of that. :|

**Comment by Software-Noob** [comment]
It's not trivial to convert. I can do it later if no one else does it before me

**Comment by Rage-GitHub** [comment]
> It's not trivial to convert. I can do it later if no one else does it before me

Would be much appreciated.

**Comment by QuintenQVD0** [comment]
I convert it to a ptero one but it now has my E-mail on it, if that is a problem feel free to change it back to the email from the wisp egg author. I can not test the egg as I do not own the game. Can somebody (@Rage-GitHub) test this on ptero?

```json
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
    "exported_at": "2022-08-08T12:13:13+02:00",
    "name": "Path of Titans",
    "author": "josdekurk@gmail.com",
    "description": "Path of Titans is an MMO dinosaur video game currently in active development for home computers and mobile devices fully compatible with cross platform play. Play as one of 18 core dinosaurs in a rich ecosystem filled with complex AI creatures and up to 200 other players.",
    "features": null,
    "docker_images": {
        "ghcr.io\/parkervcp\/games:source": "ghcr.io\/parkervcp\/games:source"
    },
    "file_denylist": [],
    "startup": ".\/PathOfTitans\/Binaries\/Linux\/PathOfTitansServer-Linux-Shipping -log -MULTIHOME=000.000.000 -Port={{SERVER_PORT}} -BranchKey={{BRANCH_TYPE}} -AuthToken={{AUTH_TOKEN}} -ServerGUID={{SERVER_GUID}} -Database={{DATABASE_TYPE}}",
    "config": {
        "files": "{}",
        "startup": "{}",
        "logs": "{}",
        "stop": "^C"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\napt -y update\r\napt -y --no-install-recommends --no-install-suggests install curl lib32gcc-s1 ca-certificates\r\n\r\n# Installation dependencies to make it work\r\napt-get install wget -y\r\n\r\napt-get install -y libicu-dev\r\n\r\n# Temporary file directory for installation\r\nmkdir -p \/mnt\/server\r\ncd \/mnt\/server\r\n\r\n# Pulling necessary file to begin server installation\r\nwget https:\/\/launcher-cdn.alderongames.com\/AlderonGamesCmd-Linux-x64\r\n\r\n# Setting that file as an executable\r\nchmod u+x AlderonGamesCmd-Linux-x64\r\n\r\n# Running server installation and downloading necessary files\r\necho Updating Server Files\r\n.\/AlderonGamesCmd-Linux-x64 --game path-of-titans --server true --beta-branch $BRANCH_TYPE --auth-token $AUTH_TOKEN\r\n\r\n# Setting startup executable permissions\r\ncd .\/PathOfTitans\/Binaries\/Linux\/\r\nchmod u+x PathOfTitansServer-Linux-Shipping\r\n\r\necho \"Done\"",
            "container": "ghcr.io\/parkervcp\/installers:debian",
            "entrypoint": "bash"
        }
    },
    "variables": [
        {
            "name": "Server GUID",
            "description": "Set a randomly generated GUID for the server. Has to be unique. https:\/\/www.guidgenerator.com\/",
            "env_variable": "SERVER_GUID",
            "default_value": "00000000-0000-0000-0000-000000000000",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|max:120",
            "field_type": "text"
        },
        {
            "name": "Auth Token",
            "description": "Requires an Auth Token generated from the Alderon Games website. https:\/\/alderongames.com\/oauth\/hosting-token",
            "env_variable": "AUTH_TOKEN",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string",
            "field_type": "text"
        },
        {
            "name": "Branch Type",
            "description": "Sets the branch type of the game to be installed. Valid types are \"demo-public-test\" and \"production\".",
            "env_variable": "BRANCH_TYPE",
            "default_value": "production",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|in:production,demo-public-test",
            "field_type": "text"
        },
        {
            "name": "Database Type",
            "description": "Sets the database type on whether to be local or remote.",
            "env_variable": "DATABASE_TYPE",
            "default_value": "local",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|in:local,remote",
            "field_type": "text"
        }
    ]
}
```

**Comment by gOOvER** [comment]
@QuintenQVD0 . Open the Egg in an Editor and Change the eMail :)

**Comment by parkervcp** [comment]
So I am reading that this was made on a wisp panel and exported from there?

**Comment by QuintenQVD0** [comment]
> So I am reading that this was made on a wisp panel and exported from there?

As far as I could understand it yes, Then I move it over to a ptero egg. Should I as author set my Email or the original from wisp?

**Comment by Software-Noob** [comment]
> > As far as I could understand it yes, Then I move it over to a ptero egg. Should I as author set my Email or the original from wisp?
> 
> email from wisp is their teams address because the panels are set up by their automation

WISP author email for new eggs is the default unknown@unknown.com since it doesn't matter. OP used another egg as a template.

**Comment by Rage-GitHub** [comment]
> > > As far as I could understand it yes, Then I move it over to a ptero egg. Should I as author set my Email or the original from wisp?
> > 
> > 
> > email from wisp is their teams address because the panels are set up by their automation
> 
> WISP author email for new eggs is the default [unknown@unknown.com](mailto:unknown@unknown.com) since it doesn't matter. OP used another egg as a template.

If you're talking about an already created egg was used to make this one, you're wrong. This was fully created from scratch. Not sure where you got the idea another egg was used as a template.

**Comment by Software-Noob** [comment]
> > > > As far as I could understand it yes, Then I move it over to a ptero egg. Should I as author set my Email or the original from wisp?
> > > 
> > > 
> > > email from wisp is their teams address because the panels are set up by their automation
> > 
> > WISP author email for new eggs is the default [unknown@unknown.com](mailto:unknown@unknown.com) since it doesn't matter. OP used another egg as a template.
> 
> If you're talking about an already created egg was used to make this one, you're wrong. This was fully created from scratch. Not sure where you got the idea another egg was used as a template.

It's obvious based on the egg author email. It doesn't matter. I actually recommend using other eggs to save time.

**Comment by Rage-GitHub** [comment]
> > > > > As far as I could understand it yes, Then I move it over to a ptero egg. Should I as author set my Email or the original from wisp?
> > > > 
> > > > 
> > > > email from wisp is their teams address because the panels are set up by their automation
> > > 
> > > 
> > > WISP author email for new eggs is the default [unknown@unknown.com](mailto:unknown@unknown.com) since it doesn't matter. OP used another egg as a template.
> > 
> > 
> > If you're talking about an already created egg was used to make this one, you're wrong. This was fully created from scratch. Not sure where you got the idea another egg was used as a template.
> 
> It's obvious based on the egg author email. It doesn't matter. I actually recommend using other eggs to save time.

I can assure you that's not the case, but doesn't matter. The egg should've been pushed under my email.

**Comment by killertobyd** [comment]
Hi
I have tried to use the Egg but even if you specify all the things in the variables, the server does not want to

**Comment by QuintenQVD0** [comment]
> Hi I have tried to use the Egg but even if you specify all the things in the variables, the server does not want to

Post here install logs and the startup error, I dont own the game so I can noy test it

**Comment by QuintenQVD0** [comment]
@Rage-GitHub Please convert the you you try to PR to a pterodactyl egg with your Email or use the egg I comment with the Email `unknown@unknown.com`.  This PR will be closed if  you not react or your not willing / have time to do any of the 2 options I asked.

Thx

**Comment by Jerry304** [comment]
while running the server from this it stays stuck on Starting........but it does go live....it just doesnt say......also i been looking at the configs.....trying to add mods but so far no luck...

**Comment by parkervcp** [comment]
> stays stuck on Starting

This is because it's startup config isn't set.

**Pull request closed without merging**
