### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nateloeffel**
Important clarification that git config must be setup when the server is created and will not work correctly if setup afterwards.

# Description
Clarifies that you MUST setup the github credentials and the repository to pull from when you are creating the server, the feature will not work if you do it once the server is already installed.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by Software-Noob** [comment]
This is not entirely correct. The GitHub repository is cloned during the initial installation process. Therefore, if new credentials are provided afterward, a server reinstallation will be necessary

**Comment by nateloeffel** [comment]
right, as opposed to just restarting the server

**Comment by nateloeffel** [comment]
See if that looks better.

**Comment by QuintenQVD0** [comment]
No one reads those README.md anyways. And there are a lot of more eggs (all generic) that use this script and logic.

**Comment by nateloeffel** [comment]
It still appears confusing to someone who is using it for the first time. This way when they are confused why their server isn't cloning they can understand why.

**Comment by QuintenQVD0** [comment]
> It still appears confusing to someone who is using it for the first time. This way when they are confused why their server isn't cloning they can understand why.

end users will never read this, only admins and they also wont so I don't find this needed

**Comment by QuintenQVD0** [comment]
This is not realy needed, most uses know that and else they will come to the discord. There are a lot of eggs that use this logic and no one reads the README.md file anyway.

**Pull request closed without merging**
