### PR TITLE
Update egg-counter--strike--global-offensive.json

### PR DESCRIPTION
**Pull request by robingroppe**
- Added -usercon to startup command due to remote rcon not working.

- Made GSLT not required, serverproviders are unable to generate a GSLT for their "customers" and the server is starting anyway in LAN-mode with a message saying to obtain a GSLT.

- Added tick and gamemodes variables

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
First, you didn't check any boxes confirming anything.
Second, I specifically fight against adding max_players so servers.

**Comment by robingroppe** [comment]
Edited, whats the reason for fightig against max_players? 
There is no other way to restrict the number of players for the server admin.
But the really urgent issue is the missing -usercon and the non nullable gslt.

Shall I remove the max players?

**Comment by parkervcp** [comment]
Please remove the max_players.

Also it looks like our install scripts are now conflicting.

**Comment by parkervcp** [comment]
@robingroppe Can you update to use my new install script please?

**Comment by parkervcp** [comment]
@robingroppe It's been over 3 months I will close this out later today if needed.

**Pull request closed without merging**
