### PR TITLE
Added Tower Unite

### PR DESCRIPTION
**Pull request by NgLoader**
### All Submissions:

* [Yes] Have you followed the guidelines in our Contributing document?
* [Yes] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Server Submissions:

1. [Yes] Does your submission pass tests (server is connectable)?
2. [No] Does your server use a custom docker image?
    * [-] Have you tried to use a generic image?
    * [-] Did you PR the nesessary changes to make it work?
3. [Yes] Have you added the server to the main README.md?
4. [Yes] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by Sir3lit** [comment]
I'd recommend changing to an alpine image for the install image. To save space on the server.

**Comment by schrej** [comment]
Isn't that game called *Tower Unite*?
http://www.towerunite.com/

**Comment by NgLoader** [comment]
Yea

**Comment by NgLoader** [comment]
Yea, @schrej

**Comment by schrej** [comment]
You should fix the name then ;)

**Comment by schrej** [comment]
In the egg itself as well.

**Pull request merged**
