### PR TITLE
Fixed version parsing that was stopping installations

### PR DESCRIPTION
**Pull request by blastehh**

### CODE REVIEW

**Comment by parkervcp** [comment]
I was actually working on a fix for this already.

**Comment by blastehh** [comment]
Only needed to add linebreaks to the returned version list for grep to work, it was all json in a single line.

**Comment by parkervcp** [comment]
I am working on a bit cleaner way as it's json and there are tools to handle this better.

**Comment by parkervcp** [comment]
@blastehh I have an update for this. I will be using jq. The glibc image I use for installing is also updated for this change.

**Pull request closed without merging**
