### PR TITLE
Valheim BepInEx mod egg update

### PR DESCRIPTION
**Pull request by HoleInTheSeat**
# Description

Allows for mods to automatically be downloaded using modpack dependencies form https://valheim.thunderstore.io/

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: I forgot this step, should I go back and do that?

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by gOOvER** [comment]
Oh nice. Wanted to do the same, but never find the time :) I will test your egg asap :)

**Comment by HoleInTheSeat** [comment]
> Oh nice. Wanted to do the same, but never find the time :) I will test your egg asap :)

Any Issues?

**Comment by HoleInTheSeat** [comment]
> sry, dont had time. IUntil next week i cant test it, since I visit my daughters

No worries thanks.

**Comment by HoleInTheSeat** [comment]
I have been using this egg as my egg to run my server for 3.5 days now without issue. I've tested starting the server with and without a modpack listed. I believe I have tested everything Very thoroughly.

**Comment by QuintenQVD0** [comment]
> I have been using this egg as my egg to run my server for 3.5 days now without issue. I've tested starting the server with and without a modpack listed. I believe I have tested everything Very thoroughly.

we need someone external to confirm this.

**Comment by trentnbauer** [comment]
G'day mate,
I've tested the egg without specifying a modpack and I can join the server
I've tested the egg with a modpack and can confirm it downloads the files and the server is joinable

Another thing to note, and already mentioned in the discord:
Goover's original Bepinex egg is broken due to Mono misconfiguration, error below:
This has been fixed in this egg:)
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/games 
Digest: sha256:4870805cb87b1028a4369fa0ef36dc056bd660affcf1dd5ebe277788eedb533b 
Status: Image is up to date for ghcr.io/parkervcp/games:valheim 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1698778122
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '896660' already up to date.
:/home/container$ export DOORSTOP_ENABLE=TRUE; export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll; export DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib; export LD_LIBRARY_PATH="./doorstop_libs:$LD_LIBRARY_PATH"; export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"; export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH="./linux64:$LD_LIBRARY_PATH"; export SteamAppId=892970; export LD_LIBRARY_PATH=$templdpath; ./valheim_server.x86_64 -nographics -batchmode -name "${SERVER_NAME}" -port ${SERVER_PORT} -world "${WORLD}" -password "${PASSWORD}" -public ${PUBLIC_SERVER} -saveinterval ${BACKUP_INTERVAL} -backups ${BACKUP_COUNT} -backupshort ${BACKUP_SHORTTIME} -backuplong ${BACKUP_LONGTIME} $( [[ ${ENABLE_CROSSPLAY} -eq 1 ]] && echo " -crossplay ") > >(sed -uE "${CONSOLE_FILTER}") & trap "${STOP}" 15; wait $!
Failed to hook dlsym, ignoring it. Error: no such function: dlsym
Found UnityPlayer, hooking into it instead
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/container/valheim_server_Data/Managed'
Mono config path = '/home/container/valheim_server_Data/MonoBleedingEdge/etc'
Got override: ./unstripped_corlib
Current root dir: /home/container/valheim_server_Data/Managed
New root path: /home/container/unstripped_corlib
Search path: /home/container/unstripped_corlib:/home/container/valheim_server_Data/Managed
Setting config paths; basedir: /home/container; config: /home/container/valheim_server.x86_64.config
Managed dir: /home/container/valheim_server_Data/Managed
Fallback handler could not load library /home/container/valheim_server_Data/MonoBleedingEdge/x86_64/P�ҿ�U/mono/aot-cache/amd64/BepInEx.Preloader.dll.so
Got image: 0x55bfbfd2dc90 
cant resolve internal call to "System.Threading.Interlocked::CompareExchange(T&,T,T)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.Threading.Thread::GetCurrentThread()" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.Threading.Interlocked::CompareExchange(T&,T,T)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "Mono.SafeStringMarshal::StringToUtf8(string)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "Mono.SafeStringMarshal::StringToUtf8(string)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.MissingMemberException::FormatSignature" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.Reflection.MemberInfo::get_MetadataToken" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/container/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
Caught fatal signal - signo:11 code:1 errno:0 addr:0x20
Obtained 46 stack frames.
#0  0x007f6d7a190520 in __sigaction
#1  0x007f6d770c02e1 in mono_install_ftnptr_eh_callback
#2  0x007f6d770c1477 in mono_install_ftnptr_eh_callback
#3  0x00000041320516 in (Unknown)
#4  0x00000040ba8807 in System.Diagnostics.StackTrace:GetFullNameForStackTrace (System.Text.StringBuilder,System.Reflection.MethodBase)
#5  0x00000040ba6e47 in System.Diagnostics.StackTrace:AddFrames (System.Text.StringBuilder)
#6  0x00000040ba6bbb in System.Diagnostics.StackTrace:ToString ()
#7  0x00000040ba6ac0 in System.Diagnostics.StackTrace:ToString (System.Diagnostics.StackTrace/TraceFormat)
#8  0x00000040ba6833 in System.Environment:GetStackTrace (System.Exception,bool)
#9  0x00000040ba676b in System.Exception:GetStackTrace (bool)
#10 0x00000040ba60df in System.Exception:ToString (bool,bool)
#11 0x00000040ba5e17 in System.Exception:ToString ()
#12 0x00000040ba5ea5 in (wrapper runtime-invoke) <Module>:runtime_invoke_object__this__ (object,intptr,intptr,intptr)
#13 0x00000040ba5b5b in (wrapper managed-to-native) Mono.SafeStringMarshal:StringToUtf8 (string)
#14 0x00000040ba5a73 in Mono.SafeStringMarshal:get_Value ()
#15 0x00000040ba59b3 in System.Environment:internalGetEnvironmentVariable (string)
#16 0x00000040ba592f in System.Environment:GetEnvironmentVariable (string)
#17 0x00000040b9c2a3 in System.TimeZoneInfo:CreateLocal ()
#18 0x00000040b9bfe7 in System.TimeZoneInfo:get_Local ()
#19 0x00000040b9bf77 in System.TimeZoneInfo:GetDateTimeNowUtcOffsetFromUtc (System.DateTime,bool&)
#20 0x00000040b9b69b in System.DateTime:get_Now ()
#21 0x00000040b9b203 in BepInEx.Preloader.Entrypoint:Main ()
#22 0x00000040b9b610 in (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
#23 0x007f6d77046328 in mono_get_runtime_build_info
#24 0x007f6d771e53fe in mono_runtime_invoke
#25 0x007f6d771e7b90 in mono_unhandled_exception
#26 0x007f6d771e7a03 in mono_runtime_unhandled_exception_policy_set
#27 0x007f6d771e77f3 in mono_runtime_unhandled_exception_policy_set
#28 0x007f6d770bd519 in mono_debugger_run_finally
#29 0x007f6d770bbda3 in mono_debugger_run_finally
#30 0x007f6d771101bd in mono_breakpoint_clean_code
#31 0x00000041320830 in (Unknown)
#32 0x007f6d77046328 in mono_get_runtime_build_info
#33 0x007f6d771e53fe in mono_runtime_invoke
#34 0x007f6d771e5373 in mono_runtime_invoke
#35 0x007f6d7c2f500c in jit_init_hook
#36 0x007f6d7b197a30 in (Unknown)
#37 0x007f6d7b1aecdd in (Unknown)
#38 0x007f6d7b21b744 in (Unknown)
#39 0x007f6d7b21bfca in PlayerMain(int, char**)
#40 0x007f6d7a177d90 in PlayerMain(int, char**)
#41 0x007f6d7a177e40 in __libc_init_first
#42 0x0055bfbf0a5029 in __libc_start_main
/entrypoint.sh: line 46:    43 Segmentation fault      (core dumped) ./valheim_server.x86_64 -nographics -batchmode -name "${SERVER_NAME}" -port ${SERVER_PORT} -world "${WORLD}" -password "${PASSWORD}" -public ${PUBLIC_SERVER} -saveinterval ${BACKUP_INTERVAL} -backups ${BACKUP_COUNT} -backupshort ${BACKUP_SHORTTIME} -backuplong ${BACKUP_LONGTIME} $( [[ ${ENABLE_CROSSPLAY} -eq 1 ]] && echo " -crossplay ") > >(sed -uE "${CONSOLE_FILTER}")
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
```

**Comment by gOOvER** [comment]
> G'day mate,
> I've tested the egg without specifying a modpack and I can join the server
> I've tested the egg with a modpack and can confirm it downloads the files and the server is joinable
> 
> Another thing to note, and already mentioned in the discord:
> Goover's original Bepinex egg is broken due to Mono misconfiguration, error below:
> This has been fixed in this egg:)

Mono have nothing to do with this ;)

**Comment by gOOvER** [comment]
@HoleInTheSeat please Check #2455 and remove the unstripped libs. No need for 2 pr's :)

**Comment by HoleInTheSeat** [comment]
> @HoleInTheSeat please Check #2544 and remove the unstripped libs. No need for 2 pr's :)

Done and ready for testing. Ill test tonight if I have time.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thanks

**Pull request merged**
