### PR TITLE
Fix egg-sons-of-the-forest.json

### PR DESCRIPTION
**Pull request by Failcrafter1998**
# Description

Changed Server startup Command to fix Server crash on startup.
Added Configuration Variables to set needed Values

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by gOOvER** [comment]
Why it crashed? Never seen any Bugreport

**Comment by gOOvER** [comment]
Why should parsing the config fix a crash insteed using the same on startup?

**Comment by Failcrafter1998** [comment]
On my end with the Egg that i downloaded yesterday i just did not start, it was i a started where it showed that it was online but you could not join it,(i got a error in console as well) after my changes it just worked. Tested today again, and your egg runs now, dont know what happend there. Error i had yesterday: dedicated server #DSX System.InvalidCastException: Unable to cast object of type 'UdpEventStartFa filed' to type 'UdpEventStartDone'. As i said after my Changes it worked yesterday

**Comment by gOOvER** [comment]
> On my end with the Egg that i downloaded yesterday i just did not start, it was i a started where it showed that it was online but you could not join it,(i got a error in console as well) after my changes it just worked. Tested today again, and your egg runs now, dont know what happend there. Error i had yesterday: dedicated server #DSX System.InvalidCastException: Unable to cast object of type 'UdpEventStartFa filed' to type 'UdpEventStartDone'. As i said after my Changes it worked yesterday

cant confirm that.

Works as it should
```
DSL Autosave complete. Time: 2023-10-18 18:36:24 Slot: 1
#DSL Autosave complete. Time: 2023-10-18 18:46:24 Slot: 1
#DSL Incoming client connection with auth ticket
#DSL Steam auth successful for client 2 with steam id 76561197962941250, usernam
e gOOvER|OldNoobTV
#DSL Server waking up...
#DSL Set target framerate: 60
```

**Comment by Failcrafter1998** [comment]
As i said, yesterday i did not work, today it does so can be closed

**Comment by gOOvER** [comment]
> As i said, yesterday i did not work, today it does so can be closed

sry to say, but your changes are nothing other than the normal startup. Eggs works fine. Check your Hostserver

**Pull request closed without merging**
