### PR TITLE
Added Cryofall

### PR DESCRIPTION
**Pull request by hypersmc**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)? (Have not tested it as i don't own the game)
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Review by gOOvER — CHANGES_REQUESTED** [review]
see: https://github.com/parkervcp/eggs/pull/686#issuecomment-690271181

**Comment by gOOvER** [comment]
How long daes the start take? For me now about 20 mins and it'S not started

**Comment by gOOvER** [comment]
You can join server, but Server stay's in starting for me

**Comment by gOOvER** [comment]
Why not installing in /mnt/server?

So on every new Version a new Dir is created.

chrome_25QFYHv56C

**Comment by hypersmc** [comment]
> You run on every start of the Server the New Server Init CMD 
> 
> "dotnet CryoFall_Server.dll loadOrNew"
> 
> 
> 
> The Startup cmd is:
> 
> "dotnet CryoFall_Server.dll load"

You cannot use load before new. This was stated in their docs of the start command usage.

**Comment by hypersmc** [comment]
> Why not installing in /mnt/server?
> 
> 
> 
> So on every new Version a new Dir is created and old one will not deleted
> 
> 
> 
> chrome_25QFYHv56C
> 
> 

This was not an issue on my end but I did make it run from that specific dir as I thought it might have been a problem. This and the others are fixes I'm going to get finished today.

**Comment by hypersmc** [comment]
All of the above issues have been fixed.

**Review by gOOvER — APPROVED** [review]
Testet latest Egg and it work for me

**Comment by gOOvER** [comment]
Fixes: https://github.com/parkervcp/eggs/issues/685

**Comment by parkervcp** [comment]
@hypersmc folders should be all lowercase

**Comment by hypersmc** [comment]
@parkervcp Fixed

**Review by hypersmc — COMMENTED** [review]
nothing have changed from last approval.

**Comment by parkervcp** [comment]
This will get the download link for the latest server download. (As long as they keep the wiki up to date...)

`curl -sSL https://wiki.atomictorch.com/CryoFall/Server/Setup | grep 'SERVER DOWNLOAD' | grep -Eoi '<a [^>]+>' | grep -Eo 'href=\"[^\\\"]+\"' | grep -Eo '(http|https):\/\/[^\"]+' | tail -1 | cut -d'?' -f1`

**Review by fadedmax — APPROVED** [review]
LGTM

**Comment by parkervcp** [comment]
@hypersmc Please see my last comment about getting the latest version.

**Pull request merged**
