### PR TITLE
add CS2D egg

### LINKED ISSUE #2311: [Egg Request]: CS2D
### Does this expand an already existing service

No

### Link to a game or software

http://cs2d.com

### Links for the download

http://store.steampowered.com/app/666220

### Links for the install docs

https://www.cs2d.com/serverhosting.php

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

closes #2311 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

## New egg Submissions

1. [] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [x] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [x] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

@diedyesterdaywashere please test

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Note the install script logic looks like magic but if you read the # then you will see what steps it goos thrue

**Review by diedyesterdaywashere — APPROVED** [review]
tested the egg and the server was running.

**Comment by QuintenQVD0** [comment]
> tested the egg and the server was running.

can you connect?

**Comment by diedyesterdaywashere** [comment]
> > tested the egg and the server was running.
> 
> can you connect?

yep

**Comment by diedyesterdaywashere** [comment]
i was able to connect and everything was working

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
