### PR TITLE
fix:  jts3servermod egg ubuntu version

### PR DESCRIPTION
**Pull request by julian-ladjani**
### All Submissions:

* [x ] Have you followed the guidelines in our Contributing document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?

### Changes to an existing Egg:

1. [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x ] Have you tested your Egg changes?

### CODE REVIEW

**Comment by parkervcp** [comment]
Why exactly is this needed?

**Comment by julian-ladjani** [comment]
Repository problems:
```
Ign:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Ign:2 http://security.ubuntu.com/ubuntu cosmic-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu cosmic-security Release
  404  Not Found [IP: 91.189.88.149 80]
Ign:5 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 91.189.88.149 80]
Err:7 http://archive.ubuntu.com/ubuntu cosmic-updates Release
  404  Not Found [IP: 91.189.88.149 80]
Err:8 http://archive.ubuntu.com/ubuntu cosmic-backports Release
  404  Not Found [IP: 91.189.88.149 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package wget
E: Unable to locate package unzip
/mnt/install/install.sh: line 11: wget: command not found
/mnt/install/install.sh: line 16: unzip: command not found
mv: cannot stat '/tmp/JTS3ServerMod/*': No such file or directory

```

**Comment by parkervcp** [comment]
This is not an egg issue. Those IP's resolve perfectly fine for me. Which tells me you are having DNS issues on your host.

**Comment by parkervcp** [comment]
I also have full access to that IP address.

**Comment by julian-ladjani** [comment]
Anyway ubuntu 18.10 is not an LTS just continue to juste not LTS version you are right...

**Comment by parkervcp** [comment]
I fully plan on bumping all old script versions to 20.04 on its release.

**Comment by parkervcp** [comment]
I guess I am going to merge this even though it shouldn't actually resolve issues...

**Pull request merged**
