### PR TITLE
Added OpenRA Server

### PR DESCRIPTION
**Pull request by microton79**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by gOOvER** [comment]
"mkdir -p /mnt/server/"

This dir allready eixt. No need to create :)

**Comment by gOOvER** [comment]
Version should not be hardcoded:
"wget https://github.com/OpenRA/OpenRA/releases/download/release-20200503/OpenRA-Red-Alert-x86_64.AppImage"

Maybe Parkers Script is something for you:
https://github.com/parkervcp/eggs/blob/master/scripts/github_release_grabber.sh

**Comment by gOOvER** [comment]
Maybe you can add all three Versions: Release, Dune-2000 and Red-Alert

**Comment by microton79** [comment]
Thanks for the suggestions. I will see what i can optimize today. The release of the other games was also planned

**Comment by parkervcp** [comment]
@microton79 all folders "should" be lowercase. That's the standard I have on all the other folders.

Please update the game README with a standard port layout. See: https://github.com/parkervcp/eggs/blob/master/example/README.md

**Comment by microton79** [comment]
Okay now it should be done

**Comment by parkervcp** [comment]
@microton79 `PORT` can just be `SERVER_PORT` it's a default variable.

**Comment by microton79** [comment]
@parkervcp done

**Pull request merged**
