### PR TITLE
Update for new server binaries naming scheme

### PR DESCRIPTION
**Pull request by O1LER**
# Description

The beamMP egg needs to be updated in order to be able to pull the correct binary from https://github.com/BeamMP/BeamMP-Server/releases since the naming scheme got changed with v3.2.2 to accomodate a larger number of prebuilt binaries

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

### CODE REVIEW

**Comment by O1LER** [comment]
Removing the restriction on the MATCH variable is only the first step. Optimally, there would be checks that automatically determine if the host is x86 or arm, and if the distro is debian or ubuntu, since these options are now available prebuilt by beamMP. I will look into creating that

**Comment by QuintenQVD0** [comment]
> Removing the restriction on the MATCH variable is only the first step. Optimally, there would be checks that automatically determine if the host is x86 or arm, and if the distro is debian or ubuntu, since these options are now available prebuilt by beamMP. I will look into creating that

Give me 5 min, I do it for you.

**Comment by O1LER** [comment]
Ive done something wrong when updating my main branch i guess, i dont want to revert my changes from May

**Comment by QuintenQVD0** [comment]
> Ive done something wrong when updating my main branch i guess, i dont want to revert my changes from May

That's fine, I handle that for you.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! Thanks

**Comment by QuintenQVD0** [comment]
Thank you for bringing this to the repo! Now the egg will based on the host arch download the debian 11 arm64 one or the debian 11 x86_64 one

**Comment by O1LER** [comment]
Ok, nice. I guess you left the last check for Server-linux in place for backwards compatibility should someone choose an older version before v3.2.2

**Comment by QuintenQVD0** [comment]
> Ok, nice. I guess you left the last check for Server-linux in place for backwards compatibility should someone choose an older version before v3.2.2

I could do that. let me quickly implement that

**Comment by O1LER** [comment]
I mean it is still there, its in the function that prints `No valid versions found. Defaulting to the latest release`

**Comment by QuintenQVD0** [comment]
There is no real need for supporting older version as they only support the latest version.
I modified the fallback logic so that it tries to find the x64 version with the keywords debian and server

**Comment by QuintenQVD0** [comment]
> I mean it is still there, its in the function that prints `No valid versions found. Defaulting to the latest release` that then goes to grab `Server-linux` but this binary will not be published anymore in the future

The server-linux does not run in pterodactyl anymore.

**Comment by O1LER** [comment]
> > I mean it is still there, its in the function that prints `No valid versions found. Defaulting to the latest release` that then goes to grab `Server-linux` but this binary will not be published anymore in the future
> 
> The server-linux does not run in pterodactyl anymore.

Since that was the ubuntu version i guess?

Thanks for the help, much appreciated

**Pull request merged**
