### PR TITLE
Add Rigs of Rods (RoRNet 2.38 for 0.4.7.0 clients)

### PR DESCRIPTION
**Pull request by ZentroPlays**
Install the server and it'll automatically startup. Change variables and restart to apply changes to the configuration.

### CODE REVIEW

**Comment by Sir3lit** [comment]
The install image could be an alpine and not a ubuntu 18.04 image, for the sakes of disk space

**Comment by ZentroPlays** [comment]
I've tested this on a few different servers. Ran without issue.

**Comment by Alauraa** [comment]
I'd recommend that this gets updated to 4.8RC4 for rigs of rods, instead of staying on 2.38

**Comment by parkervcp** [comment]
I will be closing this in favor of getting a new PR that uses the new PR template I have added to the repo.

If you still want to add this please resubmit a PR for this.

**Pull request closed without merging**
