### PR TITLE
Uptime Kuma - fix DB und cleanup

### PR DESCRIPTION
**Pull request by gOOvER**
# Description

- fix problems with database in some cases
- cleanup the installscript
- cleanup variables
- cleanup startup. Autoupdate can cause problems. To update Uptime Kuma, reinstall the server
- Support for optional apprise (https://github.com/caronc/apprise)

fixes: #2483 

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@nateloeffel Can you please test this?

**Comment by gOOvER** [comment]
Please create a new server or update the startup ind existing server

**Comment by nateloeffel** [comment]
yup this is working for me

**Comment by gOOvER** [comment]
> yup this is working for me

ty for the feedback. The db folder only contains the start db and the patches; so the db folder ist a worst dir to use, because it will be overwritten.

I copy now the kuma.db to /data/, so the other is safe.

The dev changed the way, how the cofinbg file will be created. Now it should be created everytime.

The next changes to the egg will be backup for the db

**Comment by gOOvER** [comment]
@QuintenQVD0 please wait for the readme update commit, before you merge it :)

**Comment by gOOvER** [comment]
all done and ready to merge :)

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
