### PR TITLE
Update Valheim BepINex API url

### PR DESCRIPTION
**Pull request by thomasbonsirven**
# Description

the sub-domaine not work for install BepInEx mod.
Error 404.

Without sub-domain is work.

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
this was not exported from the panel and you litterly removed the whole template.

At least re-export this from a panel and fully replace it here, else this will be converted to a draft

**Comment by thomasbonsirven** [comment]
Aaah, ok.
I don't have to modify the egg directly in GitHub, but in the panel and then export it to copy/paste it into gihub every line. Is that correct?

**Comment by QuintenQVD0** [comment]
> Aaah, ok. I don't have to modify the egg directly in GitHub, but in the panel and then export it to copy/paste it into gihub every line. Is that correct?

you just import the egg, make the needed to be changed in the panel, export it. Then replace the full file here with the one you got from your export

**Comment by ImKringle** [comment]
Check other Update PRs for how this is done, you replace the updated lines not the entire egg

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by thomasbonsirven** [comment]
Hey,

Thanks you @QuintenQVD0, for the export :)
I dont have the time this morning.

**Pull request merged**
