### PR TITLE
fix: support 1.4+ tmodloader

### PR DESCRIPTION
**Pull request by digitalravenstudio**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?

The new 1.4 stable release of tmodloader changed up a lot of their underlying systems, which in turn was not compatible with the current egg.
I have done minor changes to the install script (listed below), as well as switched the used docker image from "debian_mono-5" to "dotnet_6". This change was needed, due to the fact that the tmodloader 1.4 requires the dotnet framework to function.

2. [x] Have you tested your Egg changes?

- Installation and running various versions of tmodloader 1.3
- Installation and running various versions of tmodloader 1.4
- Installation and running tmodloader using the "latest" tag
- Runtime variables still work as intended

## Updated Scrip

```bash
#!/bin/bash
# Vanilla tModloader Installation Script
#
# Server Files: /mnt/server
## install packages to get version and download links
apt update
apt install -y curl jq file unzip

GITHUB_PACKAGE=tModLoader/tModLoader

if [ -z "$GITHUB_USER" ] && [ -z "$GITHUB_OAUTH_TOKEN" ] ; then
    echo -e "using anon api call"
else
    echo -e "user and oauth token set"
    alias curl='curl -u $GITHUB_USER:$GITHUB_OAUTH_TOKEN '
fi

## get release info and download links
LATEST_JSON=$(curl --silent "https://api.github.com/repos/tmodloader/tmodloader/releases" | jq -c '.[]' | head -1)
RELEASES=$(curl --silent "https://api.github.com/repos/$GITHUB_PACKAGE/releases" | jq '.[]')


if [ -z "$VERSION" ] || [ "$VERSION" == "latest" ]; then
    echo -e "defaulting to latest release"
    DOWNLOAD_LINK=$(echo $LATEST_JSON | jq .assets | jq -r .[].browser_download_url | grep -i tmodloader.zip)
else
    VERSION_CHECK=$(echo $RELEASES | jq -r --arg VERSION "$VERSION" '. | select(.tag_name==$VERSION) | .tag_name')
    if [ "$VERSION" == "$VERSION_CHECK" ]; then
        if [[ "$VERSION" == v0* ]]; then
            DOWNLOAD_LINK=$(echo $RELEASES | jq -r --arg VERSION "$VERSION" '. | select(.tag_name==$VERSION) | .assets[].browser_download_url' | grep -i linux | grep -i zip)
        else
            DOWNLOAD_LINK=$(echo $RELEASES | jq -r --arg VERSION "$VERSION" '. | select(.tag_name==$VERSION) | .assets[].browser_download_url' | grep -i tmodloader.zip)
        fi
    else
        echo -e "defaulting to latest release"
        DOWNLOAD_LINK=$(echo $LATEST_JSON | jq .assets | jq -r .[].browser_download_url | grep -i tmodloader.zip)
    fi
fi

## mkdir and cd to /mnt/server/
mkdir -p /mnt/server

cd /mnt/server

## download release
echo -e "running: curl -sSL ${DOWNLOAD_LINK} -o ${DOWNLOAD_LINK##*/}"
curl -sSL ${DOWNLOAD_LINK} -o ${DOWNLOAD_LINK##*/}

FILETYPE=$(file -F ',' ${DOWNLOAD_LINK##*/} | cut -d',' -f2 | cut -d' ' -f2)
if [ "$FILETYPE" == "gzip" ]; then
    tar xzvf ${DOWNLOAD_LINK##*/}
elif [ "$FILETYPE" == "Zip" ]; then
    unzip -o ${DOWNLOAD_LINK##*/}
else
    echo -e "unknown filetype. Exiting"
    exit 2 
fi

if [[ "$VERSION" == v0* ]]; then
    chmod +x tModLoaderServer.bin.x86_64
    chmod +x tModLoaderServer
else
    #tiny startup script for backward compatibility
    echo 'dotnet tModLoader.dll -server "$@"' > tModLoaderServer
    chmod +x tModLoaderServer
fi

echo -e "Cleaning up extra files."
rm -rf terraria-server-${CLEAN_VERSION}.zip rm ${DOWNLOAD_LINK##*/}
if [[ "$VERSION" != v0* ]]; then
    rm -rf DedicatedServerUtils LaunchUtils PlatformVariantLibs tModPorter RecentGitHubCommits.txt *.bat *.sh
fi
```

## Related
This issue: https://github.com/parkervcp/eggs/issues/1644

### CODE REVIEW

**Comment by Software-Noob** [comment]
Using a shell script to start is generally a no go. Anything the scripts are doing can be extracted and done properly, especially when majority of the checks they run are doing nothing good in pterodactyl environment

**Comment by digitalravenstudio** [comment]
As suggested by @Software-Noob, I have rewritten the installation script to do all the checking/installation work and simplify the startup command.

Note that the file/script "tModLoaderServer" still includes one command to support proper backward compatibility without doing various checks inside the startup command itself.
**Line 98**: `echo '/home/container/dotnet/'$dotnet_version'/dotnet tModLoader.dll -server "$@"' > tModLoaderServer`

**Comment by digitalravenstudio** [comment]
Simplified the install script further by using the proper "dotnet_6" docker image.

**Comment by ndisalvio3** [comment]
When using latest panel, wings, and tmodloader it errors out with jq therefore causing a curl error. I have made sure to use the dotnet yolk as well.

`jq: error (at <stdin>:1): Cannot index array with string "assets"
running: curl -sSL  -o 
curl: option -o: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]
unknown filetype. Exiting
`

**Comment by digitalravenstudio** [comment]
> When using latest panel, wings, and tmodloader it errors out with jq therefore causing a curl error. I have made sure to use the dotnet yolk as well.
> 
> `jq: error (at <stdin>:1): Cannot index array with string "assets" running: curl -sSL -o curl: option -o: requires parameter curl: try 'curl --help' or 'curl --manual' for more information Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type] [-e <testname>] [-F <separator>] [-f <namefile>] [-m <magicfiles>] [-P <parameter=value>] <file> ... file -C [-m <magicfiles>] file [--help] unknown filetype. Exiting `

Cannot reproduce that on the latest version of panel, wings, and tmodloader.
My assumption is that your container cannot access the API for some reason.
Can you try to run `curl --silent "https://api.github.com/repos/tmodloader/tmodloader/releases" | jq -c '.[]' | head -1` or just `curl --silent "https://api.github.com/repos/tmodloader/tmodloader/releases"` on your server and inside the container manually?

**Comment by ndisalvio3** [comment]
I can run it on both with no errors. It seems to not be an issue curling jq isnt parsing the download url properly.

**Comment by phit** [comment]
had no issues with this, thanks!

**Comment by phit** [comment]
that's not why your server isnt't launching, that's a normal warning

image

**Comment by gammeflamme** [comment]
Yes, I was unclear in my comment, the server sucsesfully loads but it can't access steam so it can't use the workshop to download mods. Is that normal behaviour?

**Comment by digitalravenstudio** [comment]
> Yes, I was unclear in my comment, the server sucsesfully loads but it can't access steam so it can't use the workshop to download mods. Is that normal behaviour?

That's expected behavior.
The server doesn't have any steam functionality installed. As far as I am aware, you aren't able to auto-download on the 1.3 version either.
Instead you will have to upload the mod files manually from your client.

This **could** potentially be an additional feature, but considering it wasn't on the original version, it shouldn't count as a bug.

**Comment by Software-Noob** [comment]
Steamclient.so used to be shipped with the older releases. This stopped with their automated releases.

**Comment by digitalravenstudio** [comment]
Ah, my mistake then.
I will have to look into it in that case.

**Comment by digitalravenstudio** [comment]
So, I have gotten the server to install the correct steamclient.so, but the thing I don't understand is, how would one go about installing terraria mods via workshop on a dedicated server? Every single method I found online talks about manual upload, so I am rather unsure about what the use of a running steam client would be,

**Comment by gammeflamme** [comment]
I somewhat naively thought simply having an "enabled.json" file in the mods folder would install them for you.

**Comment by Software-Noob** [comment]
Steam client is required for steam at minimum. `-steam -lobby`. Workshop pulling is supported by many games or/and scripts, but I always prefer to do it manually thus have no knowledge if or how it works with this. Their github wiki might have answers.

**Comment by phit** [comment]
if you remove all the startup arguments that cause it to autoload a world you get a cli that allows you to manage worlds, download mods etc. I do believe it requires Steam to be actually running though

**Comment by Software-Noob** [comment]
> > Steam client is required for steam at minimum. `-steam -lobby`. Workshop pulling is supported by many games or/and scripts, but I always prefer to do it manually thus have no knowledge if or how it works with this. Their github wiki might have answers.
> 
> The game does support "modpacks", however there is no described way, in the wiki or elsewhere, to download them from the CLI (See: [https://github.com/tModLoader/tModLoader/wiki/Mod-Browser](https://github.com/tModLoader/tModLoader/wiki/Mod-Browser))
> Not to mention that even when you run steamclient.so, the game seems to expect a running steam service in the background.
> 
> ```
> [S_API] SteamAPI_Init(): Loaded '/home/container/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
> CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
> Setting breakpad minidump AppID = 1281930
> [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
> ```
> 
> I do believe that the tmodloader devs intended steam to only be used on local servers, not dedicated software like this.
> This would also explain why they removed the steamclient.so file in the first place.

You don't have to worry about mods as it's outside the scope of this PR. You can open a new a PR if you do figure it out.

I will try to review this on Sunday once I have spare time. Too busy with other stuff so many of the issues and PRs are unfortunately neglected for which I am sorry.

**Review by parkervcp — APPROVED** [review]

**Review by Software-Noob — APPROVED** [review]
LGTM. Thank you for contributing :+1:

I've cleaned it up and updated it to the PTDL_V2 standards for a better user experience and the requirement of a 1.8+ Panel version.

**Pull request merged**
