### PR TITLE
Update egg-elixir.json

### PR DESCRIPTION
**Pull request by Leastrio**
# Description

The previous elixir egg was filled with bugs that caused certain features to not work.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: Simple update from github

* [x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@Leastrio an egg will not even be revieuwed if it is not exported from a panel!

**Comment by Leastrio** [comment]
Could someone else do it? I dont have access to a panel

**Comment by QuintenQVD0** [comment]
> Could someone else do it? I dont have access to a panel

Then how did you make this changes? as you are not allowed to edit the .json file directly!

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
