### PR TITLE
Added ArchiSteamFarm

### PR DESCRIPTION
**Pull request by NgLoader**
### New Server Submissions:

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the server to the main README.md?
4. [X] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by parkervcp** [comment]
Why does this need a custom image?

https://github.com/parkervcp/images/tree/debian/dotnet

**Comment by NgLoader** [comment]
ArchiSteamFarm run only on x64 arch and you need to set the DOTNET_BUNDLE_EXTRACT_BASE_DIR to another directory because of permission issues.
When you have any idea how I can change that, let me know that please.

**Comment by parkervcp** [comment]
You can set the ENV vars in the egg as variables.

**Comment by NgLoader** [comment]
Okay, I test it tomorrow

**Comment by NgLoader** [comment]
> You can set the ENV vars in the egg as variables.
Okay, thanks

I have changed the image to https://github.com/parkervcp/images/tree/debian/dotnet and tested it.

**Comment by parkervcp** [comment]
Start scripts are usually user modifiable. can we get rid of that?

**Comment by NgLoader** [comment]
Like that?
And yes we can change it and it works for me.
But the issue https://github.com/JustArchiNET/ArchiSteamFarm/issues/1812 is still there I think.

**Comment by NgLoader** [comment]
Okay, looks like the problem is fixed. so we can run it on Docker with no problem.

**Comment by tiweb442** [comment]
i try this pull on my panel and its working fine whit no bug

**Comment by parkervcp** [comment]
So while it is a working egg I don't know how steam feels about this tool and am not really comfortable with it.

**Comment by parkervcp** [comment]
Going to close this out as I don't want to clash with valve with this if it ever becomes an issue.

**Comment by NgLoader** [comment]
I found this comment on steam by an administator

> It's entirely impossible you got banned over a single automated trade. ASF is a grey area, but Archi is in direct contact with Valve, and ensures that nothing violates ToS at all times, and if it does, it would be disabled prior to anyone actually being punished for it.
The only reports I've seen of people getting banned is for such stupid things as using !loot asf with 100+ bots.
[Reference](https://steamcommunity.com/groups/archiasf/discussions/6/1694922526905360875/)

**Comment by parkervcp** [comment]
as stated - if it ever becomes an issue.

**Pull request closed without merging**
