### PR TITLE
Updated the muse egg

### PR DESCRIPTION
**Pull request by meesvw**
# Description

Added git as package in the install script to prevent the following error when creating or installing the egg: "error Couldn't find the binary git" I saw a couple of people in the Discord server having the same issue.

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You must fully replace the egg. A change must be made in the panel and fully exported here! Else we will close this.

**Comment by meesvw** [comment]
@QuintenQVD0 I fully replaced the egg via export through the panel.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 I fully replaced the egg via export through the panel.

I will check tommorow. Thx

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
