### PR TITLE
small grammar fix

### PR DESCRIPTION
**Pull request by camjac251**
grammar fix

### CODE REVIEW

**Comment by Hydra2k** [comment]
this is incorrect

**Comment by camjac251** [comment]
it's is short for it is.  https://www.dictionary.com/e/its-vs-its/

**Comment by Hydra2k** [comment]
it was correct originally

**Comment by camjac251** [comment]
Did you happen to check out the link Hydra? I was hoping that it could offer some clarity on the difference between the two.

**Pull request merged**
