### PR TITLE
Add NeoForge egg for Minecraft Java

### PR DESCRIPTION
**Pull request by glorantq**
This commit adds an egg for the new Minecraft Forge fork called NeoForge.

# Description

This PR adds an egg for NeoForge, a fork of Forge, for Minecraft Java. The egg supports all NeoForge versions starting from Minecraft 1.20.1.

I made this PR despite #2744 existing, since my version of the script does not require a 3rd party mirror to be kept up to date, and supports setting both a Minecraft version (MC_VERSION) or a specific NeoForge version (NEOFORGE_VERSION) to be used.

## Checklist for all submissions

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you tested and reviewed your changes with confidence that everything works?
* [X] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [X] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [X] The egg was exported from the panel

## New egg Submissions

1. [X] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [X] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X] The egg was exported from the panel

### CODE REVIEW

**Comment by glorantq** [comment]
Yes, I mentioned that in the description, with justification as to why I still made this PR.

**Comment by InvalidPandaa** [comment]
Your egg is better I guess, you implemented the version selector

**Review by QuintenQVD0 — APPROVED** [review]
For me, this is ok to merge. As it is special enough and not yet another fork.

**Comment by QuintenQVD0** [comment]
@parkervcp Up to you if you want this or not in the repo.

**Pull request merged**
