### PR TITLE
Add Wurm Unlimited Egg

### PR DESCRIPTION
**Pull request by tehguy**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

Requested in #160 , using bits from #187's egg as they worked.

### CODE REVIEW

**Comment by parkervcp** [comment]
Be sure to add this to the steamcmd servers readme too

**Comment by tehguy** [comment]
Felt like I'd missed something a bit obvious, change has been made

**Comment by parkervcp** [comment]
@tehguy You still haven't resolved the one thing I specifically said no to and that is the start script.

**Comment by parkervcp** [comment]
I am going to close this. If you make the changes I asked for please re-open this pr.

**Comment by parkervcp** [comment]
Yeah this from late 2019. I am going to close it out. If anyone would like to fix and and PR it with my requested fix then We can look at it again.

**Pull request closed without merging**
