### PR TITLE
update veloren

### PR DESCRIPTION
**Pull request by QuintenQVD0**
# Description

- Update to new image
- move to pebuild bin as there now provide and it reduces install time
- change install image as rust is not more needed
- move from downloading the config file to just generating it
- add variables for version and metric port
## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
This can not yet be merged as the file parser does not do what I want atm

**Comment by QuintenQVD0** [comment]
- added a way to at least automatic set the game port on first install:
afbeelding
- added a note to the README that the manly have to set the game port in the config file

**Comment by QuintenQVD0** [comment]
I can confirm it is working:
afbeelding
I can join

**Comment by QuintenQVD0** [comment]
Converted to draft as they gave me a pi URL where you can get the latest version without GitHub

**Comment by QuintenQVD0** [comment]
Switched to using there api for downloading latest version + fix config file download

**Review by parkervcp — APPROVED** [review]
LGTM

**Pull request merged**
