### PR TITLE
replace youtube-dl with youtube-dlp because yt-dl is slower and forgotten

### PR DESCRIPTION
**Pull request by hardixnph**
youtube-dlp is a fork of youtube-dl https://github.com/yt-dlp/yt-dlp

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?: N/A

### Changes to an existing Egg:

1. [x] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [x] Have you tested your Egg changes?

### CODE REVIEW

**Comment by gOOvER** [comment]
i don't know, if the install script is the right place for youtub.dl. This must installed from image

**Comment by hardixnph** [comment]
> i don't know, if the install script is the right place for youtub.dl. This must installed from image

The old youtube-dl was installed from the install script, I just replaced it with youtube-dlp

**Comment by gOOvER** [comment]
> > i don't know, if the install script is the right place for youtub.dl. This must installed from image
> 
> The old youtube-dl was installed from the install script, I just replaced it with youtube-dlp

But install script is only for install. I think, this must be reviewed

**Comment by gOOvER** [comment]
The next question is; can Sinusbot handle this new lib. I created a Test Image on my repo. You can pn me on dicord and i will send you the link for testing

**Comment by hardixnph** [comment]
> The next question is; can Sinusbot handle this new lib. I created a Test Image on my repo. You can pn me on dicord and i will send you the link for testing

Yes, it can, I tested it inside Pterodactyl and outside it

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
